export default {
  "AND": "UNDEFINED",
  "Abstract": "UNDEFINED",
  "Access stream directly in your browser": "UNDEFINED",
  "Add": "UNDEFINED",
  "Add attack patterns": "UNDEFINED",
  "Add data components": "UNDEFINED",
  "Add data source": "UNDEFINED",
  "Additional mandatory attributes": "UNDEFINED",
  "Aliases": "UNDEFINED",
  "Allowed markings": "UNDEFINED",
  "Also delete these elements": "UNDEFINED",
  "Analysis": "UNDEFINED",
  "Areas": "UNDEFINED",
  "Artifacts": "UNDEFINED",
  "Associated file": "UNDEFINED",
  "Attack Patterns": "UNDEFINED",
  "Author": "UNDEFINED",
  "Auto new markings": "UNDEFINED",
  "Automatic": "UNDEFINED",
  "Automatic references at file upload": "UNDEFINED",
  "Background tasks": "UNDEFINED",
  "Basic information": "UNDEFINED",
  "Browse the link": "UNDEFINED",
  "Bulk search": "UNDEFINED",
  "CRITICAL": "UNDEFINED",
  "Campaigns": "UNDEFINED",
  "Cancel": "UNDEFINED",
  "Capabilities": "UNDEFINED",
  "Cascade delete": "UNDEFINED",
  "Case priority": "UNDEFINED",
  "Case severity": "UNDEFINED",
  "Channels": "UNDEFINED",
  "Cities": "UNDEFINED",
  "City": "UNDEFINED",
  "Clear filters": "UNDEFINED",
  "Close": "UNDEFINED",
  "Color": "UNDEFINED",
  "Confidence level": "UNDEFINED",
  "Configuration": "UNDEFINED",
  "Connector": "UNDEFINED",
  "Connectors": "UNDEFINED",
  "Content": "UNDEFINED",
  "Countries": "UNDEFINED",
  "Country": "UNDEFINED",
  "Courses of action": "UNDEFINED",
  "Create": "UNDEFINED",
  "Create a case incident": "UNDEFINED",
  "Create a city": "UNDEFINED",
  "Create a country": "UNDEFINED",
  "Create a data component": "UNDEFINED",
  "Create a data source": "UNDEFINED",
  "Create a live trigger": "UNDEFINED",
  "Create a note": "UNDEFINED",
  "Create a opinions": "UNDEFINED",
  "Create a region": "UNDEFINED",
  "Create a regular digest": "UNDEFINED",
  "Create a status": "UNDEFINED",
  "Create a status template": "UNDEFINED",
  "Create a vocabulary": "UNDEFINED",
  "Create a vulnerability": "UNDEFINED",
  "Create an area": "UNDEFINED",
  "Create an external reference": "UNDEFINED",
  "Create an incident": "UNDEFINED",
  "Create external reference at upload": "UNDEFINED",
  "Creation": "UNDEFINED",
  "Creation date": "UNDEFINED",
  "Creators": "UNDEFINED",
  "Custom dashboards": "UNDEFINED",
  "Data": "UNDEFINED",
  "Data components": "UNDEFINED",
  "Data import and analyst workbenches": "UNDEFINED",
  "Data sharing": "UNDEFINED",
  "Data source": "UNDEFINED",
  "Data sources": "UNDEFINED",
  "Default hidden entity types": "UNDEFINED",
  "Default mandatory attributes": "UNDEFINED",
  "Default membership": "UNDEFINED",
  "Delete": "UNDEFINED",
  "Delete this file": "UNDEFINED",
  "Deletion": "UNDEFINED",
  "Description": "UNDEFINED",
  "Details": "UNDEFINED",
  "Digest with multiple notifications": "UNDEFINED",
  "Direct Update": "UNDEFINED",
  "Disabled": "UNDEFINED",
  "Download this file": "UNDEFINED",
  "EXPIRATION_SCHEDULER": "Expiration scheduler",
  "EXTERNAL_IMPORT": "Data import",
  "Elements successfully copied": "UNDEFINED",
  "Email": "UNDEFINED",
  "Email address": "UNDEFINED",
  "Enable this feature": "UNDEFINED",
  "Enforce reference": "UNDEFINED",
  "Enforce references": "UNDEFINED",
  "Entities": "UNDEFINED",
  "Entities distribution": "UNDEFINED",
  "Events": "UNDEFINED",
  "Explanation": "UNDEFINED",
  "Exported files": "UNDEFINED",
  "External ID": "UNDEFINED",
  "External References": "UNDEFINED",
  "Feedback": "UNDEFINED",
  "File successfully removed": "UNDEFINED",
  "First seen": "UNDEFINED",
  "Firstname": "UNDEFINED",
  "Friday": "UNDEFINED",
  "GRAPHQL_API": "GraphQL API",
  "Generate an export": "UNDEFINED",
  "Global keyword": "UNDEFINED",
  "Granted by default at user creation": "UNDEFINED",
  "Groupings": "UNDEFINED",
  "Groups": "UNDEFINED",
  "Groups with this role": "UNDEFINED",
  "HIGH": "UNDEFINED",
  "HISTORY_MANAGER": "History manager",
  "Hidden entity types": "UNDEFINED",
  "Hidden in interface": "UNDEFINED",
  "Hidden in roles": "UNDEFINED",
  "Hide in the platform": "UNDEFINED",
  "History": "UNDEFINED",
  "INTERNAL_ENRICHMENT": "Enrichment",
  "INTERNAL_EXPORT_FILE": "Files export",
  "INTERNAL_IMPORT_FILE": "Files import",
  "Incident date": "UNDEFINED",
  "Incident type": "UNDEFINED",
  "Incidents": "UNDEFINED",
  "Indicators": "UNDEFINED",
  "Individuals": "UNDEFINED",
  "Information": "UNDEFINED",
  "Infrastructures": "UNDEFINED",
  "Intrusion sets": "UNDEFINED",
  "Investigations": "UNDEFINED",
  "Knowledge": "UNDEFINED",
  "LOW": "UNDEFINED",
  "Label": "UNDEFINED",
  "Language": "UNDEFINED",
  "Last": "UNDEFINED",
  "Last seen": "UNDEFINED",
  "Lastname": "UNDEFINED",
  "Latitude": "UNDEFINED",
  "Launch an import": "UNDEFINED",
  "Launch an import of this file": "UNDEFINED",
  "Layers": "UNDEFINED",
  "Likelihood": "UNDEFINED",
  "Limits": "UNDEFINED",
  "Live trigger": "UNDEFINED",
  "Login": "UNDEFINED",
  "Logout": "UNDEFINED",
  "Longitude": "UNDEFINED",
  "MEDIUM": "UNDEFINED",
  "Malwares": "Malware",
  "Mandatory attributes": "UNDEFINED",
  "Marking": "UNDEFINED",
  "Markings": "UNDEFINED",
  "Maximum": "UNDEFINED",
  "Members": "UNDEFINED",
  "Message": "UNDEFINED",
  "Minimum": "UNDEFINED",
  "Minimum one outcome": "UNDEFINED",
  "Minimum one trigger": "UNDEFINED",
  "Modification": "UNDEFINED",
  "Modification date": "UNDEFINED",
  "Monday": "UNDEFINED",
  "Month day": "UNDEFINED",
  "Multiple": "UNDEFINED",
  "NOTIFICATION_MANAGER": "Notification generation manager",
  "Name": "UNDEFINED",
  "Narratives": "UNDEFINED",
  "No": "UNDEFINED",
  "No available options": "UNDEFINED",
  "No available public stream on this platform": "UNDEFINED",
  "No description": "UNDEFINED",
  "No export connector available to generate an export": "UNDEFINED",
  "No file for the moment": "UNDEFINED",
  "No label": "UNDEFINED",
  "Nonee": "None",
  "Note types": "UNDEFINED",
  "Notes": "UNDEFINED",
  "Notes about this entity": "UNDEFINED",
  "Notes about this relationship": "UNDEFINED",
  "Notification": "UNDEFINED",
  "Notifications and triggers": "UNDEFINED",
  "OR": "UNDEFINED",
  "Object": "UNDEFINED",
  "Objective": "UNDEFINED",
  "Observable type": "UNDEFINED",
  "Observables": "UNDEFINED",
  "Observables distribution": "UNDEFINED",
  "Observed datas": "Observed data",
  "Opinion": "UNDEFINED",
  "Opinions": "UNDEFINED",
  "Order": "UNDEFINED",
  "Organizations": "UNDEFINED",
  "Organizations sharing": "UNDEFINED",
  "Others": "UNDEFINED",
  "Overview": "UNDEFINED",
  "PUBLISHER_MANAGER": "Notification publishing manager",
  "Password": "UNDEFINED",
  "Pattern type": "UNDEFINED",
  "Period": "UNDEFINED",
  "Permissions": "UNDEFINED",
  "Platforms": "UNDEFINED",
  "Positions": "UNDEFINED",
  "Postal code": "UNDEFINED",
  "Priority": "UNDEFINED",
  "Processed time": "Data sent",
  "Profile": "UNDEFINED",
  "Public stream collections": "UNDEFINED",
  "Publication date": "UNDEFINED",
  "RETENTION_MANAGER": "Retention manager",
  "RFIs": "UNDEFINED",
  "RULE_ENGINE": "Rules engine",
  "Rating": "UNDEFINED",
  "Received time": "Triggered",
  "Reference modification": "UNDEFINED",
  "Region": "UNDEFINED",
  "Regions": "UNDEFINED",
  "Regular digest": "UNDEFINED",
  "Related cases": "UNDEFINED",
  "Related entities": "UNDEFINED",
  "Relation type": "UNDEFINED",
  "Relationships": "UNDEFINED",
  "Remove": "UNDEFINED",
  "Remove from this entity": "UNDEFINED",
  "Remove from this object": "UNDEFINED",
  "Response type": "UNDEFINED",
  "Roles": "UNDEFINED",
  "STREAM": "Streaming",
  "SUBSCRIPTION_MANAGER": "Subscriptions manager",
  "SYNC_MANAGER": "Synchronization manager",
  "Saturday": "UNDEFINED",
  "Save": "UNDEFINED",
  "Search": "UNDEFINED",
  "Sectors": "UNDEFINED",
  "Select your file": "UNDEFINED",
  "Severity": "UNDEFINED",
  "Share": "UNDEFINED",
  "Share with an organization": "UNDEFINED",
  "Sightings": "UNDEFINED",
  "Sign in": "UNDEFINED",
  "Source": "UNDEFINED",
  "Source name": "UNDEFINED",
  "Street address": "UNDEFINED",
  "Submit a feedback": "UNDEFINED",
  "Sunday": "UNDEFINED",
  "Synchronization": "UNDEFINED",
  "Systems": "UNDEFINED",
  "TASK_MANAGER": "Tasks manager",
  "Target": "UNDEFINED",
  "Tasks": "UNDEFINED",
  "The code is not correct": "UNDEFINED",
  "The minimum value cannot be greater than maximum value": "UNDEFINED",
  "The value is too long": "UNDEFINED",
  "The value must be an URL": "UNDEFINED",
  "The value must be an email address": "UNDEFINED",
  "The value must be between minimum and maximum value": "UNDEFINED",
  "The value must be greater than or equal to 0": "UNDEFINED",
  "The value must be less than or equal to 100": "UNDEFINED",
  "This configuration is not available for this entity type": "UNDEFINED",
  "This field is required": "UNDEFINED",
  "This field must be a number": "UNDEFINED",
  "Threat actors": "UNDEFINED",
  "Thursday": "UNDEFINED",
  "Ticks": "UNDEFINED",
  "Time": "UNDEFINED",
  "Token": "UNDEFINED",
  "Tools": "UNDEFINED",
  "Triggering on": "UNDEFINED",
  "Triggers": "UNDEFINED",
  "Tuesday": "UNDEFINED",
  "Type": "UNDEFINED",
  "Types": "UNDEFINED",
  "URL": "UNDEFINED",
  "Unknown": "Unknown",
  "Update": "UNDEFINED",
  "Update a case incident": "UNDEFINED",
  "Update a city": "UNDEFINED",
  "Update a data component": "UNDEFINED",
  "Update a data source": "UNDEFINED",
  "Update a feedback": "UNDEFINED",
  "Update a group": "UNDEFINED",
  "Update a note": "UNDEFINED",
  "Update a region": "UNDEFINED",
  "Update a role": "UNDEFINED",
  "Update a status": "UNDEFINED",
  "Update a status template": "UNDEFINED",
  "Update a trigger": "UNDEFINED",
  "Update a user": "UNDEFINED",
  "Update an area": "UNDEFINED",
  "Update an attribute": "UNDEFINED",
  "Update an country": "UNDEFINED",
  "Update an external reference": "UNDEFINED",
  "Update an incident": "UNDEFINED",
  "Updated the": "UNDEFINED",
  "Uploaded files": "UNDEFINED",
  "Use": "UNDEFINED",
  "Use Alt + click to exclude items": "Use Alt + click to exclude items",
  "User interface": "UNDEFINED",
  "Validate": "UNDEFINED",
  "Value": "UNDEFINED",
  "Vulnerabilities": "UNDEFINED",
  "Webhook": "UNDEFINED",
  "Wednesday": "UNDEFINED",
  "Week day": "UNDEFINED",
  "Workflow": "UNDEFINED",
  "Workflow of": "UNDEFINED",
  "Write a note": "UNDEFINED",
  "Yes": "UNDEFINED",
  "_": "UNDEFINED",
  "added a note": "UNDEFINED",
  "day": "UNDEFINED",
  "entity_Administrative-Area": "Area",
  "entity_All": "All entities",
  "entity_Analysis": "Analysis",
  "entity_Arsenal": "Arsenal",
  "entity_Artifact": "Artifact",
  "entity_Attack-Pattern": "Attack Pattern",
  "entity_Autonomous-System": "Autonomous System",
  "entity_Bank-Account": "Bank account",
  "entity_Campaign": "Campaign",
  "entity_Case": "Case",
  "entity_Case-Incident": "Incident response",
  "entity_Case-Rfi": "Request for information",
  "entity_Case-Rft": "Request for takedown",
  "entity_Channel": "Channel",
  "entity_City": "City",
  "entity_Country": "Country",
  "entity_Course-Of-Action": "Course of action",
  "entity_Cryptocurrency-Wallet": "Cryptocurrency wallet",
  "entity_Cryptographic-Key": "Cryptographic key",
  "entity_Data-Component": "Data Component",
  "entity_Data-Source": "Data Source",
  "entity_Directory": "Directory",
  "entity_Domain-Name": "Domain name",
  "entity_Email-Addr": "Email address",
  "entity_Email-Message": "Email message",
  "entity_Email-Mime-Part-Type": "Email message - MIME Part",
  "entity_Entities": "Entities",
  "entity_Event": "Event",
  "entity_Events": "Events",
  "entity_External-Reference": "External reference",
  "entity_Feedback": "Feedback",
  "entity_Grouping": "Grouping",
  "entity_Hostname": "Hostname",
  "entity_IPv4-Addr": "IPv4 address",
  "entity_IPv6-Addr": "IPv6 address",
  "entity_Identity": "Identity",
  "entity_Incident": "Incident",
  "entity_Indicator": "Indicator",
  "entity_Individual": "Individual",
  "entity_Infrastructure": "Infrastructure",
  "entity_Intrusion-Set": "Intrusion Set",
  "entity_Ipv4-Addr": "IPv4 address",
  "entity_Ipv6-Addr": "IPv6 address",
  "entity_Label": "Label",
  "entity_Language": "Language",
  "entity_Location": "Location",
  "entity_Locations": "Locations",
  "entity_Mac-Addr": "MAC address",
  "entity_Malware": "Malware",
  "entity_Marking-Definition": "Marking definition",
  "entity_Media-Content": "Media content",
  "entity_Mutex": "Mutex",
  "entity_Narrative": "Narrative",
  "entity_Network-Traffic": "Network traffic",
  "entity_Note": "Note",
  "entity_Observable": "Observable",
  "entity_Observations": "Observations",
  "entity_Observed-Data": "Observed Data",
  "entity_Opinion": "Opinion",
  "entity_Organization": "Organization",
  "entity_Payment-Card": "Payment card",
  "entity_Phone-Number": "Phone number",
  "entity_Position": "Position",
  "entity_Process": "Process",
  "entity_Region": "Region",
  "entity_Relationship": "Relationship",
  "entity_Report": "Report",
  "entity_Sector": "Sector",
  "entity_Sighting": "Sighting",
  "entity_Software": "Software",
  "entity_Stix-Core-Objects": "Entities and observables",
  "entity_Stix-Core-Relationship": "Relationships",
  "entity_Stix-Cyber-Observable": "Observable",
  "entity_Stix-Cyber-Observables": "Observables",
  "entity_Stix-Domain-Object": "Entity",
  "entity_Stix-Domain-Objects": "Entities",
  "entity_StixFile": "File",
  "entity_Stixfile": "File",
  "entity_System": "System",
  "entity_Techniques": "Techniques",
  "entity_Text": "Text",
  "entity_Threat-Actor": "Threat Actor",
  "entity_Threats": "Threats",
  "entity_Tool": "Tool",
  "entity_Url": "URL",
  "entity_User-Account": "User account",
  "entity_User-Agent": "User agent",
  "entity_Vulnerability": "Vulnerability",
  "entity_Windows-Registry-Key": "Windows Registry Key",
  "entity_Windows-Registry-Value-Type": "Windows Registry Key Value",
  "entity_X509-Certificate": "X509 certificate",
  "filter_${filterKey}": "UNDEFINED",
  "filter_assigneeTo": "Assignee",
  "filter_basedOn": "Based on an observable",
  "filter_containedBy": "Container",
  "filter_createdBy": "Author",
  "filter_createdBy_not_eq": "NOT Author",
  "filter_elementId": "Related entity",
  "filter_fromId": "Source entity",
  "filter_fromTypes": "Source type",
  "filter_killChainPhase": "Kill Chain phase",
  "filter_labelledBy": "Label",
  "filter_labelledBy_not_eq": "NOT Label",
  "filter_markedBy": "Marking definition",
  "filter_markedBy_not_eq": "NOT Marking definition",
  "filter_objectContains": "Contains",
  "filter_sightedBy": "Sighted by/in",
  "filter_sightedBy_not_eq": "NOT Sighted by/in",
  "filter_toCreatedAt_end_date": "Ingested before",
  "filter_toCreatedAt_start_date": "Ingested after",
  "filter_toId": "Target entity",
  "filter_toSightingId": "Sighted in/at",
  "filter_toTypes": "Target type",
  "hour": "UNDEFINED",
  "malwares": "Malware",
  "month": "UNDEFINED",
  "obsContent": "Content",
  "of": "UNDEFINED",
  "on": "UNDEFINED",
  "organization": "Structured organization",
  "relationship_All": "All types of relationship",
  "reliability_A": "A - Completely reliable",
  "reliability_B": "B - Usually reliable",
  "reliability_C": "C - Fairly reliable",
  "reliability_D": "D - Not usually reliable",
  "reliability_E": "E - Unreliable",
  "reliability_F": "F - Reliability cannot be judged",
  "reports": "UNDEFINED",
  "selected": "UNDEFINED",
  "to exclude items": "UNDEFINED",
  "unknown": "unknown",
  "week": "UNDEFINED"
}