export default {
  "2FA": "2FA",
  "2FA state": "Estado de la autenticación en dos pasos",
  "AND": "UNDEFINED",
  "API access": "Acceso a la API",
  "API key": "Clave de API",
  "About": "Acerca de",
  "Abstract": "Resumen",
  "Accent color ": "Color de resalte",
  "Access stream directly in your browser": "UNDEFINED",
  "Accesses": "Accesos",
  "Action type": "Tipo de acción",
  "Active": "Activo",
  "Activities": "Actividad",
  "Activity": "Actividad",
  "Add": "Añadir",
  "Add Tick": "Añadir rotulador",
  "Add a widget": "Añadir un elemento gráfico",
  "Add an action": "Añadir una acción",
  "Add an entity to this container": "Añadir una entidad a este contenedor",
  "Add and complete": "Agregar y completar",
  "Add attack patterns": "Añadir patrones de ataque",
  "Add context": "Agregar contexto",
  "Add courses of action": "Añadir contramedidas",
  "Add data components": "Añadir componentes de datos",
  "Add data source": "Añadir fuente de datos",
  "Add entities": "Añadir entidades",
  "Add external references": "Añadir referencias externas",
  "Add locations": "Añadir una localización",
  "Add new labels": "Añadir nuevas etiquetas",
  "Add notes": "Añadir notas",
  "Add observable": "Añadir un observable",
  "Add observables": "Añadir observables",
  "Add sub attack patterns": "Añadir subpatrones de ataque",
  "Add subsectors": "Añadir subsectores",
  "Additional mandatory attributes": "Atributos obligatorios adicionales",
  "Admin": "Administrador",
  "Advanced search": "Búsqueda avanzada",
  "Affected software": "Aplicaciones afectadas",
  "Affecting this sector": "Afecta a este sector",
  "Alias": "Alias",
  "Aliases": "UNDEFINED",
  "Aliases separated by commas": "Aliases separados por comas",
  "All": "Todas",
  "All confidence levels": "Todos los niveles de confianza",
  "All entities": "Todas las entidades",
  "All observables": "Todos los observables",
  "All reports": "Todos los informes",
  "All threats": "Todas las amenazas",
  "All types of entity": "Todo los tipos de entidad",
  "All types of relationship": "Todos los tipos de relación",
  "All years": "Todos los años",
  "Allowed markings": "Marcas permitidas",
  "Already in plat.": "Ya está en la plataforma.",
  "Also delete these elements": "También elimine estos elementos",
  "An unknown error has occurred!  Please try again later.": "Ha ocurrido un error desconocido. Inténtalo de nuevo más tarde.",
  "Analysis": "Análisis",
  "Analyst workbenches": "Espacios de trabajo del analista",
  "Apply on": "Aplicar sobre",
  "Applying this rule on the existing data": "Aplicando esta regla a los datos existentes",
  "Architecture execution env.": "Arquitectura de ejecución",
  "Area": "Zona",
  "Areas": "Zonas",
  "Arsenal": "Arsenal",
  "Artifacts": "Artefactos",
  "As it happens": "Tal y como ocurre",
  "Assignee(s)": "Referente",
  "Assignees": "Referencias",
  "Associated file": "Fichero asociado",
  "Attack pattern": "Patrón de ataque",
  "Attack pattern usage": "Uso del patrón de ataque",
  "Attack patterns": "Patrones de ataque",
  "Attributed to this actor": "Atribuido a este actor",
  "Attributed to this campaign": "Atribuido a esta campaña",
  "Attributed to this country": "Atribuido a este país",
  "Attributed to this individual": "Atribuido a este individuo",
  "Attributed to this intrusion set": "Atribuido a este set de intrusión",
  "Attributed to this organization": "Atribuido a esta organización",
  "Attributed to this region": "Atribuido a esta región",
  "Attribution": "Atribución",
  "Authentication": "Autenticación",
  "Authentication strategies": "Estrategias de autenticación",
  "Author": "Autor",
  "Auto new markings": "Autorización de nuevos marcados",
  "Automatic": "Automático",
  "Automatic references at file upload": "Referencias automáticas al cargar el archivo",
  "Automatic trigger": "Activación automática",
  "Automatically authorize this group to new marking definition": "Autorizar automáticamente a este grupo a nuevas categorías de clasificación",
  "Autonomous system": "Sistema autónomo (AS)",
  "Autonomous systems": "Sistemas autónomos (AS)",
  "Averages of context relations": "Promedio de relaciones de contexto",
  "Avoid dependencies resolution": "Evitar resolución de dependencias",
  "Back": "Volver",
  "Background color": "Color de fondo",
  "Background tasks": "Tareas en segundo plano",
  "Bad login or password": "Nombre de usuario o contraseña incorrectos",
  "Base URL": "URL de base",
  "Based on": "Basado en",
  "Basic information": "Información básica",
  "Belonging to this organization": "Perteneciente a esta organización",
  "Browse the link": "Visitar el enlace",
  "Bulk search": "Búsqueda masiva",
  "Bundle content": "Empaquetar contenido",
  "Bundle details": "Detalles del paquete",
  "Bundles processed": "Paquetes procesados",
  "CRITICAL": "UNDEFINED",
  "CSIRT": "CSIRT",
  "CSV file": "Fichero CSV",
  "Campaign": "Campaña",
  "Campaigns": "Campañas",
  "Cancel": "Cancelar",
  "Capabilities": "Capacidades",
  "Cards view": "Vista por tarjetas",
  "Cascade delete": "Eliminación en cascada",
  "Case priority": "Prioridad",
  "Case severity": "Gravedad",
  "Category": "Catégorie",
  "Channel": "Canal",
  "Channel type": "Tipo de canal",
  "Channel types": "Tipos de canal",
  "Channels": "Canales",
  "Cities": "Ciudades",
  "City": "Ciudad",
  "Cleaning up this rule on the existing data": "Deshaciendo los cambios de esta regla sobre los datos existentes",
  "Clear": "Borrar",
  "Clear all works": "Eliminar todas las tareas",
  "Clear filters": "Limpiar los filtros",
  "Clear this connector": "Eliminar este conector",
  "Close": "Cerrar",
  "Cloud Control Plane": "Plano de control de nube",
  "Collapse": "Colapso",
  "Color": "Color",
  "Column": "Columna",
  "Columns": "Columnas",
  "Commit message": "Mensaje de confirmación",
  "Commit message when updating data from the UI.": "Mensaje al modificar datos en la interfaz.",
  "Commit messages": "Mensajes de confirmación",
  "Compare": "Comparar",
  "Completed tasks": "Tareas completadas",
  "Completed works": "Ejecuciones completadas",
  "Confidence": "Confianza",
  "Confidence level": "Nivel de confianza",
  "Configuration": "Configuración",
  "Confirmation": "Confirmación",
  "Confirmation required": "Confirmación requerida",
  "Connected": "Conectado",
  "Connected workers": "Trabajadores conectados",
  "Connection successfully verified": "Conexión verificada con éxito",
  "Connector": "Conector",
  "Connectors": "Conectores",
  "Connectors & workers": "Conectores y «workers»",
  "Constituent": "Constitutivo",
  "Contact information": "Información de contacto",
  "Containers": "Contenedores",
  "Containers (reports, groupings, notes & opinions)": "Contenedores (informes, agrupaciones, notas y opiniones)",
  "Content": "Contenido",
  "Context relations": "Relaciones de contexto",
  "Continue": "Continuar",
  "Copied to clipboard": "Copiado al portapapeles",
  "Copy": "Copiar",
  "Copy disabled: too many selected elements (maximum number of elements for a copy: ": "Copia deshabilitada: demasiados elementos seleccionados (número máximo de elementos para una copia: ",
  "Copy/paste text content": "Copiar o pegar contenido textual",
  "Correlate": "Correlar",
  "Correlation view": "Vista de las correlaciones",
  "Count": "Cuenta",
  "Countries": "Países",
  "Country": "País",
  "Course of action": "Contramedida",
  "Courses of action": "Contramedidas",
  "Courses of action view": "Vista de las contramedidas",
  "Create": "Crear",
  "Create a TAXII collection": "Crear una colección TAXII",
  "Create a campaign": "Crear una campaña",
  "Create a case incident": "Crear un incidente de caso",
  "Create a channel": "Crear un canal",
  "Create a city": "Crear una ciudad",
  "Create a country": "Crear un país",
  "Create a course of action": "Crear una contramedida",
  "Create a data component": "Crear un componente de datos",
  "Create a data source": "Crear una fuente de datos",
  "Create a feed": "Crear una fuente de datos",
  "Create a feedback": "Crear un comentario",
  "Create a file": "Crear un fichero",
  "Create a group": "Crear un grupo",
  "Create a grouping": "Crear una agrupación",
  "Create a individual": "Crear un individuo",
  "Create a kill chain phase": "Crear una fase de la «kill-chain»",
  "Create a label": "Crear una etiqueta",
  "Create a live stream": "Crear una emisión en vivo",
  "Create a live trigger": "UNDEFINED",
  "Create a malware": "Crear código malicioso",
  "Create a marking definition": "Crear una categoría de clasificación",
  "Create a narrative": "Crear una narrativa",
  "Create a nested relationship": "Crear una relación anidada",
  "Create a note": "Crear una nota",
  "Create a opinions": "UNDEFINED",
  "Create a position": "Crear un puesto",
  "Create a region": "Crear una région",
  "Create a regular digest": "UNDEFINED",
  "Create a relationship": "Crear una relación",
  "Create a report": "Crear un informe",
  "Create a retention policy": "Crear una política de retención",
  "Create a role": "Crear un rol",
  "Create a sector": "Crear un sector",
  "Create a sighting": "Crear una detección",
  "Create a status": "Crear un estado",
  "Create a status template": "Crear una plantilla de estado",
  "Create a subscription": "Crear una suscripción",
  "Create a synchronizer": "Crear un sincronizador",
  "Create a system": "Crear un sistema",
  "Create a threat actor": "Crear un actor de amenazas",
  "Create a tool": "Crear una herramienta",
  "Create a user": "Crear un usuario",
  "Create a vocabulary": "UNDEFINED",
  "Create a vulnerability": "Crear una vulnerabilidad",
  "Create a workbench": "Crear un espacio de trabajo",
  "Create a workspace": "Crear un espacio de trabajo",
  "Create an area": "Crear una zona",
  "Create an artifact": "Crear un artefacto",
  "Create an attack pattern": "Crear un patrón de ataque",
  "Create an attribute": "Crear un atributo",
  "Create an entity": "Crear una entidad",
  "Create an event": "Crear un evento",
  "Create an external reference": "Crear una referencia externa",
  "Create an incident": "Crear un incidente",
  "Create an indicator": "Crear un indicador",
  "Create an indicator from this observable": "Crear un indicador a partir de este observable",
  "Create an infrastructure": "Crear una infrastructura",
  "Create an intrusion set": "Crear un set de intrusión",
  "Create an observable": "Crear un observable",
  "Create an observed data": "Crear un conjunto de datos observados",
  "Create an opinion": "Crear una opinión",
  "Create an organization": "Crear una organización",
  "Create external reference at upload": "Crear referencia externa al cargar",
  "Created entities": "Entidades creadas",
  "Created the": "Creado el",
  "Creation": "UNDEFINED",
  "Creation date": "Fecha de creación",
  "Creation date (in this platform)": "Fecha de creación (en esta plataforma)",
  "Creator": "Creador",
  "Creators": "Creadors",
  "Current password": "Contraseña actual",
  "Current state": "Estado actual",
  "Custom dashboard": "Cuadro de mando personalizado",
  "Custom dashboards": "Cuadros de mando personalizados",
  "Dark": "Oscuro",
  "Dark (with background)": "Oscuro (con fondo)",
  "Dark (without background)": "Oscuro (sin fondo)",
  "Dark theme": "Tema oscuro",
  "Dashboard": "Cuadro de mando",
  "Dashboard settings": "Cuadro de mando de configuración",
  "Data": "Datos",
  "Data component": "Componente de datos",
  "Data components": "Componentes de datos",
  "Data curation": "Curación de datos",
  "Data import": "Importación de datos",
  "Data import and analyst workbenches": "UNDEFINED",
  "Data sharing": "Compartición de datos",
  "Data source": "Fuente de datos",
  "Data sources": "Fuentes de datos",
  "Data type": "Tipo de datos",
  "Date": "Fecha",
  "Date reference": "Referencia de la fecha",
  "Default": "Por defecto",
  "Default hidden entity types": "UNDEFINED",
  "Default mandatory attributes": "Atributos obligatorios predeterminados",
  "Default membership": "Pertenencia predeterminada",
  "Default value": "Valor por defecto",
  "Definition": "Definición",
  "Delete": "Suprimir",
  "Delete the element if no other containers contain it": "Eliminar el elemento si ningún otro contenedor lo contiene",
  "Delete this file": "Borrar  este fichero",
  "Delete this workbench": "Eliminar este espacio de trabajo",
  "Deletion": "UNDEFINED",
  "Demo credentials": "Credenciales de prueba",
  "Dependencies": "Dependencias",
  "Description": "Descripción",
  "Details": "Detalles",
  "Digest with multiple notifications": "UNDEFINED",
  "Direct Update": "UNDEFINED",
  "Direct relations creations": "Creación de relaciones directas",
  "Direct targeting of this country": "Este paíss como objetivo directo",
  "Direct targeting of this region": "Esta región como objetivo directo",
  "Direct targeting of this sector": "Este sector como objetivo directo",
  "Directories": "Directorios",
  "Directory": "Carpeta",
  "Disable": "Desactivar",
  "Disable 3D mode": "Desactivar el modo 3D",
  "Disable forces": "Desactivar las fuerzas",
  "Disable tree horizontal mode": "Desactivar el modo árbol horizontal",
  "Disable tree vertical mode": "Desactivar el modo árbol vertical",
  "Disable two-factor authentication": "Desactivar la autenticación en dos pasos",
  "Disabled": "Desactovado",
  "Disconnected": "Desconectado",
  "Display as": "Mostrar como",
  "Display global knowledge with filters and criteria.": "Muestra conocimiento global con filtros y criterios.",
  "Display notes": "Mostrar las notas",
  "Display specific knowledge using relationships and filters.": "Muestre conocimientos específicos utilizando relaciones y filtros.",
  "Display time range selector": "Mostrar el selector de rango temporal",
  "Distribution": "Distribución",
  "Distribution of entities": "Distribución de entidades",
  "Distribution of opinions": "Distribución de opiniones",
  "Distribution of relations": "Distribución de relaciones",
  "Distribution of relations (including inferred)": "Distribución de reñacopmes (incluyendo inferencias)",
  "Distribution of sources": "Distribución de fuentes",
  "Distribution:": "Distribución:",
  "Do you want to browse this external link?": "¿Quieres visitar este enlace externo?",
  "Do you want to clear the works of this connector?": "¿Quieres eliminar todas las tareas de este conector?",
  "Do you want to create a STIX Indicator from this observable?": "¿Quieres crear un indicador STIX a partir de este observable?",
  "Do you want to delete these entities?": "¿Quieres borrar estas entidades?",
  "Do you want to delete this area?": "¿Quieres borrar esta zona?",
  "Do you want to delete this attack pattern?": "¿Quieres borrar este patrón de ataque?",
  "Do you want to delete this attribute?": "¿Quieres borrar este atributo?",
  "Do you want to delete this campaign?": "¿Quieres borrar esta campaña?",
  "Do you want to delete this case incident ?": "¿Desea eliminar este incidente de caso?",
  "Do you want to delete this city?": "¿Quieres borrar esta ciudad?",
  "Do you want to delete this country?": "¿Quieres borrar este país?",
  "Do you want to delete this course of action?": "¿Quieres borrar esta contramedida?",
  "Do you want to delete this data component?": "¿Quieres borrar este componente de datos?",
  "Do you want to delete this data source?": "¿Quieres eliminar esta fuente de datos?",
  "Do you want to delete this entity?": "¿Quieres borrar esta entidad?",
  "Do you want to delete this external reference?": "¿Quieres borrar esta referencia externa?",
  "Do you want to delete this feed?": "¿Quieres borrar esta fuente de información?",
  "Do you want to delete this feedback ?": "¿Quieres eliminar este comentario?",
  "Do you want to delete this file?": "¿Quieres borrar este fichero?",
  "Do you want to delete this group?": "¿Quieres borrar este grupo?",
  "Do you want to delete this grouping?": "¿Quieres eliminar esta agrupación?",
  "Do you want to delete this incident?": "¿Quieres borrar este incidente?",
  "Do you want to delete this indicator?": "¿Quieres borrar este indicador?",
  "Do you want to delete this individual?": "¿Quieres borrar a este individuo?",
  "Do you want to delete this intrusion set?": "¿Quieres borrar este set de intrusión?",
  "Do you want to delete this kill chain phase?": "¿Quieres borrar esta fase de la «kill chain»?",
  "Do you want to delete this label?": "¿Quieres borrar esta etiqueta?",
  "Do you want to delete this live stream?": "¿Quieres borrar esta transmisión en vivo?",
  "Do you want to delete this malware?": "¿Quieres borrar este malware?",
  "Do you want to delete this marking definition?": "¿Quieres borrar esta categoría de clasificación?",
  "Do you want to delete this note?": "¿Quieres borrar esta nota?",
  "Do you want to delete this observable?": "¿Quieres borrar este observable?",
  "Do you want to delete this observed data?": "¿Quieres borrar este conjunto de datos observados?",
  "Do you want to delete this organization?": "¿Quieres borrar esta organización?",
  "Do you want to delete this region?": "¿Quieres borrar esta región?",
  "Do you want to delete this relation?": "¿Quieres borrar esta relación?",
  "Do you want to delete this report?": "¿Quieres borrar este informe?",
  "Do you want to delete this role?": "¿Quieres borrar este rol?",
  "Do you want to delete this sector?": "¿Quieres borrar este sector?",
  "Do you want to delete this sighting?": "¿Quieres borrar esta observación?",
  "Do you want to delete this status template?": "¿Desea eliminar esta plantilla de estado?",
  "Do you want to delete this synchronizer?": "¿Quieres borrar este sincronizador?",
  "Do you want to delete this system?": "¿Quieres borrar este sistema?",
  "Do you want to delete this threat actor?": "¿Quieres borrar este actor de amenazas?",
  "Do you want to delete this tool?": "¿Quieres borrar esta herramienta?",
  "Do you want to delete this user?": "¿Quieres borrar este usuario?",
  "Do you want to delete this vulnerability?": "¿Quieres borrar esta vulnerabilidad?",
  "Do you want to delete this widget?": "¿Quieres borrar este elemento gráfico?",
  "Do you want to delete this workbench?": "¿Quieres eliminar este espacio de trabajo?",
  "Do you want to delete this workspace?": "¿Quieres borrar este área de trabajo?",
  "Do you want to disable this rule?": "¿Quieres desactivar esta regla?",
  "Do you want to enable this rule?": "¿Quieres activar esta regla?",
  "Do you want to kill all the sessions of this user?": "¿Quieres cerrar todas las sesiones de este usuario?",
  "Do you want to kill this session?": "¿Quieres cerrar esta sesión?",
  "Do you want to remove the entity from this container?": "¿Quieres borrar esta entidad de este contenedor?",
  "Do you want to remove the entity from this grouping?": "¿Desea eliminar la entidad de esta agrupación?",
  "Do you want to remove the entity from this report?": "¿Quieres borrar esta entidad de este informe?",
  "Do you want to remove the indicator from this observable?": "¿Quieres borrar este indicador de este observable?",
  "Do you want to remove the observable from this indicator?": "¿Quieres borrar este observable de este indicador?",
  "Do you want to remove these elements from this grouping?": "¿Quieres borrar estos elementos de esta agrupación?",
  "Do you want to remove these elements from this investigation?": "¿Quieres borrar estos elementos de esta investigación?",
  "Do you want to remove these elements from this report?": "¿Quieres borrar estos elementos de este informe?",
  "Do you want to remove this entity?": "¿Quieres eliminar este objeto?",
  "Do you want to remove this external reference?": "¿Quieres borrar esta referencia externa?",
  "Do you want to remove this grouping?": "¿Quieres borrar esta agrupación?",
  "Do you want to remove this job?": "¿Quieres borrar esta tarea?",
  "Do you want to remove this note?": "¿Quieres borrar esta nota?",
  "Do you want to remove this opinion?": "¿Quieres borrar esta opinión?",
  "Do you want to remove this report?": "¿Quieres borrar este informe?",
  "Do you want to remove this status?": "¿Quieres eliminar este estado?",
  "Do you want to reset the state of this connector?": "¿Quieres reiniciar el estado de este conector?",
  "Do you want to start this synchronizer?": "¿Quieres iniciar este sincronizador?",
  "Do you want to stop this synchronizer?": "¿Quieres parar este sincronizador?",
  "Domain": "Nombre de dominio",
  "Domain names": "Nombres de dominio",
  "Donut": "Donut",
  "Donut chart": "Gráfico de donut",
  "Download": "Descargar",
  "Download this file": "Descargar este fichero",
  "EXPIRATION_SCHEDULER": "Planificador de expiración",
  "EXTERNAL_IMPORT": "Importación de datos",
  "Each tick value must be between min and max value": "Cada valor de tick debe estar entre el valor mínimo y máximo",
  "Edit the selected item": "Quitar el elemento seleccionado",
  "Elasticsearch": "Elasticsearch",
  "Element will be rescan with all compatible activated rules": "El elemento será reescaneado con todas las reglas compatibles activadas",
  "Elements successfully copied": "Elementos copiados correctamente",
  "Email": "Correo electrónico",
  "Email address": "Dirección de correo electrónico",
  "Email addresses": "Direcciones de correo electrónico",
  "Email subject": "Asunto del correo electŕonico",
  "Emails": "Correos electrónicos",
  "Enable": "Activar",
  "Enable 3D mode": "Activar el modo 3D",
  "Enable commit messages": "Habilitar los mensajes de confirmación",
  "Enable forces": "Activar las fuerzas",
  "Enable this feature": "UNDEFINED",
  "Enable tree mode": "Activar el modo árbol",
  "Enable two-factor authentication": "Activar la autenticación en dos pasos",
  "Enabled": "Activado",
  "Enabled import connectors": "Conectores de importación activados",
  "Enabled the ": "Activar ",
  "End date": "Fecha de fin",
  "Enforce reference": "Hacer cumplir la referencia",
  "Enforce references": "UNDEFINED",
  "Enforce two-factor authentication": "Hacer cumplir la autenticación de dos factores",
  "Enrich": "Enriquecer",
  "Enrichment": "Enriquecimiento",
  "Enrichment connectors": "Conectores de enriquecimiento ",
  "Entities": "Entidades",
  "Entities distribution": "Distribución de entidades",
  "Entities view": "Vista de entidades",
  "Entity": "Entidad",
  "Entity aliases": "Aliases de la entidad",
  "Entity details": "Detalles de la entidad",
  "Entity enrichment": "Enriquecimiento de la entidad",
  "Entity settings": "Configuración de la entidad",
  "Entity type": "Tipo de entidad",
  "Entity types": "Tipo de entidad",
  "Entity usage": "Uso dela entidad",
  "Error": "Error",
  "Event types": "Tipos de evento",
  "Events": "Eventos",
  "Every 1 hour": "Cada hora",
  "Every 24 hours": "Cada 24 horas",
  "Every month": "Cada mes",
  "Every week": "Cada semana",
  "Everything": "Todos los elementos",
  "Evidences": "Evidencias",
  "Evolution": "Evolución",
  "Example": "Ejemplo",
  "Expand": "Expandir",
  "Expand elements": "Expandir elementos",
  "Explanation": "Explicación",
  "Explore": "Explorar",
  "Explore the attack campaigns of the dataset through time and involved entities.": "Explorer las campañas de la base de datos en el espacio y en el tiempo.",
  "Explore the kill chains of entities through time and other contextual information like campaigns or incidents.": "Explorar las «kill chains» de las entidades en el tiempo y otra información contexual como campañas e incidentes.",
  "Explore the observables of the dataset though time to visualize clusters and correlations.": "Explorar los observables de la base de datos a lo largo del tiempo para visualizar «clusters» y correlaciones.",
  "Explore the techniques, tactics and procedures of the dataset through time and entities who used its.": "Explorer las TTP en el tiempo y las entidades que las usaron.",
  "Explore the victims and the targets of the dataset through space and time.": "Explorar víctimas y objetivos de la base de datos en el espacio y en el tiempo.",
  "Explore the vulnerabilities used by entities through time and kill chain phases.": "Explorar las vulnerabilidades utilizadas por las entidades a lo largo del tiempo y las fases de la «kill chain».",
  "Export": "Exportar",
  "Export as PDF": "Exportar como PDF",
  "Export as image": "Exportar como imagen",
  "Export data in CSV": "Exportar los datos en CSV",
  "Export format": "Formato de exportación",
  "Export is disabled because too many entities are targeted (maximum number of entities is: ": "La exportación está deshabilitada porque hay demasiadas entidades de destino (el número máximo de entidades es: ",
  "Export successfully started": "Exportación iniciada con éxito",
  "Export the entity": "Exportar la entidad",
  "Export to CSV": "Exportar a CSV",
  "Export to PDF": "Exportar a PDF",
  "Export to document (pdf)": "Exportar a documento (pdf)",
  "Export to image": "Exportar a image",
  "Export to image (png)": "Exportar a imagen (png)",
  "Export type": "Tipo de exportación",
  "Exported files": "Ficheros exportados",
  "Exports list": "Lista de exportaciones",
  "Exports panel": "Panel de exportación",
  "External ID": "ID externo",
  "External authentication": "Autenticación externa",
  "External references": "Referencias externas",
  "External references files": "Ficheros de referencias externas",
  "False positive": "Falso positivo",
  "Feedback": "UNDEFINED",
  "Feeds (CSV)": "«Feeds» (CSV)",
  "Field": "Atributo",
  "Field type": "Tipo de atributo",
  "File MD5 hash": "Hash MD5 del fichero",
  "File SHA1 hash": "Hash SHA1 del fichero",
  "File SHA256 hash": "Hash SHA256 del fichero",
  "File and associated external reference successfully removed": "Archivo y referencia externa asociada eliminados correctamente",
  "File hash": "Hash del fichero",
  "File hashes": "Hashes de ficheros",
  "File information": "Información del fichero",
  "File name": "Nombre del fichero",
  "File path": "Ruta del fichero",
  "File successfully removed": "Fichero borrado con éxito",
  "File successfully uploaded": "Fichero subido con éxito",
  "File successfully uploaded and associated external reference successfully created": "Archivo cargado correctamente y referencia externa asociada creada correctamente",
  "File to import": "Fichero a importer",
  "Files": "Ficheros",
  "Files & history": "Ficheros y actividad",
  "Filter authors (created by)": "Filtrar por autores (creado por)",
  "Filter by": "Filtrar por",
  "Filter entity types": "Filtrar por tipos de entidad",
  "Filter marking definitions": "Filtrar por clasificación",
  "Filters": "Filtros",
  "First obs.": "Primera obs.",
  "First observed": "Primera observación",
  "First seen": "Primera observación",
  "Firstname": "Nombre",
  "Fit graph to canvas": "Ajustar el grafo al espacio disponible",
  "Force now": "Forzar ahora",
  "Free text import": "Importar desde texto libre",
  "Friday": "UNDEFINED",
  "From name": "Nombre origen",
  "From type": "Tipo origen",
  "Full export (entity and first neighbours)": "Exportación completa (entidad y primeros vecinos)",
  "Functional date": "Fecha funcional",
  "GRAPHQL_API": "API de GraphQL",
  "General": "General",
  "Generate": "Generar",
  "Generate an export": "Generar una exportación",
  "Generated the": "Generado el",
  "Generation in progress...": "Generación en curso...",
  "Global": "Global",
  "Global keyword": "Palabra clave global",
  "Global kill chain": "«ill chain» global",
  "Global parameters": "Parámetros globales",
  "Global streams are available for granted users. Live at /stream/live and raw at /stream": "Las publicaciones en vivo están permitidas para usuarios autorizados. En tiempo real en /stream/live y en bruto en /stream",
  "Goals": "Objetivos",
  "Goals (1 / line)": "Objetivos (1 por línea)",
  "Good": "Buena",
  "Granted by default": "Asignado por defecto",
  "Granted by default at user creation": "Asignado por defecto en la creación del usuario",
  "Graph": "Grafo",
  "Graph type": "Tipo de gráfico",
  "Graph view": "Vista en grafo",
  "Grouping": "Agrupación",
  "Groupings": "Agrupaciones",
  "Groups": "Grupos",
  "Groups permissions on data marking is not fully implemented yet.": "Los permisos de grupo en el marcado de datos no están completamente implementados todavía.",
  "Groups with this role": "Grupos con este rol",
  "HISTORY_MANAGER": "Gestor del historial",
  "HTML files": "Ficheros  HTML",
  "Heatmap": "Mapa de calor",
  "Hidden entity types": "Tipos de entidad ocultos",
  "Hidden in interface": "Oculto en la interfaz",
  "Hidden in roles": "Oculto en roles",
  "Hide in the platform": "UNDEFINED",
  "High": "Alto",
  "History": "Historial",
  "Horizontal Bar": "Barra horizontal",
  "Host": "Anfitrión",
  "INTERNAL_ENRICHMENT": "Enriquecimiento",
  "INTERNAL_EXPORT_FILE": "Exportación de ficheros",
  "INTERNAL_IMPORT_FILE": "Importación de ficheros",
  "IPv4 address": "Dirección IPv4",
  "IPv4 addresses": "Direcciones IPv4",
  "IPv6 address": "Dirección IPv6",
  "IPv6 addresses": "Direcciones IPv6",
  "Identities": "Identidades",
  "Identity": "Identidad",
  "Impacted": "Impactado",
  "Implant": "Implante",
  "Implementation languages": "Lenguajes de implementación",
  "Import": "Importar",
  "Import data": "Importar datos",
  "Import successfully asked": "Importación solicitada exitosamente",
  "Import type": "Tipo de importación",
  "In OpenCTI, a predictable STIX ID is generated based on one or multiple attributes of the entity.": "En OpenCTI, se genera un STIX ID predictivo basado en uno o más atributos de esta entidad.",
  "In all the database": "En toda la base de datos",
  "In progress messages": "Mensajes en curso",
  "In progress tasks": "Tareas en curso",
  "In progress works": "Ejecuciones en curso",
  "In this report, ": "En este informe, ",
  "Incident": "Incidente",
  "Incident Date": "Fecha del incidente",
  "Incident type": "Tipo de incidente",
  "Incidents": "Incidentes",
  "Include headers in the feed": "Incluir cabeceras en la fuente de información",
  "Indicator": "Indicador",
  "Indicator pattern": "Patrón del indicador",
  "Indicator type": "Tipo de indicador",
  "Indicator types": "Tipos de indicador",
  "Indicators": "Indicadores",
  "Indicators composed with this observable": "Indicadores compuestos con este observable",
  "Indicators/observables generation": "Generación de indicadore y /observables",
  "Individual": "Individuo",
  "Individuals": "Individuos",
  "Inference explanation": "Explicación de la inferencia",
  "Inference rules": "Reglas de inferencia",
  "Inferences": "Inferencias",
  "Inferred knowledge based on the rule ": "Conocimiento inferido basado en la regla",
  "Information": "Información",
  "Infrastructure types": "Tipos de infraestructura",
  "Infrastructures": "Infraestructuras",
  "Ingested entities": "Entidades ingestadas",
  "Initiator": "Iniciador",
  "Intrusion set": "Set de intrusión",
  "Intrusion sets": "Sets de intrusión",
  "Investigate": "Investigar",
  "Investigations": "Investigaciones",
  "Is family": "Es una familia",
  "Is family?": "¿Es una familia?",
  "JSON content": "Contenido JSON",
  "Just in the report": "Solo en el informe",
  "Key": "Clave",
  "Kill chain": "«Kill chain»",
  "Kill chain name": "Nombre de la «kill chain»",
  "Kill chain phase": "Fase de la «kill chain»",
  "Kill chain phases": "Fases de la «kill chain»",
  "Kill chain view": "Vista de la «kill chain»",
  "Kill chains": "«Kill chains»",
  "Knowledge": "Conocimiento",
  "Knowledge entity": "Entidad de conocimiento",
  "Knowledge graph": "Grafo de conocimiento",
  "Knowledge update (except indicators & observables)": "Actualización de base de conocimiento (excepto indicadores y observables)",
  "Label": "Etiqueta",
  "Labels": "Etiquetas",
  "Labels & Attributes": "Etiquetas y atributos",
  "Language": "Idioma",
  "Last": "UNDEFINED",
  "Last 24 hours": "Últiimas 24 horas",
  "Last 6 months": "Últimos 6 meses",
  "Last 7 days": "Últimos 7 días",
  "Last execution": "Última ejecución",
  "Last ingested reports (creation date in the platform)": "Últimos informes añadidos (fecha de creación en la plataforma)",
  "Last modified": "Última modificación",
  "Last modified entities": "Últimas entidades modificadas",
  "Last month": "Último mes",
  "Last notes": "Últimas notas",
  "Last obs.": "Última obs.",
  "Last observables": "Últimos observables",
  "Last observed": "Dernière observation",
  "Last processed message": "Último mensaje procesado",
  "Last reports": "Últimos informes",
  "Last reports about the entity": "Últimos informes sobre esta entidad",
  "Last run": "Última ejecución",
  "Last run:": "Última ejecución:",
  "Last seen": "Última observación",
  "Last targeted organizations in this sector": "Últimas organizaciones atacadas en este sector",
  "Last update": "Última actualización",
  "Last year": "Último año",
  "Lastname": "Apellido",
  "Latest created relationships": "Últimas relaciones creadas",
  "Latest reports about this entity": "Últimos informes sobre esta entidad",
  "Latest reports written by this entity": "Últimos informes escritos por esta entidad",
  "Latitude": "UNDEFINED",
  "Launch": "Lanzar",
  "Launch a background task": "Lanzar una tarea en segundo plano",
  "Launch an import": "Lanzar una importación",
  "Launch an import of this file": "Lanzar importación de este fichero",
  "Launch rescan": "Lanzar reescaneo",
  "Layers": "Capas",
  "Let the field empty to grant all users": "Dejar el campo vacío para conceder a todos los usuarios",
  "Level": "Nivel",
  "Light": "Claro",
  "Light (with background)": "Claro (con fondo)",
  "Light (without background)": "Claro (sin fondo)",
  "Light theme": "Tema claro",
  "Likelihood": "Probabilidad",
  "Limit": "Límite",
  "Limits": "UNDEFINED",
  "Line chart": "Gráfico de líneas",
  "Lines view": "Vista por líneas",
  "Linked entities": "Entidades relacionadas",
  "Linked entity": "Entidad relacionada",
  "Linked knowledge": "Conocimiento relacionado",
  "Linked threat": "Amenaza relacionada",
  "Linked threat(s)": "Amenaza(s) relacionada(s)",
  "Links with threats": "Enlaces con las amenazas",
  "List": "Lista",
  "List of entities": "Lista de entidades",
  "Live streams": "Publicación en vivo",
  "Live trigger": "UNDEFINED",
  "Localized in this country": "Localizado en este país",
  "Localized in this region": "Localizado en esta región",
  "Location": "Localización",
  "Locations": "Localizaciones",
  "Locations of this individual": "Localizaciones de este individuo",
  "Locations of this organization": "Localizaciones de esta organización",
  "Log sources": "Origen de los registros",
  "Log sources (1 / line)": "Origen de los registros (1 por línea)",
  "Login": "Usuario",
  "Logo URL": "Dirección URL del logo",
  "Logo URL for login page": "Dirección URL del logo en la página de inicio de sesión",
  "Logout": "Cerrar sesión",
  "Longitude": "UNDEFINED",
  "Low": "Débil",
  "MAC address": "Dirección MAC",
  "MAC addresses": "Direcciones MAC",
  "MEDIUM": "UNDEFINED",
  "Main observable type": "Tipo de observable principal",
  "Make this stream public and available to anyone": "Haz que esta transmisión sea pública y esté disponible para todos.",
  "Malicious": "Malicioso",
  "Malware": "Malware",
  "Malware types": "Tipos de malware",
  "Malwares": "Malware",
  "Manage a container": "Administrar un contenedor",
  "Manage an entity": "Administrar una entidad",
  "Manage an observable": "Administrar un observable",
  "Mandatory attributes": "Atributos obligatorios",
  "Manual": "Manual",
  "Map": "Mapa",
  "Markdown files": "Ficheros  Markdown",
  "Markdown source": "Origen Markdown",
  "Marking": "Clasificación",
  "Marking definitions": "Categorías de clasificación",
  "Markings": "Marcas",
  "Matrix view": "Vista en matriz",
  "Max marking definition level": "Máximo nivel de categoría de clasificación",
  "Max retention": "Retención máxima",
  "Maximum": "UNDEFINED",
  "Maximum retention days": "Días de retención máxima",
  "Med": "Mediano",
  "Members": "Miembros",
  "Merge": "Fusionar",
  "Merge entities": "Fusionar entidades",
  "Merged entity": "Entidad fusionada",
  "Message": "UNDEFINED",
  "Metrics": "Métricas",
  "MinIO": "MinIO",
  "Mini map": "Mini mapa",
  "Minimum": "UNDEFINED",
  "Minimum one outcome": "UNDEFINED",
  "Minimum one trigger": "UNDEFINED",
  "Mitigated attack patterns": "Patrones de ataque mitigados",
  "Moderate": "Moderada",
  "Modification": "UNDEFINED",
  "Modification date": "Fecha de modificación",
  "Modified": "Modificado",
  "Monday": "UNDEFINED",
  "Month": "Mes",
  "Month day": "UNDEFINED",
  "More": "Más",
  "Most recent history": "Historial más reciente",
  "Multiple": "UNDEFINED",
  "Multiple entities selected": "Múltiples entidades seleccionadas",
  "Mutex": "Mutex",
  "NOTIFICATION_MANAGER": "Gestor de generación de notificaciones",
  "Name": "Nombre",
  "Narrative": "Narrativa",
  "Narratives": "Narrativas",
  "Navigation color": "Color de navegación",
  "Nested objects": "Objetos anidados",
  "Network": "Red",
  "Never enabled": "Nunca activado",
  "Never generated": "Nunca generado",
  "New alias": "Nuevo alias",
  "New password": "Nueva contraseña",
  "No": "No",
  "No available options": "Opciones no disponibles",
  "No available public stream on this platform": "UNDEFINED",
  "No connector available for the selected entities.": "Ningún conector disponible para las entidades seleccionadas.",
  "No connectors are enabled on this platform.": "Ningún conector se ha habilitado en esta plataforma.",
  "No connectors for this type of entity": "Ningún conector para este tipo de entidad",
  "No description": "UNDEFINED",
  "No description of this targeting": "No hay descripción de este objetivo",
  "No description of this usage": "No hay descripción de este uso",
  "No enrichment connectors on this platform": "Ningún conector de enriquecimiento en esta plataforma",
  "No entities of this type has been found.": "No se ha encontrado ninguna entidad de este tipo.",
  "No entities were found for this search.": "Ninguna entidad fue encontrada en esta búsqueda.",
  "No export connector available to generate an export": "Ningún conector de exportación disponible para generar la exportación",
  "No file for the moment": "Ningún fichero por el momento",
  "No file selected.": "Ningún fichero seleccionado",
  "No files in this category.": "Sin archivos en esta categoría.",
  "No history about this entity.": "No hay historial sobre esta entidad.",
  "No history about this relationship.": "No hay historial sobre esta relación",
  "No import connectors on this platform": "Ningún conector de importación en esta plataforma",
  "No label": "Sin etiquetas",
  "No notes about this entity yet.": "No se ha encontrado ninguna nota sobre esta entidad todavía",
  "No potential duplicate entities has been found.": "No se han encontrado entidades potencialmente duplicadas.",
  "No relations history about this entity.": "No hay historial de relaciones sobre esta entidad",
  "No reports about this entity.": "Ningún informe sobre esta entidad.",
  "No task": "Ninguna tarea",
  "No value": "Sin valor",
  "No widget in this workspace": "Sin elementos gráficos en este espacio de trabajo",
  "No work": "Ningún trabajo",
  "None": "Ninguno",
  "Nonee": "Ninguna",
  "Not Specified": "No especificado",
  "Not aplicable": "No aplica",
  "Not applicable": "No aplicable",
  "Note types": "Tipos de notas",
  "Notes": "Notas",
  "Notes about this entity": "Notas sobre esta entidad",
  "Notes about this relationship": "Notas sobre esta relación",
  "Notification": "UNDEFINED",
  "Notifications and triggers": "UNDEFINED",
  "Number": "Número",
  "Number observed": "Número de observaciones",
  "Number of": "Número de",
  "Number of elements": "Número de elementos",
  "Number of entities": "Número de entidades",
  "Number of errors": "Número de erores",
  "Number of relationships": "Número de relaciones",
  "Number of target relations": "Número de relaciones de objetivo",
  "Number of targeting": "Número de ataques",
  "OR": "UNDEFINED",
  "Object": "UNDEFINED",
  "Objective": "Objetivo",
  "Observable type": "Tipo de observable",
  "Observable types": "Tipos de observable",
  "Observable value": "Valor del observable",
  "Observables": "Observables",
  "Observables and indicators conversion": "Conversión entre observables e indicadores",
  "Observables distribution": "Distribución de observables",
  "Observables roles": "Roles de los observables",
  "Observations": "Observaciones",
  "Observed data": "Conjunto de datos observados",
  "Observed datas": "Conjuntos de datos observados",
  "One keyword by line or separated by commas": "Una palabra clave por línea o separada por comas",
  "Only contextual": "Solamente contextual",
  "Open export panel": "Abrir panel de exportación",
  "Open the suggestions": "Abre las sugerencias",
  "OpenCTI - Cyber threat intelligence platform": "OpenCTI - Plataforma de ciberinteligencia de amenazas",
  "OpenCTI version": "Versión de OpenCTI",
  "Operations completed": "Operaciones terminadas",
  "Opinion": "UNDEFINED",
  "Opinions": "Opiniones",
  "Optional, you may want to subscribe to specific entities.": "Opcional, puedes querer suscribirte a entidades concretas.",
  "Options": "Opciones",
  "Order": "Orden",
  "Organization": "Organización",
  "Organization type": "Tipo de organización",
  "Organizations": "Organizaciones",
  "Organizations restriction": "Restricción de organizaciones",
  "Organizations sharing": "UNDEFINED",
  "Originates from": "Se origina en",
  "Origins of the malware": "Orígenes de este malware",
  "Origins of the targeting": "Orígenes de los ataques",
  "Origins of this campaign": "Orígenes de esta campaña",
  "Origins of this incident": "Orígines de este incidente",
  "Origins of this intrusion set": "Orígenes de este set de intrusión",
  "Other": "Otro",
  "Other STIX IDs": "Otros ID de STIX",
  "Others": "UNDEFINED",
  "Out of Range": "Fuera de rango",
  "Overview": "Vista general",
  "Owner": "Propietario",
  "PDB Path": "Ruta PDB",
  "PDF files": "Ficheros  PDF",
  "PDF viewer": "Visor de PDF",
  "PUBLISHER_MANAGER": "Gestor de publicaciones de notificacione",
  "Paper color": "Color del papel",
  "Parameters": "Parámetros",
  "Parent attack patterns": "Patrones de ataque superiores",
  "Parent regions": "Regiones a las que pertenece",
  "Parent sectors": "Sectores a los que pertenece",
  "Part of this sector": "Es parte de este sector",
  "Partner": "Asociado",
  "Password": "Contraseña",
  "Pattern": "Patrón",
  "Pattern type": "Tipo de patrón",
  "Period": "UNDEFINED",
  "Periodicity": "Periodicidad",
  "Permissions": "Permisos",
  "Personal motivations": "Motivaciones personales",
  "Phase name": "Nombre de la fase",
  "Pie chart": "Gráfico de quesos",
  "Platform": "Plataforma",
  "Platform favicon URL": "Dirección URL del favicon de la plataforma",
  "Platform login message": "Mensaje de inicio de sesión de la plataforma",
  "Platform organization": "Organización de la plataforma",
  "Platform title": "Título de la plataforma",
  "Platforms": "Plataformas",
  "Played role": "Rol jugado",
  "Playground": "Playground",
  "Positions": "Localizaciones",
  "Postal code": "Código postal",
  "Potential duplicate entities": "Entidades potencialmente duplicadas",
  "Preview": "Vista previa",
  "Primary color": "Color principal",
  "Primary motivation": "Motivación principal",
  "Priority": "Prioridad",
  "Processed time": "Hora de procesamiento",
  "Processing status": "Estado de procesamientot",
  "Profile": "Perfil",
  "Progress": "Progeso",
  "Proxy": "Proxy",
  "Public stream": "Transmisión pública",
  "Public stream collections": "UNDEFINED",
  "Publication": "Publicación",
  "Publication date": "Fecha de publicación",
  "Queued bundles": "Paquetes en espera",
  "RETENTION_MANAGER": "Gestor de retención",
  "RFIs": "UNDEFINED",
  "RULE_ENGINE": "Motor de reglas",
  "RabbitMQ": "RabbitMQ",
  "Radar chart": "Gráfico de radar",
  "Rating": "Clasificación",
  "Read operations": "Operaciones de lectura",
  "Received time": "Hora de recepción",
  "Redirecting to the Content section": "Redireccionamiento a la sección Contenido",
  "Redirecting to the Knowledge section": "Redireccionamiento a la sección Conocimiento",
  "Redirecting to the Overview section": "Redireccionamiento a la sección Información general",
  "Redis": "Redis",
  "Reference knowledge update": "Actualización de referencia de conocimiento",
  "Reference modification": "Modificación de referencia",
  "References": "Referencias",
  "Refresh the knowledge using this connector": "Actualizar la base de conocimiento usando este conector",
  "Region": "Región",
  "Regions": "Regiones",
  "Regions, countries and cities": "Regiones, países y ciudades",
  "Registered connectors": "Conectores registrados",
  "Registration": "Registro",
  "Registry": "Registro de Windows",
  "Registry key": "Clave de registro",
  "Registry key value": "Valor de la clave de registro",
  "Regular digest": "UNDEFINED",
  "Related cases": "Casos relacionados",
  "Related entities": "Entidades relacionadas",
  "Related entities (generic relation \"related-to\")": "Entidades relacionadas (relación genérica \"relacionada con\")",
  "Related groupings": "Agrupaciones relacionadas",
  "Related reports": "Informes relacionados",
  "Related to this country": "Relacionado con este país",
  "Related to this organization": "Relacionado con esta organización",
  "Related to this region": "Relacionado con esta región",
  "Relation": "Relación",
  "Relation type": "Tipo de relación",
  "Relations": "Relaciones",
  "Relations of the entity": "Relaciones de esta entidad",
  "Relations to other entities": "Relaciones con otras entidades",
  "Relations to threats": "Relaciones con las amenazas",
  "Relationship": "Relación",
  "Relationship type": "Tipo de relación",
  "Relationship types": "Tipos de relaciones",
  "Relationships": "Relaciones",
  "Relative time": "Tiempo relativo",
  "Reliability": "Fiabilidad",
  "Remote OpenCTI URL": "Dirección URL de la instancia de OpenCTI remota",
  "Remote OpenCTI configuration": "Configuración remota de OpenCTI",
  "Remote OpenCTI stream ID": "ID de la instancia de OpenCTI remota",
  "Remote OpenCTI token": "Token de autenticación de la instancia de OpenCTI remota",
  "Remove": "Borrar",
  "Remove from the container": "Borrar del contenedor",
  "Remove from this entity": "Quitar esta entidad",
  "Remove from this object": "Quitar este objeto",
  "Remove selected items": "Quitar los elementos seleccionados",
  "Renew": "Renovar",
  "Replace": "Reemplazarr",
  "Report": "Informe",
  "Report type": "Tipo de informe",
  "Report types": "Tipos de informe",
  "Reports": "Informes",
  "Reports distribution": "Distribución de informes",
  "Required permissions": "Permisos requeridos",
  "Rescan": "Reescanear",
  "Reset": "Reiniciar",
  "Reset filters": "Restablecer filtros",
  "Reset the connector state": "Reiniciar el estado del conector",
  "Resource level": "Nivel de recursos",
  "Response type": "Tipo de respuesta",
  "Retention policies": "Política de retención",
  "Revoked": "Revocado",
  "Rich editor": "Editor enriquecido",
  "Role": "Rol",
  "Roles": "Roles",
  "Rolling time": "Intervalo de consulta",
  "Rolling time (in minutes)": "Intervalo de consulta (en minutos)",
  "Rule entity rescan": "Reescaneo de reglas de entidades",
  "Rule has been cleaned up on the existing data": "La regla ha deshecho los cambios sobre los datos existentes",
  "Rule rescan": "Reescaneo de reglas",
  "Rule rescan (engine is disabled)": "Reescaneo de reglas (el motor está desactivado)",
  "Rules engine": "Motor de reglas",
  "Running": "Comenzó",
  "STIX Version": "Versión de STIX",
  "STIX2 bundle": "Paquete STIX2",
  "STREAM": "Emisión en directo",
  "SUBSCRIPTION_MANAGER": "Gestor de suscripciones",
  "SYNC_MANAGER": "Gestor de sincronización",
  "Saturday": "UNDEFINED",
  "Save": "UNDEFINED",
  "Scope": "Perímetro",
  "Score": "Puntuación",
  "Search": "Buscar",
  "Search for a threat...": "Investigar una amenaza...",
  "Search for an entity": "Buscar una entidad",
  "Search for multiple entities": "Buscar varias entidades",
  "Secondary color": "Color secundario",
  "Secondary motivations": "Motivaciones secundarias",
  "Sector": "Sector",
  "Sectors": "Sectores",
  "Sectors and organizations": "Sectores y organizaciones",
  "Select a relationship": "Seleccionar una relación ",
  "Select all nodes": "Séleccionar todos los nodos",
  "Select by entity type": "Séleccionar por tipo",
  "Select your file": "Seleccionar otro fichero",
  "Selected connectors": "Conectores seleccionados",
  "Selected entities": "Entidades seleccionadas",
  "Selected rules": "Reglas seleccionadas",
  "Sender": "Emisor",
  "Sender email address": "Dirección de correo electrónico del emisor",
  "Separator": "Separador",
  "Settings": "Parámetros",
  "Settings have been updated": "La configuración ha sido actualizada",
  "Severity": "Severidad",
  "Share": "Compartir",
  "Share with an organization": "Compartir con una organización",
  "Sightings": "Detecciones",
  "Sightings distribution": "Distribución de observaciones",
  "Sign in": "Iniciar sesión",
  "Signatures": "Firmas",
  "Simple export (just the entity)": "Exportación simple (solamente la entidad)",
  "Size": "Tamaño",
  "Sophistication": "Sofisticación",
  "Sort by": "Ordenar por",
  "Source": "UNDEFINED",
  "Source name": "Nombre de la fuente",
  "Standard STIX ID": "ID estándar de STIX",
  "Start": "Iniciar",
  "Start date": "Fecha de inicio",
  "Start time": "Inicio de obs.",
  "Starting synchronization (empty = from start)": "Empezando sincronización (vacío = desde el comiendo)",
  "State": "Estado",
  "Statistics": "Estadísticas",
  "Status": "Estado",
  "Status templates": "Plantillas de estado",
  "Step": "Fase",
  "Stop": "Parar",
  "Stop time": "Fin de obs.",
  "Stream ID": "ID de transmisión",
  "Street address": "Dirección",
  "Strong": "Fuerte",
  "Sub attack patterns": "Subpatrones de ataque",
  "Submit a feedback": "Enviar un comentario",
  "Subregions": "Subregiones",
  "Subscriptions & digests": "Suscripciones y resúmenes",
  "Subsectors": "Subsectores",
  "Sunday": "UNDEFINED",
  "Synchronization": "Sincronización",
  "Synthesis of knowledge": "Síntesis de conocimiento",
  "System": "Sistema",
  "Systems": "Sistemas",
  "TASK_MANAGER": "Gestor de tareas",
  "TAXII collections": "Colecciones de TAXII",
  "TTPs": "TTP",
  "TTPs knowledge": "Conocimiento sobre las TTP",
  "TTPs of threats": "TTP de las amenazas",
  "TTPs through time": "TTP a lo largo del tiempo",
  "Table": "Tabla",
  "Table (top 10)": "Tabla (top 10)",
  "Tactics": "Tácticas",
  "Tactics matrix view": "Vista de la matriz de tácticas",
  "Take deletions into account": "Tener en cuenta los borrados",
  "Target": "UNDEFINED",
  "Targeted by this TTP": "Objetivo de esta TTP",
  "Targeted by this actor": "Es objetivo de este actor",
  "Targeted by this intrusion set": "Es objetivo de este set de intrusión",
  "Targeted by this malware": "Es objetivo de este malware",
  "Targeted countries (3 last months)": "Países atacados (tres últimos meses)",
  "Targeted entities": "Entidades",
  "Targeted entity through time": "Entidades atacadas en el tiempo",
  "Targeted entity types": "Tipos de entidades atacadas",
  "Targeted in this campaign": "Es objetivo en esta campaña",
  "Targeted in this incident": "Es objetivo en este incidente",
  "Targeting knowledge": "Conocimiento sobre los objetivos",
  "Targeting this country": "Atacando este país",
  "Targeting this individual": "Atacando a este individuo",
  "Targeting this organization": "Atacando a esta organización",
  "Targeting this region": "Atacando a esta región",
  "Targeting this sector": "Tiene como objetivo este sector",
  "Targeting this vulnerability": "Atacando esta vulnerabilidad",
  "Targeting through time": "Pbjetivos a lo largo del tiempo",
  "Targeting types": "Tipos de objetivos",
  "Task end time": "Hora de fin de la tarea",
  "Task start time": "Hora de inicio de la tarea",
  "Tasks": "UNDEFINED",
  "Technical date": "Fecha técnica",
  "Technical elements (indicators & observables)": "Elementos técnicos (indicadores y observables)",
  "Techniques": "Técnicas",
  "Techniques matrix": "Matriz de técnicas",
  "Text files": "Ficheros de texto",
  "The CSV file has been generated with the parameters of the view and is ready for download.": "El fichero CSV se ha generado con los parámetros de la vista y está preparado para ser descargado.",
  "The alias has been added": "El alias has sido añadido",
  "The code is not correct": "El código es incorrecto",
  "The color must be written in hexadecimal. Example: #ff9800": "El color debe estar escrito en hexadecimal. Ejemplo: #ff9800",
  "The connector has been cleared": "El conector ha sido eliminado",
  "The connector state has been reset": "El estado de este conector ha sido reiniciado",
  "The importation of the file has been started": "La importación del fichero se ha iniciado",
  "The min value cannot be greater than max value": "El valor mínimo no puede ser mayor que el valor máximo",
  "The minimum value cannot be greater than maximum value": "UNDEFINED",
  "The password has been updated": "La contraseña se ha modificado",
  "The relations attached to selected entities will be copied to the merged entity.": "Las relaciones adjuntadas a las entidades seleccionadas serán copiadas a la entidad fusionada.",
  "The rule has been disabled, clean-up launched...": "La regla ha sido desactivada, limpieza lanzada...",
  "The rule has been enabled, rescan of platform data launched...": "La regla ha sido activada, reescaneo de los datos de la plataforma lanzado...",
  "The value is too long": "El valor es demasiado largo",
  "The value is too short": "El valor es demasiado corto",
  "The value must be a date (yyyy-MM-dd)": "El valor debe ser una fecha (AAAA-MM-DD)",
  "The value must be a datetime (yyyy-MM-dd hh:mm (a|p)m)": "El valor debe ser una fecha con minutos (AAAA-MM-DD HH:MM (a|p)m)",
  "The value must be a datetime with seconds (yyyy-MM-dd hh:mm:ss (a|p)m)": "El valor debe ser una fecha con segundos (AAAA-MM-DD HH:MM:ss (a|p)m)",
  "The value must be a number": "El valor debe ser un número",
  "The value must be an URL": "El valor debe ser una dirección URL",
  "The value must be an email address": "El valor debe ser una dirección de correo electrónico",
  "The value must be between min and max value": "El valor debe estar entre el valor mínimo y máximo",
  "The value must be between minimum and maximum value": "UNDEFINED",
  "The value must be greater than or equal to 0": "El valor debe ser mayor o igual a 0",
  "The value must be less than or equal to 100": "El valor debe ser menor o igual a 100",
  "The values do not match": "Los valores no coinciden",
  "Theme": "Tema",
  "This action will generate STIX patterns indicators from the selected observables.": "Esta acción generará indicadores STIX a partir de los observables seleccionados.",
  "This action will generate observables from the selected indicators.": "Esta acción generará observables a partir de los indicadores seleccionados.",
  "This configuration enables an entity to automatically construct an external reference from the uploaded file.": "Esta configuración permite que una entidad construya automáticamente una referencia externa a partir del archivo cargado.",
  "This configuration enables the requirement of a reference message on an entity update.": "Esta configuración habilita el requisito de un mensaje de referencia en una actualización de entidad.",
  "This configuration hide a specific entity type across the entire platform.": "Esta configuración oculta un tipo de entidad específico en toda la plataforma.",
  "This configuration is not available for this entity type": "Esta configuración no está disponible para este tipo de entidad",
  "This connector is active": "Este conector está activo",
  "This connector is disconnected": "Este conector está desconectado",
  "This feature is not available yet.": "Está funcionalidad todavía no está disponible.",
  "This field is required": "Este campo es requerido",
  "This field must be a number": "UNDEFINED",
  "This field must only contain alphanumeric chars, dashes and space": "Este campo debe contener solamente caracteres alfanuméricos, guiones y espacios",
  "This individual is now a user": "Este individuo es ahora un usuario",
  "This individual is part of": "Este individuo es parte de",
  "This malware has been used": "Se ha utilizado este malware",
  "This page is not found on this OpenCTI application.": "Esta página no se ha encontrado en esta aplicación de OpenCTI.",
  "This panel shows by default the latest created entities, use the search to find more.": "Este planel muestra por defecto las entidades creadas en último lugar, usa la búsqueda para encontrar más.",
  "This relation is inferred": "Esta relación se ha inferido",
  "This report contains too many objects to be displayed as a graph. We are working on a new visualization which will allow large graph to be displayed in the future.": "Este informe contiene demasiados objetos para mostrarse como un grafo. Estamos trabajando en una nueva visualización que permitirá mostrar gráficos grandes en el futuro.",
  "This rule has been applied on the existing data": "Esta regla se ha aplicado a los datos existentes",
  "This sector does not have any description.": "Este sector no tiene ninguna descripción.",
  "Threat actor": "Actor de amenazas",
  "Threat actor types": "Tipos de actor de amenazas",
  "Threat actors": "Actores de amenazas",
  "Threat hunting techniques": "Técnicas de «Threat Hunting»",
  "Threats": "Amenazas",
  "Threats targeting": "Conocimiento sobre las amenazas",
  "Threats using this malware": "Amenazas utilizando este código malicioso",
  "Thursday": "UNDEFINED",
  "Ticks": "Rotulador",
  "Time": "UNDEFINED",
  "Timeline": "Cronología",
  "Title": "Título",
  "To name": "Nombre de destino",
  "To type": "Tipo de destino",
  "To use this feature, your platform administrator must enable the according manager in the config.": "Para usar esta función, el administrador de su plataforma debe habilitar el administrador correspondiente en la configuración.",
  "To use this feature, your platform administrator must enable the subscription manager in the config.": "Para utilizar esta función, el administrador de la plataforma debe habilitar el gestor de suscripciones.",
  "Token": "UNDEFINED",
  "Too many objects": "Demasiados objetos",
  "Tool": "Herramienta",
  "Tool types": "Tipos de herramienta",
  "Tool usage": "Uso de la herramienta",
  "Tool version": "Versión de la herramienta",
  "Tools": "Herramientas",
  "Tools versions": "Versiones de las herramientas",
  "Top 10 active entities (3 last months)": "Top 10 de entidades activos (tres últimos meses)",
  "Top 10 threats targeting this entity": "Top 10 de amenazas atacando a esta entidad",
  "Top 10:": "Top 10:",
  "Top Labels (3 last months)": "Top de etiquetas (tres últimos meses)",
  "Total direct relations": "Número de relations directas",
  "Total entities": "Número de entidades",
  "Total indicators": "Número de indicadores",
  "Total notes": "Número de notas",
  "Total number of documents": "Número total de documentos",
  "Total number of operations": "Número total de operaciones",
  "Total observables": "Número de observables",
  "Total pending inserts": "Número de inserciones en espera",
  "Total processed messages": "Total de mensajes procesados",
  "Total relations": "Número de relaciones",
  "Total relationships": "Número de relaciones",
  "Total reports": "Número de informes",
  "Total workspaces": "Número de espacios de trabajo",
  "Triggering on": "UNDEFINED",
  "Triggers": "UNDEFINED",
  "Tuesday": "UNDEFINED",
  "Turn to user": "Transformar en usuario",
  "Two-factor authentication": "Autenticación en dos pasos",
  "Type": "Tipo",
  "Type the code generated in your application": "Escribe el código en tu aplicación",
  "Types": "UNDEFINED",
  "Types of the targeting": "Tipos de ataques",
  "Types of the targets": "Tipos de objetivos",
  "URL": "URL",
  "Unauthorized action, please refresh your browser": "Acción no autorizada, refresca tu navegador",
  "Unfix the nodes and re-apply forces": "Liberar los nodos y reaplicar las fuerzas",
  "Unique identifier": "Identificador único",
  "Unknown": "Desconocida",
  "Unsupported": "No soportado",
  "Update": "Modificar",
  "Update a TAXII collection": "Actualizar una colección TAXII",
  "Update a campaign": "Actualizar una campaña",
  "Update a case incident": "Actualizar un incidente de caso",
  "Update a channel": "Actualizar un canal",
  "Update a city": "Actualizar una ciudad",
  "Update a country": "Actualizar un país",
  "Update a course of action": "Actualizar una contramedida",
  "Update a data component": "Actualizar un componente de datos",
  "Update a data source": "UNDEFINED",
  "Update a date source": "Actualizar una fuente de datos",
  "Update a feed": "Actualizar una fuente de datos",
  "Update a feedback": "Actualizar un comentario",
  "Update a group": "Actualizar un grupo",
  "Update a grouping": "Actualizar una agrupación",
  "Update a individual": "Actualizar un individuo",
  "Update a kill chain phase": "Actualizar una fase de la «kill-chain»",
  "Update a label": "Actualizar una etiqueta",
  "Update a live stream": "Actualizar una emisión en vivo",
  "Update a malware": "Actualizar código malicioso",
  "Update a marking definition": "Actualizar una categoría de clasificación",
  "Update a narrative": "Actualizar una narrativa",
  "Update a note": "Actualizar una nota",
  "Update a position": "Actualizar una posición",
  "Update a region": "Actualizar una región",
  "Update a relationship": "Actualizar una relación",
  "Update a report": "Actualizar un informe",
  "Update a retention policy": "Actualizar una política de retención",
  "Update a role": "Actualizar un rol",
  "Update a sector": "Actualizar un sector",
  "Update a sighting": "Actualizar una detección",
  "Update a status": "Actualizar un estado",
  "Update a status template": "Actualizar una plantilla de estado",
  "Update a subscription": "Actualizar una suscripción",
  "Update a synchronizer": "Actualizar un sincronizador",
  "Update a system": "Actualizar un sistema",
  "Update a threat actor": "Actualizar un actor de amenazas",
  "Update a tool": "Actualizar una herramienta",
  "Update a trigger": "UNDEFINED",
  "Update a user": "Actualizar un usuario",
  "Update a vulnerability": "Actualizar una vulnerabilidad",
  "Update a widget": "Actualizar un elemento gráfico",
  "Update a workspace": "Actualizar un espacio de trabajo",
  "Update an area": "Actualizar una zona",
  "Update an artifact": "Actualizar un artefacto",
  "Update an attack pattern": "Actualizar un patrón de ataque",
  "Update an attribute": "Actualizar un atributo",
  "Update an country": "UNDEFINED",
  "Update an entity": "Actualizar una entidad",
  "Update an event": "Actualizar un evento",
  "Update an external reference": "Actualizar una referencia externa",
  "Update an incident": "Actualizar un incidente",
  "Update an indicator": "Actualizar un indicador",
  "Update an infrastructure": "Actualizar una infrastructura",
  "Update an intrusion set": "Actualizar un set de intrusión",
  "Update an observable": "Actualizar un observable",
  "Update an observed data": "Actualizar un conjunto de datos observados",
  "Update an organization": "Actualizar una organización",
  "Update and complete": "Actualizar y completar",
  "Update entities": "Actualizar entidades",
  "Update opinion": "Actualizar la opinión",
  "Updated the": "Actualizado el",
  "Uploaded files": "Ficheros subidos",
  "Usage": "Uso",
  "Use": "UNDEFINED",
  "Use 2FA authentication": "Usa la autenticación en dos pasos",
  "Use Alt + click to exclude items": "Usar Alt + clic para excluir elementos",
  "Used TTPs": "TTP utilizadas",
  "Used by this actor": "Usado por este actor",
  "Used by this intrusion set": "Utilizado por este set de intrusión",
  "Used by this malware": "Es usado por este malware",
  "Used in this campaign": "Utilizado por esta campaña",
  "Used in this incident": "Utilizado por este incidente",
  "Used tools": "Herramientas urilizadas",
  "User interface": "UNDEFINED",
  "User responsible for data creation (empty = System)": "Usuario responsable de la creación de datos (vacío = System)",
  "User will be created with default groups.": "El usuario se creará con grupos por defecto.",
  "Users": "Usuarios",
  "Using this TTP": "Usando esta TTP",
  "Using this tool": "Usando esta herramienta",
  "Valid from": "Válido desde",
  "Valid until": "Válido hasta",
  "Validate": "Validar",
  "Validate and send for import": "Validar y enviar para importación",
  "Validate this workbench": "Validar este espacio de trabajo",
  "Value": "Valor",
  "Values": "Valores",
  "Variants": "Variantes",
  "Variants of this malware": "Variantes de este malware",
  "Vendor": "Fabricante",
  "Verify": "Verificadorr",
  "Verify SSL certificate": "Verificar el certificado SSL",
  "Versions": "Versiones",
  "Vertical Bar": "Barra vertical",
  "Victimology": "Victimología",
  "Victimology (countries)": "Victimología (países)",
  "Victimology (regions)": "Victimología (regiones)",
  "Victimology (sectors)": "Victimología (sectores)",
  "View": "Vista",
  "View the item": "Ver el objeto",
  "Visualization": "Visualización",
  "Vulnerabilities": "Vulnerabilidades",
  "Vulnerability": "Vulnerabilidad",
  "Vulnerability usage": "Uso de la vulnerabilidad",
  "Webhook": "UNDEFINED",
  "Wednesday": "UNDEFINED",
  "Week day": "UNDEFINED",
  "When you specified the platform organization, data without any organization restriction will be accessible only for users that are part of the platform one": "Cuando especificó la organización de la plataforma, los datos sin ninguna restricción de organización serán accesibles solo para los usuarios que forman parte de la plataforma.",
  "Widget": "Elemento gráfico",
  "Windows scheduled tasks": "Tareas programadas de Windows",
  "Windows services": "Servicios de Windows",
  "Work end time": "Hora de fin de la ejecución",
  "Work start time": "Hora de inicio de la ejecución",
  "Workers statistics": "Estadísticas de los trabajadores",
  "Workflow": "Flujo de trabajo",
  "Workflow of": "Flujo de trabajo de",
  "Workflows": "Flujos de trabajo",
  "Works": "Ejecuciones",
  "Workspace": "Espacio de trabajo",
  "Workspaces": "Espacios de trabajo",
  "Write": "Redacción",
  "Write a note": "Escribir una nota",
  "Write operations": "Operaciones de escritura",
  "Write something awesome...": "Escibe algo genial...",
  "X509 Certificates": "Certificados X509",
  "Year": "Año",
  "Yes": "Sí",
  "You are not allowed to do this.": "No tienes permitido hacer esto.",
  "You do not have any access to the knowledge of this OpenCTI instance.": "No tienes acceso al conocimiento de esta instancia de OpenCTI.",
  "You have no subscription for the moment.": "No tienes ninguna suscripción por el momento.",
  "You have successfully logged out.": "Has cerrado sesión con éxito.",
  "You must be logged in to do this.": "Tienes que iniciar sesión para hacer esto.",
  "You must provide at least one external reference for this type of entity": "Debes facilitar al menos una referencia externa para este tipo de entidad",
  "You need to activate a two-factor authentication. Please type the code generated in your application.": "Necesitas activar una autenticación de dos factores. Por favor, escriba el código generado en su aplicación.",
  "You need to validate your two-factor authentication. Please type the code generated in your application.": "Debe validar su autenticación de dos factores. Por favor, escriba el código generado en su aplicación.",
  "You're targeting more than 1000 entities with this background task, be sure of what you're doing!": "¡Estás seleccionando más de 1000 entidades en esta tarea en segundo plano así que estáte seguro de que sabes lo que haces!",
  "_": "UNDEFINED",
  "added a note": "agregó una nota",
  "day": "UNDEFINED",
  "entities": "entidades",
  "entity_Administrative-Area": "Zona",
  "entity_All": "Todas las entidades",
  "entity_Analysis": "Análisis",
  "entity_Arsenal": "Arsenal",
  "entity_Artifact": "Artefacto",
  "entity_Attack-Pattern": "Patrón de ataque",
  "entity_Autonomous-System": "Sístema autónomo (AS)",
  "entity_Bank-Account": "Cuenta bancaria",
  "entity_Campaign": "Campaña",
  "entity_Case": "Caso",
  "entity_Case-Incident": "Respuesta al incidente",
  "entity_Case-Rfi": "Solicitud de información",
  "entity_Case-Rft": "Solicitud de eliminación",
  "entity_Channel": "Canal",
  "entity_City": "Ciudad",
  "entity_Country": "País",
  "entity_Course-Of-Action": "Contramedida",
  "entity_Cryptocurrency-Wallet": "Monedero de criptomonedas",
  "entity_Cryptographic-Key": "Clave criptográfica",
  "entity_Data-Component": "Componente de datos",
  "entity_Data-Source": "Origen de los datos",
  "entity_Directory": "Directorio",
  "entity_Domain-Name": "Nombre de dominio",
  "entity_Email-Addr": "Dirección de correo electrónico",
  "entity_Email-Message": "Correo electrónico",
  "entity_Email-Mime-Part-Type": "Correo electrónico - MIME Part",
  "entity_Entities": "Entidades",
  "entity_Event": "Evento",
  "entity_Events": "Eventos",
  "entity_External-Reference": "Referencia externa",
  "entity_Feedback": "Comentario",
  "entity_Grouping": "Agrupación",
  "entity_Hostname": "Nombre de host",
  "entity_IPv4-Addr": "Dirección IPv4",
  "entity_IPv6-Addr": "Dirección IPv6",
  "entity_Identity": "Identidad",
  "entity_Incident": "Incidente",
  "entity_Indicator": "Indicador",
  "entity_Individual": "Individuo",
  "entity_Infrastructure": "Infrastructura",
  "entity_Intrusion-Set": "Set de intrusión",
  "entity_Ipv4-Addr": "Dirección IPv4",
  "entity_Ipv6-Addr": "Dirección IPv6",
  "entity_Label": "Etiqueta",
  "entity_Language": "Idioma",
  "entity_Location": "Localización",
  "entity_Locations": "Localizaciones",
  "entity_Mac-Addr": "Dirección MAC",
  "entity_Malware": "Malware",
  "entity_Marking-Definition": "Clasificación",
  "entity_Media-Content": "Contenido multimedia",
  "entity_Mutex": "Mutex",
  "entity_Narrative": "Narrativa",
  "entity_Network-Traffic": "Tráfico de red",
  "entity_Note": "Nota",
  "entity_Observable": "Observable",
  "entity_Observations": "Observaciones",
  "entity_Observed-Data": "Datos observados",
  "entity_Opinion": "Opinión",
  "entity_Organization": "Organización",
  "entity_Payment-Card": "Tarjeta bancaria",
  "entity_Phone-Number": "Número de teléfono",
  "entity_Position": "Posición",
  "entity_Process": "Proceso",
  "entity_Region": "Región",
  "entity_Relationship": "Relación",
  "entity_Report": "Informe",
  "entity_Sector": "Sector",
  "entity_Sighting": "Deteccion",
  "entity_Software": "Aplicación",
  "entity_Stix-Core-Objects": "Entidades y observables",
  "entity_Stix-Core-Relationship": "Relaciones",
  "entity_Stix-Cyber-Observable": "Observable",
  "entity_Stix-Cyber-Observables": "Observables",
  "entity_Stix-Domain-Object": "Entidad",
  "entity_Stix-Domain-Objects": "Entidades",
  "entity_StixFile": "Fichero",
  "entity_Stixfile": "Fichero",
  "entity_System": "Sistema",
  "entity_Techniques": "Técnicas",
  "entity_Text": "Texto",
  "entity_Threat-Actor": "Actor de amenazas",
  "entity_Threats": "Amenazas",
  "entity_Tool": "Herramienta",
  "entity_Url": "Dirección URL",
  "entity_User-Account": "Cuenta de usuario",
  "entity_User-Agent": "User agent",
  "entity_Vulnerability": "Vulnerabilidad",
  "entity_Windows-Registry-Key": "Clave de registro de Windows",
  "entity_Windows-Registry-Value-Type": "Clave de registro de Windows - Valor",
  "entity_X509-Certificate": "Certificado X509",
  "filter_assigneeTo": "Referente",
  "filter_basedOn": "Basado en un observable",
  "filter_containedBy": "Contenedor",
  "filter_createdBy": "Autor",
  "filter_createdBy_not_eq": "NO Autor",
  "filter_elementId": "Entidad relacionada",
  "filter_fromId": "Entidad de origen",
  "filter_fromTypes": "Tipo de origen",
  "filter_killChainPhase": "Fase de la «kill chain»",
  "filter_labelledBy": "Etiqueta",
  "filter_labelledBy_not_eq": "NO etiqueta",
  "filter_markedBy": "Clasificación",
  "filter_markedBy_not_eq": "NO Clasificación",
  "filter_objectContains": "Contiene",
  "filter_sightedBy": "Detectado por/en",
  "filter_sightedBy_not_eq": "NO Detectado por/en",
  "filter_toCreatedAt_end_date": "Ingerido antes",
  "filter_toCreatedAt_start_date": "Ingerido después",
  "filter_toId": "Entidad de destino",
  "filter_toSightingId": "Detectado en",
  "filter_toSightingId_not_eq": "NO Detectado en",
  "filter_toTypes": "Tipo de destino",
  "hour": "UNDEFINED",
  "name": "Nombre",
  "obsContent": "Contenido",
  "of": "UNDEFINED",
  "on": "UNDEFINED",
  "organization": "Organización estructurada",
  "relationship_All": "Todos los tipos de relación",
  "reliability_A": "A - Completamente fiable",
  "reliability_B": "B - Usualmente fiable",
  "reliability_C": "C - Bastante fiable",
  "reliability_D": "D - No habitualmente fiable",
  "reliability_E": "E - No fiable",
  "reliability_F": "F - La fiabilidad no puede ser juzgada",
  "selected": "seleccionado(s)",
  "to exclude items": "UNDEFINED",
  "week": "UNDEFINED"
}