export default {
  "2FA": "ADF",
  "2FA state": "Etat de l'ADF",
  "AND": "UNDEFINED",
  "API access": "Accès à l'API",
  "API key": "Clé d'API",
  "About": "A propos",
  "Abstract": "Résumé",
  "Access stream directly in your browser": "UNDEFINED",
  "Accesses": "Accès",
  "Action type": "Type d'action",
  "Active": "Actif",
  "Activities": "Activités",
  "Activity": "Activité",
  "Add": "Ajouter",
  "Add Tick": "Ajouter un marqueur",
  "Add a widget": "Ajouter un widget",
  "Add an action": "Ajouter une action",
  "Add an entity to this container": "Ajouter une entité à ce conteneur",
  "Add and complete": "Ajouter et compléter",
  "Add attack patterns": "Ajouter des motifs d'attaque",
  "Add context": "Ajouter du contexte",
  "Add courses of action": "Ajouter des conduites à suivre",
  "Add data components": "Ajouter des composants de données",
  "Add data source": "Ajouter une source de données",
  "Add entities": "Ajouter des entités",
  "Add external references": "Ajouter des références externes",
  "Add locations": "Ajouter une localisation",
  "Add new labels": "Ajouter des labels",
  "Add notes": "Ajouter des notes",
  "Add observable": "Ajouter un observable",
  "Add observables": "Ajouter des observables",
  "Add sub attack patterns": "Ajouter des sous motifs d'attaque",
  "Add subsectors": "Ajouter des sous-secteurs",
  "Additional mandatory attributes": "Attributs obligatoires supplémentaires",
  "Admin": "Admin",
  "Advanced search": "Recherche avancée",
  "Affected software": "Logiciels affectés",
  "Affecting this sector": "Affectant ce secteur",
  "Alias": "Alias",
  "Aliases": "UNDEFINED",
  "Aliases separated by commas": "Alias séparés par des virgules",
  "All": "Tout",
  "All confidence levels": "Tous les niveaux de confiance",
  "All entities": "Toutes les entités",
  "All observables": "Tous les observables",
  "All reports": "Tous les rapports",
  "All threats": "Toutes les menaces",
  "All types of entity": "Tous les types d'entité",
  "All types of relationship": "Tous les types de relation",
  "All years": "Toutes les années",
  "Allowed markings": "Marquages autorisés",
  "Already in plat.": "Déjà dans la plat.",
  "Also delete these elements": "Supprimer aussi ces éléments",
  "An unknown error has occurred!  Please try again later.": "Une erreur est survenue ! Merci de rééssayer plus tard.",
  "Analysis": "Analyses",
  "Analyst workbenches": "Espaces de travail analyste",
  "Apply on": "S'applique à",
  "Applying this rule on the existing data": "En cours d'application de cette règle sur les données de la plateforme",
  "Architecture execution env.": "Env. d'éxécution,",
  "Area": "Zone",
  "Areas": "Zones",
  "Arsenal": "Arsenal",
  "Artifacts": "Artefacts",
  "As it happens": "Au fil de l'eau",
  "Assignee(s)": "Référent(s)",
  "Assignees": "Référents",
  "Associated file": "Fichier associé",
  "Attack pattern": "Motif d'attaque",
  "Attack pattern usage": "Usage de ce motif d'attaque",
  "Attack patterns": "Motifs d'attaque",
  "Attributed to this actor": "Attribué à cet acteur",
  "Attributed to this campaign": "Attribué à cette campagne",
  "Attributed to this country": "Attribué à ce pays",
  "Attributed to this individual": "Attribué à cette individualne",
  "Attributed to this intrusion set": "Attribué à ce mode opératoire",
  "Attributed to this organization": "Attribué à cette organisation",
  "Attributed to this region": "Attribué à cette région",
  "Attribution": "Attribution",
  "Authentication": "Authentification",
  "Authentication strategies": "Stratégies d'authentification",
  "Author": "Auteur",
  "Auto new markings": "Autorisation pour les nouveaux marquages",
  "Automatic": "Automatique",
  "Automatic references at file upload": "Références automatiques lors du téléchargement du fichier",
  "Automatic trigger": "Déclenchement automatique",
  "Automatically authorize this group to new marking definition": "Autoriser automatiquement ce groupe sur les nouveaux marquages",
  "Autonomous system": "Système autonome",
  "Autonomous systems": "Systèmes autonomes",
  "Averages of context relations": "Moyennes des relations de contexte",
  "Avoid dependencies resolution": "Aucune résolution des dépendances",
  "Back": "Retour",
  "Background tasks": "Tâches de fond",
  "Bad login or password": "Nom d'utilisateur ou mot de passe incorrect",
  "Base URL": "URL de base",
  "Based on": "Basé sur",
  "Basic information": "Informations de base",
  "Belonging to this organization": "Appartenant à cette organisa.",
  "Browse the link": "Naviguer vers le lien",
  "Bulk search": "Recherche de masse",
  "Bundle content": "Contenu du bundle",
  "Bundle details": "Détails du bundle",
  "Bundles processed": "Bundles traités",
  "CREATE": "CREER",
  "CRITICAL": "UNDEFINED",
  "CSIRT": "CSIRT",
  "CSV file": "Fichier CSV",
  "Campaign": "Campagne",
  "Campaigns": "Campagnes",
  "Cancel": "Annuler",
  "Capabilities": "Capacités",
  "Cards view": "Vue cartes",
  "Cascade delete": "Suppression en cascade",
  "Case priority": "Priorité",
  "Case severity": "Sévérité",
  "Category": "Catégorie",
  "Channel": "Canal",
  "Channel type": "Type de canal",
  "Channel types": "Types de canal",
  "Channels": "Canaux",
  "Cities": "Villes",
  "City": "Ville",
  "Cleaning up this rule on the existing data": "En cours de purge de cette règle des données de la plateforme",
  "Clear": "Effacer",
  "Clear all works": "Nettoyer toutes les exécutions",
  "Clear filters": "Enlever les filtres",
  "Clear this connector": "Supprimer ce connecteur",
  "Close": "Fermer",
  "Cloud Control Plane": "Plan de contrôle Cloud",
  "Collapse": "Réduire",
  "Color": "Couleur",
  "Column": "Colonne",
  "Columns": "Colonnes",
  "Commit message": "Message de justification",
  "Commit message when updating data from the UI.": "Message lors de la modification des données dans l'interface.",
  "Commit messages": "Messages de justificaiton",
  "Compare": "Comparer",
  "Completed tasks": "Tâches terminées",
  "Completed works": "Exécutions terminées",
  "Confidence": "Confiance",
  "Confidence level": "Niveau de confiance",
  "Configuration": "Configuration",
  "Confirmation": "Confirmation",
  "Confirmation required": "Confirmation requise",
  "Connected": "Connecté",
  "Connected workers": "Workers connectés",
  "Connection successfully verified": "La connexion a été vérifiée avec succès",
  "Connector": "Connecteur",
  "Connectors": "Connecteurs",
  "Connectors & workers": "Connecteurs et workers",
  "Constituent": "Bénéficiaire",
  "Contact information": "Informations de contact",
  "Containers": "Conteneurs",
  "Containers (reports, groupings, notes & opinions)": "Conteneurs (rapports, groupements, notes et opinions)",
  "Content": "Contenu",
  "Context relations": "Relations de contexte",
  "Continue": "Continuer",
  "Copied to clipboard": "Copié dans le presse-papier",
  "Copy": "Copie",
  "Copy disabled: too many selected elements (maximum number of elements for a copy: ": "Copie désactivée : trop d’éléments sélectionnés (nombre maximum d'éléments pour une copie: ",
  "Copy/paste text content": "Copier/coller du contenu textuel",
  "Correlate": "Corréler",
  "Correlation view": "Vue des corrélations",
  "Count": "Nombre",
  "Countries": "Pays",
  "Country": "Pays",
  "Course of action": "Conduite à suivre",
  "Courses of action": "Conduites à suivre",
  "Courses of action view": "Vue conduites à suivre",
  "Create": "Créer",
  "Create a TAXII collection": "Créer une collection TAXII",
  "Create a campaign": "Créer une campagne",
  "Create a case incident": "Créer un incident",
  "Create a channel": "Créer un canal",
  "Create a city": "Créer une ville",
  "Create a country": "Créer un pays",
  "Create a course of action": "Créer une conduite à suivre",
  "Create a data component": "Créer un composant de données",
  "Create a data source": "Créer une source de données",
  "Create a feed": "Créer un flux",
  "Create a feedback": "Créer un commentaire",
  "Create a file": "Créer un fichier",
  "Create a group": "Créer un groupe",
  "Create a grouping": "Créer un groupement",
  "Create a individual": "Créer un individu",
  "Create a kill chain phase": "Créer une étape de kill chain",
  "Create a label": "Créer un label",
  "Create a live stream": "Créer un stream live",
  "Create a live trigger": "Créer un déclencheur live",
  "Create a malware": "Créer un code malveillant",
  "Create a marking definition": "Créer un marquage",
  "Create a narrative": "Créer un narratif",
  "Create a nested relationship": "Créer une relation imbriquée",
  "Create a note": "Créer une note",
  "Create a opinions": "UNDEFINED",
  "Create a position": "Créer une position",
  "Create a region": "Créer une région",
  "Create a regular digest": "Créer un résumé régulier",
  "Create a relationship": "Créer une relation",
  "Create a report": "Créer un rapport",
  "Create a retention policy": "Créer une règle de rétention",
  "Create a role": "Créer un rôle",
  "Create a sector": "Créer un secteur",
  "Create a sighting": "Créer une détection",
  "Create a status": "Créer un statut",
  "Create a status template": "Créer un template de statut",
  "Create a subscription": "Créer une souscription",
  "Create a synchronizer": "Créer un synchroniseur",
  "Create a system": "Créer un système",
  "Create a threat actor": "Créer un acteur",
  "Create a tool": "Créer un outil",
  "Create a user": "Créer un utilisateur",
  "Create a vocabulary": "UNDEFINED",
  "Create a vulnerability": "Créer une vulnérabilité",
  "Create a workbench": "Créer un espace de travail",
  "Create a workspace": "Créer un espace de travail",
  "Create an area": "Créer une zone",
  "Create an artifact": "Créer un artefact",
  "Create an attack pattern": "Créer un motif d'attaque",
  "Create an attribute": "Créer un attribut",
  "Create an entity": "Créer une entité",
  "Create an event": "Créer un événement",
  "Create an external reference": "Créer une référence externe",
  "Create an incident": "Créer un incident",
  "Create an indicator": "Créer un indicateur",
  "Create an indicator from this observable": "Créer un indicateur à partir de cet observable",
  "Create an infrastructure": "Créer une infrastructure",
  "Create an intrusion set": "Créer un mode opératoire",
  "Create an observable": "Créer un observable",
  "Create an observed data": "Créer une donnée observée",
  "Create an opinion": "Créer une opinion",
  "Create an organization": "Créer une organisation",
  "Create external reference at upload": "UNDEFINED",
  "Created entities": "Entités créées",
  "Created the": "Créé le",
  "Creation": "Création",
  "Creation date": "Date de création",
  "Creation date (in this platform)": "Date de création (dans la plateforme)",
  "Creator": "Créateur",
  "Creators": "Créateurs",
  "Current password": "Mot de passe actuel",
  "Current state": "Etat actuel",
  "Custom dashboard": "Tableau de bord personnalisé",
  "Custom dashboards": "Tableaux de bord personnalisés",
  "Dark": "Sombre",
  "Dark (with background)": "Sombre (avec arrière-plan)",
  "Dark (without background)": "Sombre (sans arrière-plan)",
  "Dashboard": "Tableau de bord",
  "Dashboard settings": "Paramètres du tableau de bord",
  "Data": "Données",
  "Data component": "Composant de données",
  "Data components": "Composants de données",
  "Data curation": "Curation des données",
  "Data import": "Importation de données",
  "Data import and analyst workbenches": "UNDEFINED",
  "Data sharing": "Partage de données",
  "Data source": "Source de données",
  "Data sources": "Sources de données",
  "Data type": "Type de données",
  "Date": "Date",
  "Date reference": "Référence de la date",
  "Default": "Défaut",
  "Default hidden entity types": "UNDEFINED",
  "Default mandatory attributes": "Attributs obligatoires par défaut",
  "Default membership": "Adhésion par défaut",
  "Default value": "Valeur par défaut",
  "Definition": "Définition",
  "Delete": "Supprimer",
  "Delete the element if no other containers contain it": "Supprimer l'élément si aucun autre conteneur ne le contient",
  "Delete this file": "Supprimer ce fichier",
  "Delete this workbench": "Supprimer cet espace de travail",
  "Deletion": "Suppression",
  "Demo credentials": "Identifiants de démo",
  "Dependencies": "Dépendances",
  "Description": "Description",
  "Details": "Détails",
  "Digest with multiple notifications": "UNDEFINED",
  "Direct Update": "UNDEFINED",
  "Direct relations creations": "Créations de relations directes",
  "Direct targeting of this country": "Ciblage direct de ce pays",
  "Direct targeting of this region": "Ciblage direct de cette région",
  "Direct targeting of this sector": "Ciblage direct de ce secteur",
  "Directories": "Répertoires",
  "Directory": "Répertoire",
  "Disable": "Désactiver",
  "Disable 3D mode": "Désactiver le mode 3D",
  "Disable forces": "Désactiver les forces",
  "Disable tree horizontal mode": "Désactiver le mode arbre horizontal",
  "Disable tree vertical mode": "Désactiver le mode arbre vertical",
  "Disable two-factor authentication": "Désactiver l'authentification double facteur",
  "Disabled": "Désactivé",
  "Disconnected": "Déconnecté",
  "Display as": "Afficher comme",
  "Display global knowledge with filters and criteria.": "Afficher la connaissance globale avec des filtres et des critères.",
  "Display notes": "Afficher les notes",
  "Display specific knowledge using relationships and filters.": "Afficher des connaissances spécifiques en utilisant des relations et des filtres.",
  "Display time range selector": "Afficher le sélecteur d'intervalle de temps",
  "Distribution": "Répartition",
  "Distribution of entities": "Distribution des entités",
  "Distribution of opinions": "Distribution des opinions",
  "Distribution of relations": "Répartition des relations",
  "Distribution of relations (including inferred)": "Répartition des relations (inférences incluses)",
  "Distribution of sources": "Répartition des sources",
  "Distribution:": "Répartition:",
  "Do you want to browse this external link?": "Souhaitez-vous naviguer vers ce lien externe ?",
  "Do you want to clear the works of this connector?": "Souhaitez-vous nettoyer toutes les exécutions de ce connecteur ?",
  "Do you want to create a STIX Indicator from this observable?": "Souhaitez-vous créer un indicateur STIX depuis cet observable ?",
  "Do you want to delete these entities?": "Souhaitez-vous supprimer ces entités ?",
  "Do you want to delete this area?": "Souhaitez-vous supprimer cette zone ?",
  "Do you want to delete this attack pattern?": "Souhaitez-vous supprimer ce motif d'attaque ?",
  "Do you want to delete this attribute?": "Souhaitez-vous supprimer cet attribut ?",
  "Do you want to delete this campaign?": "Souhaitez-vous supprimer cette campagne ?",
  "Do you want to delete this case incident ?": "Voulez-vous supprimer ce cas d'incident ?",
  "Do you want to delete this city?": "Souhaitez-vous supprimer cette ville ?",
  "Do you want to delete this country?": "Souhaitez-vous supprimer ce pays ?",
  "Do you want to delete this course of action?": "Souhaitez-vous supprimer cette conduite à suivre ?",
  "Do you want to delete this data component?": "Souhaitez-vous supprimer ce composant de données ?",
  "Do you want to delete this data source?": "Souhaitez-vous supprimer cette source de données ?",
  "Do you want to delete this entity?": "Souhaitez-vous supprimer cette entité ?",
  "Do you want to delete this external reference?": "Souhaitez-vous supprimer cette référence externe ?",
  "Do you want to delete this feed?": "Souhaitez-vous supprimer ce flux ?",
  "Do you want to delete this feedback ?": "Voulez-vous supprimer ce commentaire ?",
  "Do you want to delete this file?": "Souhaitez-vous supprimer ce fichier ?",
  "Do you want to delete this group?": "Souahitez-vous supprimer ce groupe ?",
  "Do you want to delete this grouping?": "Souhaitez-vous supprimer ce groupement ?",
  "Do you want to delete this incident?": "Souhaitez-vous supprimer cet incident ?",
  "Do you want to delete this indicator?": "Souhaitez-vous supprimer cet indicateur ?",
  "Do you want to delete this individual?": "Souhaitez-vous supprimer cette individualne ?",
  "Do you want to delete this intrusion set?": "Souhaitez-vous supprimer ce mode opératoire ?",
  "Do you want to delete this kill chain phase?": "Souhaitez-vous supprimer cette étape de kill chain ?",
  "Do you want to delete this label?": "Souhaitez-vous supprimer ce label ?",
  "Do you want to delete this live stream?": "Souhaitez-vous supprimer ce stream live ?",
  "Do you want to delete this malware?": "Souhaitez-vous supprimer ce code malveillant ?",
  "Do you want to delete this marking definition?": "Souhaitez-vous supprimer ce marquage ?",
  "Do you want to delete this note?": "Souhaitez-vous supprimer cette note ?",
  "Do you want to delete this observable?": "Souhaitez-vous supprimer cet observable ?",
  "Do you want to delete this observed data?": "Souhaitez-vous supprimer cette données observée ?",
  "Do you want to delete this organization?": "Souhaitez-vous supprimer cette organisation ?",
  "Do you want to delete this region?": "Souhaitez-vous supprimer cette région ?",
  "Do you want to delete this relation?": "Souhaitez-vous supprimer cette relation ?",
  "Do you want to delete this report?": "Souhaitez-vous supprimer ce rapport ?",
  "Do you want to delete this role?": "Souhaitez-vous supprimer ce rôle ?",
  "Do you want to delete this sector?": "Souhaitez-vous supprimer ce secteur ?",
  "Do you want to delete this sighting?": "Souhaitez-vous supprimer cette détection ?",
  "Do you want to delete this status template?": "Souhaitez-vous supprimer ce template de statut ?",
  "Do you want to delete this synchronizer?": "Souhaitez-vous supprimer ce synchroniseur ?",
  "Do you want to delete this system?": "Souhaitez-vous supprimer ce système ?",
  "Do you want to delete this threat actor?": "Souhaitez-vous supprimer cet acteur ?",
  "Do you want to delete this tool?": "Souhaitez-vous supprimer cet outil ?",
  "Do you want to delete this user?": "Souahitez-vous supprimer cet utilisateur ?",
  "Do you want to delete this vulnerability?": "Souhaitez-vous supprimer cette vulnérabilité ?",
  "Do you want to delete this widget?": "Souhaitez-vous supprimer ce widget ?",
  "Do you want to delete this workbench?": "Souhaitez-vous supprimer cet espace de travail ?",
  "Do you want to delete this workspace?": "Souhaitez-vous supprimer cet espace de travail ?",
  "Do you want to disable this rule?": "Souhaitez-vous désactiver cette règle ?",
  "Do you want to enable this rule?": "Souhaitez-vous activer cette règle ?",
  "Do you want to kill all the sessions of this user?": "Souhaitez-vous supprimer toutes les sessions de cet utilisateur ?",
  "Do you want to kill this session?": "Souhaitez-vous supprimer cette session ?",
  "Do you want to remove the entity from this container?": "Souhaitez-vous supprimer cette entité de ce conteneur ?",
  "Do you want to remove the entity from this grouping?": "Souhaitez-vous retirer cette entité de ce groupement ?",
  "Do you want to remove the entity from this report?": "Souhaitez-vous retirer cette entité de ce rapport ?",
  "Do you want to remove the indicator from this observable?": "Souhaitez-vous supprimer cet indicator de cet observable ?",
  "Do you want to remove the observable from this indicator?": "Souhaitez-vous supprimer cet observable de cet indicateur ?",
  "Do you want to remove these elements from this grouping?": "Souhaitez-vous supprimer ces éléments de ce grouping ?",
  "Do you want to remove these elements from this investigation?": "Souhaitez-vous supprimer ces éléments de cette investigation ?",
  "Do you want to remove these elements from this report?": "Souhaitez-vous supprimer ces éléments de ce rapport ?",
  "Do you want to remove this external reference?": "Souhaitez-vous retirer cette référence externe ?",
  "Do you want to remove this groupement?": "Souhaitez-vous supprimer ce groupement ?",
  "Do you want to remove this job?": "Souhaitez-vous supprimer cette tâche ?",
  "Do you want to remove this note?": "Souhaitez-vous retirer cette note ?",
  "Do you want to remove this object?": "Souhaitez-vous retirer cet object ?",
  "Do you want to remove this opinion?": "Souhaitez-vous supprimer cette opinions ?",
  "Do you want to remove this report?": "Souhaitez-vous supprimer ce rapport ?",
  "Do you want to remove this status?": "Voulez-vous supprimer ce statut ?",
  "Do you want to reset the state of this connector?": "Souhaitez-vous réinitialiser l'état de ce connecteur ?",
  "Do you want to start this synchronizer?": "Souhaitez-vous démarrer ce synchroniseur ?",
  "Do you want to stop this synchronizer?": "Souhaitez-vous arrêter ce synchroniseur ?",
  "Domain": "Nom de domaine",
  "Domain names": "Noms de domaine",
  "Donut": "Donut",
  "Donut chart": "Donut",
  "Download": "Télécharger",
  "Download this file": "Télécharger ce fichier",
  "EXPIRATION_SCHEDULER": "Planificateur d'expiration",
  "EXTERNAL_IMPORT": "Import de données",
  "Each tick value must be between min and max value": "Chaque valeur de marqueur doit être comprise entre la valeur min et max",
  "Edit the selected item": "Editer l'élément sélectionné",
  "Elasticsearch": "Elasticsearch",
  "Element will be rescan with all compatible activated rules": "L'élément sera rafraichi avec toutes les règles activées et compatibles",
  "Elements successfully copied": "Elements copiés avec succès",
  "Email": "Email",
  "Email address": "Adresse email",
  "Email addresses": "Adresses email",
  "Email subject": "Sujet de mail",
  "Emails": "Emails",
  "Enable": "Activer",
  "Enable 3D mode": "Activer le mode 3D",
  "Enable commit messages": "Activer les messages de justification",
  "Enable forces": "Activer les forces",
  "Enable this feature": "Activer cette fonctionnalité",
  "Enable tree mode": "Activer le mode arbre",
  "Enable two-factor authentication": "Activer l'authentification double facteur",
  "Enabled": "Activé",
  "Enabled import connectors": "Connecteurs d'import activés",
  "Enabled the ": "Activée le ",
  "End date": "Date de fin",
  "Enforce reference": "Appliquer les références obligatoires",
  "Enforce references": "Appliquer les références",
  "Enforce two-factor authentication": "Imposer l'authentification double facteur",
  "Enrich": "Enrichir",
  "Enrichment": "Enrichissement",
  "Enrichment connectors": "Connecteurs d'enrichissement",
  "Entities": "Entités",
  "Entities distribution": "Distribution des entités",
  "Entities view": "Vue entités",
  "Entity": "Entité",
  "Entity aliases": "Alias de l'entité",
  "Entity details": "Détails de l'entité",
  "Entity enrichment": "Enrichissement de l'entité",
  "Entity settings": "Paramètres de l'entité",
  "Entity type": "Type d'entité",
  "Entity types": "Types d'entité",
  "Entity usage": "Usage de cette entité",
  "Error": "Erreur",
  "Event types": "Types d'événement",
  "Events": "Evénements",
  "Every 1 hour": "Toutes les heures",
  "Every 24 hours": "Toutes les 24 heures",
  "Every month": "Tous les mois",
  "Every week": "Toutes les semaines",
  "Everything": "Tous les éléments",
  "Evidences": "",
  "Evolution": "Evolution",
  "Example": "Exemple",
  "Expand": "Etendre",
  "Expand elements": "Etendre les éléments",
  "Explanation": "Explication",
  "Explore": "Explorer",
  "Explore the attack campaigns of the dataset through time and involved entities.": "Explorer les campagnes d'attaques des données à travers le temps et les entités impliquées.",
  "Explore the kill chains of entities through time and other contextual information like campaigns or incidents.": "Explorer les kill chains des entités à travers le temps et d'autres informations contextuelles comme les campagnes ou les incidents.",
  "Explore the observables of the dataset though time to visualize clusters and correlations.": "Explorer les observables des données à travers le temps pour visualiser des clusters et des corrélations.",
  "Explore the techniques, tactics and procedures of the dataset through time and entities who used its.": "Explorer les arsenal, tactiques et procédures des données à travers le temps et les entités qui les utilisent.",
  "Explore the victims and the targets of the dataset through space and time.": "Explorer les victimes et les cibles des données à travers l'espace et le temps",
  "Explore the vulnerabilities used by entities through time and kill chain phases.": "Explorer les vulnérabilités utilisées par les entités à travers le temps et les phases de la kill chain.",
  "Export": "Exporter",
  "Export as PDF": "Exporter comme PDF",
  "Export as image": "Exporter comme image",
  "Export data in CSV": "Exporter les données en CSV",
  "Export format": "Format d'export",
  "Export is disabled because too many entities are targeted (maximum number of entities is: ": "L’exportation est désactivée car trop d’entités sont ciblées (le nombre maximal d’entités est de : ",
  "Export successfully started": "L'export a démarré avec succès",
  "Export the entity": "Exporter l'entité",
  "Export to CSV": "Exporter en CSV",
  "Export to PDF": "Exporter en PDF",
  "Export to document (pdf)": "Exporter en document (pdf)",
  "Export to image": "Exporter en image",
  "Export to image (png)": "Exporter en image (png)",
  "Export type": "Type d'export",
  "Exported files": "Fichiers exportés",
  "Exports list": "Liste des exports",
  "Exports panel": "Volet exports",
  "External ID": "ID externe",
  "External authentication": "Authentification externe",
  "External references": "Références externes",
  "External references files": "Fichiers des références externes",
  "False positive": "Faux positif",
  "Feedback": "UNDEFINED",
  "Feeds (CSV)": "Flux (CSV)",
  "Field": "Attribut",
  "Field type": "Type d'attribut",
  "File MD5 hash": "Condensat MD5 de fichier",
  "File SHA1 hash": "Condensat SHA1 de fichier",
  "File SHA256 hash": "Condensat SHA256 de fichier",
  "File and associated external reference successfully removed": "Fichier et référence externe associé supprimés avec succès",
  "File hash": "Condensat de fichier",
  "File hashes": "Condensats de fichiers",
  "File information": "Information du fichier",
  "File name": "Nom de fichier",
  "File path": "Chemin de fichier",
  "File successfully removed": "Fichier supprimé avec succès",
  "File successfully uploaded": "Fichier uploadé avec succès",
  "File successfully uploaded and associated external reference successfully created": "Fichier uploadé avec succès et référence externe associée créee avec succès",
  "File to import": "Fichier à importer",
  "Files": "Fichiers",
  "Files & history": "Fichiers & activité",
  "Filter authors (created by)": "Filtrer les auteurs (créé par)",
  "Filter by": "Filtrer par",
  "Filter entity types": "Filtrer les types d'entité",
  "Filter marking definitions": "Filtrer les marquages",
  "Filters": "Filtres",
  "First obs.": "Première obs.",
  "First observed": "Première observation",
  "First seen": "Première observation",
  "Firstname": "Prénom",
  "Fit graph to canvas": "Dimensionner le graphe à l'espace",
  "Force now": "Forcer maintenant",
  "Free text import": "Import de texte libre",
  "Friday": "UNDEFINED",
  "From name": "Nom source",
  "From type": "Type source",
  "Full export (entity and first neighbours)": "Export complet (entité et ses voisins)",
  "Functional date": "Date fonctionnelle",
  "GRAPHQL_API": "API GraphQL",
  "General": "Général",
  "Generate": "Générer",
  "Generate an export": "Générer un export",
  "Generated the": "Généré le",
  "Generation in progress...": "Génération en cours...",
  "Global": "Global",
  "Global keyword": "Mot-clé global",
  "Global kill chain": "Kill chain globale",
  "Global parameters": "Paramètres généraux",
  "Goals": "Objectifs",
  "Goals (1 / line)": "Objectifs (1 / ligne)",
  "Good": "Bon",
  "Granted by default": "Alloué par défaut",
  "Granted by default at user creation": "Alloué par défaut à la création d'un utilisateur",
  "Graph": "Graph",
  "Graph type": "Type de graphique",
  "Graph view": "Vue graphe",
  "Grouping": "Groupement",
  "Groupings": "Groupements",
  "Groups": "Groupes",
  "Groups permissions on data marking is not fully implemented yet.": "Les permissions des groupes sur le marquage des données n'est pas encore implémenté.",
  "Groups with this role": "Groupes avec ce role",
  "HISTORY_MANAGER": "Manager d'historique",
  "HTML files": "Fichiers HTML",
  "Heatmap": "Carte de chaleur",
  "Hidden entity types": "Types d'entité cachés",
  "Hidden in interface": "Caché dans l'interface",
  "Hidden in roles": "Caché dans les roles",
  "Hide in the platform": "Cacher dans la plateforme",
  "High": "Élevé",
  "History": "Activité",
  "Horizontal Bar": "Barre horizontale",
  "Host": "Hôte",
  "IF": "SI",
  "INTERNAL_ENRICHMENT": "Enrichissement",
  "INTERNAL_EXPORT_FILE": "Export de fichiers",
  "INTERNAL_IMPORT_FILE": "Import de fichiers",
  "IPv4 address": "Adresse IPv4",
  "IPv4 addresses": "Adresses IPv4",
  "IPv6 address": "Adresse IPv6",
  "IPv6 addresses": "Adresses IPv6",
  "Identities": "Identités",
  "Identity": "Identité",
  "Impacted": "Impactés",
  "Implant": "Implant",
  "Implementation languages": "Langages d'implémentation",
  "Import": "Importer",
  "Import data": "Importer des données",
  "Import successfully asked": "L'import a été demandé",
  "Import type": "Type d'import",
  "In OpenCTI, a predictable STIX ID is generated based on one or multiple attributes of the entity.": "Dans OpenCTI, un ID STIX prédictif est généré basé sur un ou plusieurs attributs de cette entité.",
  "In all the database": "Dans toute la base",
  "In progress messages": "Messages en traitement",
  "In progress tasks": "Tâches en cours",
  "In progress works": "Exécutions en cours",
  "In this report, ": "Dans ce rapport, ",
  "Incident": "Incident",
  "Incident Date": "Date de l'incident",
  "Incident type": "Type d'incident",
  "Incidents": "Incidents",
  "Include headers in the feed": "Inclure les en-têtes dans le flux",
  "Indicator": "Indicateur",
  "Indicator pattern": "Motif de l'indicateur",
  "Indicator type": "Type d'indicateur",
  "Indicator types": "Types d'indicateur",
  "Indicators": "Indicateurs",
  "Indicators composed with this observable": "Indicateurs composés avec cet observable",
  "Indicators/observables generation": "Génération d'indicateurs/observables",
  "Individual": "Individu",
  "Individuals": "Individus",
  "Inference explanation": "Explication de l'inférence",
  "Inference rules": "Règles d'inférence",
  "Inferences": "Inférences",
  "Inferred knowledge based on the rule ": "Connaissance inférée basée sur la règle ",
  "Information": "Informations",
  "Infrastructure types": "Types d'infrastructure",
  "Infrastructures": "UNDEFINED",
  "Ingested entities": "Entités stockées",
  "Initiator": "Initiateur",
  "Intrusion set": "Mode opératoire",
  "Intrusion sets": "Modes opératoires",
  "Investigate": "Investiguer",
  "Investigations": "UNDEFINED",
  "Is family": "Est une famille",
  "Is family?": "Est une famille ?",
  "JSON content": "Contenu JSON",
  "Just in the report": "Juste dans le rapport",
  "Key": "Clé",
  "Kill chain": "Kill chain",
  "Kill chain name": "Nom de la kill chain",
  "Kill chain phase": "Phase de kill chain",
  "Kill chain phases": "Phases de kill chain",
  "Kill chain view": "Vue kill chain",
  "Kill chains": "Kill chains",
  "Knowledge": "Connaissance",
  "Knowledge entity": "Entité de connaissance",
  "Knowledge graph": "Graph de connaissance",
  "Knowledge update (except indicators & observables)": "Modification des connaissances (sauf indicateurs et observables)",
  "Label": "Label",
  "Labels": "Labels",
  "Labels & Attributes": "Labels & Attributs",
  "Language": "Langue",
  "Last": "UNDEFINED",
  "Last 24 hours": "Dernières 24 heures",
  "Last 6 months": "Derniers 6 mois",
  "Last 7 days": "Derniers 7 jours",
  "Last execution": "Dernière éxecution",
  "Last ingested reports (creation date in the platform)": "Derniers rapports ajoutés (date de création dans la plateforme)",
  "Last modified": "Dernière modification",
  "Last modified entities": "Dernières entités modifiées",
  "Last month": "Dernier mois",
  "Last notes": "Dernières notes",
  "Last obs.": "Dernière obs.",
  "Last observables": "Derniers observables",
  "Last observed": "Dernière observation",
  "Last processed message": "Dernier message traité",
  "Last reports": "Derniers rapports",
  "Last reports about the entity": "Derniers rapports à propos de l'entité",
  "Last run": "Dernière exécution",
  "Last run:": "Dernière exécution:",
  "Last seen": "Dernière observation",
  "Last targeted organizations in this sector": "Dernières organisations ciblées dans ce secteur",
  "Last update": "Dernière mise à jour",
  "Last year": "Dernière année",
  "Lastname": "Nom",
  "Latest created relationships": "Dernières relations créées",
  "Latest reports about this entity": "Derniers rapports à propos de l'élément",
  "Latest reports written by this entity": "Derniers rapports écrits par cette entité",
  "Latitude": "UNDEFINED",
  "Launch": "Lancer",
  "Launch a background task": "Lancer une tâche de fond",
  "Launch an import": "Lancer un import",
  "Launch an import of this file": "Lancer un import de ce fichier",
  "Launch rescan": "Lancer le re-scan",
  "Layers": "Couches",
  "Let the field empty to grant all users": "Laissez le champ vide pour autoriser tous les utilisateurs",
  "Level": "Niveau",
  "Light": "Clair",
  "Light (with background)": "Clair (avec arrière-plan)",
  "Light (without background)": "Clair (sans arrière-plan)",
  "Likelihood": "Probabilité",
  "Limit": "Limite",
  "Limits": "UNDEFINED",
  "Line chart": "Graphique linéaire",
  "Lines view": "Vue lignes",
  "Linked entities": "Entités liées",
  "Linked entity": "Entité liée",
  "Linked knowledge": "Connaissance liée",
  "Linked threat": "Menace liée",
  "Linked threat(s)": "Menace(s) liée(s)",
  "Links with threats": "Liens avec des menaces",
  "List": "Liste",
  "List of entities": "Liste d'entités",
  "Live streams": "Streams live",
  "Live trigger": "Déclencheur live",
  "Localized in this country": "Localisé dans ce pays",
  "Localized in this region": "Localisé dans cette région",
  "Location": "Localisation",
  "Locations": "Localisations",
  "Locations of this individual": "Lieux de cette individualne",
  "Locations of this organization": "Lieux de cette organisation",
  "Log sources": "Sources de log",
  "Log sources (1 / line)": "Sources de log (1 / ligne)",
  "Login": "Nom d'utilisateur",
  "Logout": "Se déconnecter",
  "Longitude": "UNDEFINED",
  "Low": "Faible",
  "MAC address": "Adresse MAC",
  "MAC addresses": "Adresses MAC",
  "MEDIUM": "UNDEFINED",
  "Main observable type": "Type d'observable principal",
  "Make this stream public and available to anyone": "Rendre ce stream public et accessible à tous",
  "Malicious": "Malveillant",
  "Malware": "Code malveillant",
  "Malware types": "Type de code malveillant",
  "Malwares": "Codes malveillants",
  "Manage a container": "Gérer un conteneur",
  "Manage an entity": "Gérer une entité",
  "Manage an observable": "Gérer un observable",
  "Mandatory attributes": "Attributs obligatoires",
  "Manual": "Manuel",
  "Map": "Carte",
  "Markdown files": "Fichiers Markdown",
  "Markdown source": "Source markdown",
  "Marking": "Marquage",
  "Marking definitions": "Marquages",
  "Markings": "Marquages",
  "Matrix view": "Vue matricielle",
  "Max marking definition level": "Niveau de marquage maximum",
  "Max retention": "Rétention maximum",
  "Maximum": "UNDEFINED",
  "Maximum retention days": "Jours de rétention maximum",
  "Med": "Moyen",
  "Members": "Membres",
  "Merge": "Fusionner",
  "Merge entities": "Fusionner des entités",
  "Merged entity": "Entité fusionnée",
  "Message": "UNDEFINED",
  "Metrics": "Métriques",
  "MinIO": "MinIO",
  "Mini map": "Mini carte",
  "Minimum": "UNDEFINED",
  "Minimum one outcome": "UNDEFINED",
  "Minimum one trigger": "UNDEFINED",
  "Mitigated attack patterns": "Motifs d'attaque atténués",
  "Moderate": "Modéré",
  "Modification": "Modification",
  "Modification date": "Date de modification",
  "Modified": "Modifié",
  "Monday": "UNDEFINED",
  "Month": "Mois",
  "Month day": "UNDEFINED",
  "More": "Plus",
  "Most recent history": "Historique récent",
  "Multiple": "UNDEFINED",
  "Multiple entities selected": "Plusieurs entités sélectionnées",
  "Mutex": "Mutex",
  "NOTIFICATION_MANAGER": "Manager de génération de notifications",
  "Name": "Nom",
  "Narrative": "Narratif",
  "Narratives": "Narratifs",
  "Nested objects": "Objets liés",
  "Network": "Réseau",
  "Never enabled": "Jamais activée",
  "Never generated": "Jamais généré",
  "New alias": "Nouvel alias",
  "New password": "Nouveau mot de passe",
  "No": "Non",
  "No available options": "Aucune option disponible",
  "No available public stream on this platform": "UNDEFINED",
  "No connector available for the selected entities.": "Aucun connecteur disponible pour les entités sélectionnées.",
  "No connectors are enabled on this platform.": "Aucun connecteur n'est actif sur cette plateforme",
  "No connectors for this type of entity": "Aucun connecteur pour ce type d'entité",
  "No description": "UNDEFINED",
  "No description of this targeting": "Aucune description de ce ciblage",
  "No description of this usage": "Aucune description de cet usage",
  "No enrichment connectors on this platform": "Aucun connecteur d'enrichissement sur cette plateforme",
  "No entities of this type has been found.": "Aucune entité de ce type n'a été trouvée.",
  "No entities were found for this search.": "Aucune entité n'a été trouvée pour cette recherche.",
  "No export connector available to generate an export": "Aucun connecteur d'export disponible pour générer un export",
  "No file for the moment": "Aucun fichier pour le moment",
  "No file selected.": "Aucun fichier sélectionné.",
  "No files in this category.": "Aucun fichier dans cette catégorie.",
  "No history about this entity.": "Aucun historique à propos cette entité.",
  "No history about this relationship.": "Aucun historique à propos de cette relation",
  "No import connectors on this platform": "Aucun connecteur d'import sur cette plateforme",
  "No label": "Aucun label",
  "No notes about this entity yet.": "Aucune note concernant cette entité pour le moment",
  "No potential duplicate entities has been found.": "Aucun potentiel duplicat d'entité n'a été trouvé.",
  "No relations history about this entity.": "Aucun historique de relations à propos cette entité.",
  "No reports about this entity.": "Aucun rapport à propos de cette entité.",
  "No task": "Aucune tâche",
  "No value": "Aucune valeur",
  "No widget in this workspace": "Aucun widget dans cet espace de travail",
  "No work": "Aucune exécution",
  "None": "Aucun",
  "Nonee": "Aucune",
  "Not Specified": "Non spécifié",
  "Not aplicable": "Non applicable",
  "Not applicable": "Non applicable",
  "Note types": "Types de note",
  "Notes": "UNDEFINED",
  "Notes about this entity": "Notes à propos de cette entité",
  "Notes about this relationship": "Notes à propos de cette relation",
  "Notification": "Notification",
  "Notifications and triggers": "Notifications et déclencheurs",
  "Number": "Nombre",
  "Number observed": "Nombre de fois",
  "Number of": "Nombre de",
  "Number of elements": "Nombre d'éléments",
  "Number of entities": "Nombre d'entités",
  "Number of errors": "Nombre d'erreurs",
  "Number of relationships": "Nombre de relations",
  "Number of target relations": "Nombre de relations de ciblage",
  "Number of targeting": "Nombre de ciblages",
  "OR": "UNDEFINED",
  "Object": "UNDEFINED",
  "Objective": "Objectif",
  "Observable type": "Type d'observable",
  "Observable types": "Types d'observable",
  "Observable value": "Valeur de l'observable",
  "Observables": "Observables",
  "Observables and indicators conversion": "Conversion entre observables et indicateurs",
  "Observables distribution": "Distribution des observables",
  "Observables roles": "Rôles des observables",
  "Observations": "Observations",
  "Observed data": "Donnée observée",
  "Observed datas": "Données observées",
  "One keyword by line or separated by commas": "Un mot-clé par ligne ou séparé par des virgules",
  "Only contextual": "Seulement contextuel",
  "Open export panel": "Ouvrir le volet d'export",
  "Open the suggestions": "Ouvrir les suggestions",
  "OpenCTI - Cyber threat intelligence platform": "OpenCTI - Plateforme d'analyse de la cybermenace",
  "OpenCTI version": "OpenCTI version",
  "Operations completed": "Opérations terminées",
  "Opinion": "UNDEFINED",
  "Opinions": "UNDEFINED",
  "Optional, you may want to subscribe to specific entities.": "Optionnel, si vous souhaitez souscrire à des entités spécifiques",
  "Options": "Options",
  "Order": "Ordre",
  "Organization": "Organisation",
  "Organization type": "Type d'organisation",
  "Organizations": "Organisations",
  "Organizations restriction": "Restriction d'organisations",
  "Organizations sharing": "UNDEFINED",
  "Originates from": "Originaire de",
  "Origins of the malware": "Origines de ce code",
  "Origins of the targeting": "Origines du ciblage",
  "Origins of this campaign": "Origine de cette campagne",
  "Origins of this incident": "Origine de cet incident",
  "Origins of this intrusion set": "Origine de ce mode opératoire",
  "Other": "Autre",
  "Other STIX IDs": "Autres IDs STIX",
  "Others": "UNDEFINED",
  "Out of Range": "Hors champ",
  "Overview": "Aperçu",
  "Owner": "Propriétaire",
  "PDB Path": "Chemin PDB",
  "PDF files": "Fichiers PDF",
  "PDF viewer": "Visualiseur PDF",
  "PUBLISHER_MANAGER": "Manager de publication de notifications",
  "Parameters": "Paramètres",
  "Parent attack patterns": "Motifs d'attaque parents",
  "Parent regions": "Régions parentes",
  "Parent sectors": "Secteurs parents",
  "Part of this sector": "Appartenant à ce secteur",
  "Partner": "Partenaire",
  "Password": "Mot de passe",
  "Pattern": "Motif",
  "Pattern type": "Type de motif",
  "Period": "UNDEFINED",
  "Periodicity": "Périodicité",
  "Permissions": "Permissions",
  "Personal motivations": "Motivations personnelles",
  "Phase name": "Nom de l'étape",
  "Pie chart": "Camembert",
  "Platform": "Système d'exploitation",
  "Platform favicon URL": "URL de la favicon de la plateforme",
  "Platform organization": "Organisation de la plateforme",
  "Platform title": "Titre de la plateforme",
  "Platforms": "Systèmes d'exploitation",
  "Played role": "Rôle joué",
  "Playground": "Playground",
  "Positions": "UNDEFINED",
  "Postal code": "Code postal",
  "Potential duplicate entities": "Duplicats potentiels d'entités",
  "Preview": "Aperçu",
  "Primary motivation": "Motivation première",
  "Priority": "Priorité",
  "Processed time": "Envoi des données",
  "Processing status": "Etat du traitement",
  "Profile": "Profil",
  "Progress": "Progression",
  "Proxy": "Proxy",
  "Public stream": "Stream public",
  "Public stream collections": "UNDEFINED",
  "Publication": "Publication",
  "Publication date": "Date de publication",
  "Queued bundles": "Bundles en attente",
  "RETENTION_MANAGER": "Manager de rétention",
  "RFIs": "UNDEFINED",
  "RULE_ENGINE": "Moteur de règles",
  "RabbitMQ": "RabbitMQ",
  "Radar chart": "Radar",
  "Rating": "Notation",
  "Read operations": "Opérations de lecture",
  "Received time": "Délenchement",
  "Redirecting to the Content section": "Redirection vers la section Contenu",
  "Redirecting to the Knowledge section": "Redirection vers la section Connaissances",
  "Redirecting to the Overview section": "Redirection vers la section Vue d’ensemble",
  "Redis": "Redis",
  "Reference knowledge update": "Références des modifications",
  "Reference modification": "Références de modification",
  "References": "Références",
  "Refresh the knowledge using this connector": "Actualiser la connaissance en utilisant ce connecteur",
  "Region": "Région",
  "Regions": "Régions",
  "Regions, countries and cities": "Régions, pays et villes",
  "Registered connectors": "Connecteurs enregistrés",
  "Registration": "Inscription",
  "Registry": "Registre Windows",
  "Registry key": "Clé de reg.",
  "Registry key value": "Valeur de clé de reg.",
  "Regular digest": "Résumé régulier",
  "Related cases": "Cas connexes",
  "Related entities": "Entités liées",
  "Related entities (generic relation \"related-to\")": "Entités liées (relation générique \"lié à\")",
  "Related groupings": "Groupements liés",
  "Related reports": "Rapports liés",
  "Related to this country": "Lié à ce pays",
  "Related to this organization": "Lié à cette organisation",
  "Related to this region": "Lié à cette région",
  "Relation": "Relation",
  "Relation type": "Type de relation",
  "Relations": "Relations",
  "Relations of the entity": "Relations de cette entité",
  "Relations to other entities": "Relations vers d'autres entités",
  "Relations to threats": "Relations vers des menaces",
  "Relationship": "Relation",
  "Relationship type": "Type de relation",
  "Relationship types": "Types de relation",
  "Relationships": "Relations",
  "Relative time": "Temps relatif",
  "Reliability": "Fiabilité",
  "Remote OpenCTI URL": "URL de la plateforme distante",
  "Remote OpenCTI configuration": "Configuration de la plateforme OpenCTI distante",
  "Remote OpenCTI stream ID": "ID du stream de la plateforme distante",
  "Remote OpenCTI token": "Token de la plateforme distante",
  "Remove": "Retirer",
  "Remove from the container": "Retirer de ce conteneur",
  "Remove from this entity": "Retirer de cette entité",
  "Remove from this object": "Retirer de cet objet",
  "Remove selected items": "Supprimer les éléments sélectionnés",
  "Renew": "Renouveler",
  "Replace": "Remplacer",
  "Report": "Report",
  "Report type": "Type de rapport",
  "Report types": "Types de rapport",
  "Reports": "Rapports",
  "Reports distribution": "Répartition des rapports",
  "Required permissions": "Permissions requises",
  "Rescan": "Rescanner",
  "Reset": "Réinitialiser",
  "Reset filters": "Réinitialiser les filtres",
  "Reset the connector state": "Réinitialiser l'état du connecteur",
  "Resource level": "Niveau de ressource",
  "Response type": "Type de réponse",
  "Retention policies": "Politiques de rétention",
  "Revoked": "Révoqué",
  "Rich editor": "Editeur enrichi",
  "Role": "Rôle",
  "Roles": "Rôles",
  "Rolling time": "Intervalle de requête",
  "Rolling time (in minutes)": "Intervalle de requête (en minutes)",
  "Rule entity rescan": "Rafraichissement des règles pour les entités",
  "Rule has been cleaned up on the existing data": "Cette règle a été purgée des données de la plateforme",
  "Rule rescan": "Rafraichissement des règles",
  "Rule rescan (engine is disabled)": "Rafraichissement des règles (moteur désactivé)",
  "Rules engine": "Moteur de règles",
  "Running": "Démarré",
  "STIX Version": "Version STIX",
  "STIX2 bundle": "Bundle STIX2",
  "STREAM": "Streaming",
  "SUBSCRIPTION_MANAGER": "Manager des souscriptions",
  "SYNC_MANAGER": "Manager de synchronisation",
  "Saturday": "UNDEFINED",
  "Save": "UNDEFINED",
  "Scope": "Périmètre",
  "Score": "Score",
  "Search": "Rechercher",
  "Search for a threat...": "Rechercher une menace...",
  "Search for an entity": "Rechercher une entité",
  "Search for multiple entities": "Rechercher plusieurs entités",
  "Secondary motivations": "Motivations secondaires",
  "Sector": "Secteur",
  "Sectors": "Secteurs",
  "Sectors and organizations": "Secteurs et organisations",
  "Select a relationship": "Sélectionner une relation",
  "Select all nodes": "Sélectionner tous les noeuds",
  "Select by entity type": "Sélectionner par type",
  "Select your file": "Selectionner votre fichier",
  "Selected connectors": "Connecteurs sélectionnés",
  "Selected entities": "Entités sélectionnées",
  "Selected rules": "Règles sélectionnées",
  "Sender": "Expéditeur",
  "Sender email address": "Adresse mail d'expédition",
  "Separator": "Séparateur",
  "Settings": "Paramètres",
  "Settings have been updated": "Les paramètres ont été mis à jour",
  "Severity": "Sévérité",
  "Share": "Partager",
  "Share with an organization": "Partager avec une organisation",
  "Sightings": "Détections",
  "Sightings distribution": "Répartition des détections",
  "Sign in": "S'identifier",
  "Signatures": "Signatures",
  "Simple export (just the entity)": "Export simple (seulement l'entité)",
  "Size": "Taille",
  "Sophistication": "Sophistication",
  "Sort by": "Trier par",
  "Source": "UNDEFINED",
  "Source name": "Nom de la source",
  "Standard STIX ID": "STIX ID standard",
  "Start": "Démarrer",
  "Start date": "Date de début",
  "Start time": "Début d'obs.",
  "Starting synchronization (empty = from start)": "Début de synchronisation (vide = début)",
  "State": "Etat",
  "Statistics": "Statistiques",
  "Status": "Statut",
  "Status templates": "Templates de statut",
  "Step": "Etape",
  "Stop": "Arrêter",
  "Stop time": "Fin d'obs.",
  "Stream ID": "ID du stream",
  "Street address": "Adresse postale",
  "Strong": "Fort",
  "Sub attack patterns": "Sous motifs d'attaque",
  "Submit a feedback": "Soumettre un commentaire",
  "Subregions": "Sous-régions",
  "Subscriptions & digests": "Souscriptions & résumés",
  "Subsectors": "Sous-secteurs",
  "Sunday": "UNDEFINED",
  "Synchronization": "Synchronisation",
  "Synthesis of knowledge": "Synthèse de la connaissance",
  "System": "Système",
  "Systems": "Systèmes",
  "TASK_MANAGER": "Manager des tâches",
  "TAXII collections": "Collections TAXII",
  "THEN": "ALORS",
  "TTPs": "TTPs",
  "TTPs knowledge": "Connaissance des TTPs",
  "TTPs of threats": "TTPs de menaces",
  "TTPs through time": "TTPs à travers le temps",
  "Table": "Tableau",
  "Table (top 10)": "Tableau (top 10)",
  "Tactics": "Tactiques",
  "Tactics matrix view": "Vue matrice de tactiques",
  "Take deletions into account": "Prendre en compte les suppressions",
  "Target": "UNDEFINED",
  "Targeted by this TTP": "Ciblées par cette TTP",
  "Targeted by this actor": "Ciblé par cet acteur",
  "Targeted by this intrusion set": "Ciblé par ce mode opératoire",
  "Targeted by this malware": "Ciblé par ce code",
  "Targeted countries (3 last months)": "Pays ciblés (3 derniers mois)",
  "Targeted entities": "Entités ciblées",
  "Targeted entity through time": "Ciblages d'entités à travers le temps",
  "Targeted entity types": "Types d'entités ciblées",
  "Targeted in this campaign": "Ciblé dans cette campagne",
  "Targeted in this incident": "Ciblé dans cet incident",
  "Targeting knowledge": "Connaissance du ciblage",
  "Targeting this country": "Ciblant ce pays",
  "Targeting this individual": "Ciblant cette individualne",
  "Targeting this organization": "Ciblant cette organisation",
  "Targeting this region": "Ciblant cette région",
  "Targeting this sector": "Ciblant ce secteur",
  "Targeting this vulnerability": "Ciblant cette vulnérabilité",
  "Targeting through time": "Ciblage à travers le temps",
  "Targeting types": "Types de ciblages",
  "Task end time": "Fin de la tâche",
  "Task start time": "Début de la tâche",
  "Tasks": "UNDEFINED",
  "Technical date": "Date technique",
  "Technical elements (indicators & observables)": "Eléments techniques (indicateurs & observables)",
  "Techniques": "Techniques",
  "Techniques matrix": "Matrice des techniques",
  "Text files": "Fichiers texte",
  "The CSV file has been generated with the parameters of the view and is ready for download.": "Le fichier CSV a été généré avec les paramètres de la vue et est prêt pour être téléchargé.",
  "The alias has been added": "L'alias a bien été ajouté",
  "The code is not correct": "Le code est incorrect",
  "The color must be written in hexadecimal. Example: #ff9800": "La couleur doit être écrite en hexadécimal. Exemple : #ff9800",
  "The connector has been cleared": "Le connecteur a été supprimé",
  "The connector state has been reset": "L'état du connecteur a été réinitialisé",
  "The importation of the file has been started": "L'importation du fichier a été lancée",
  "The min value cannot be greater than max value": "La valeur min ne peut pas être supérieure à la valeur max",
  "The minimum value cannot be greater than maximum value": "UNDEFINED",
  "The password has been updated": "Le mot de passe a été modifié",
  "The relations attached to selected entities will be copied to the merged entity.": "Les relations attachées aux entités sélectionnées seront copiées sur l'entité fusionnée.",
  "The rule has been disabled, clean-up launched...": "La règle a été déséactivée, purge lancée...",
  "The rule has been enabled, rescan of platform data launched...": "La règle a été activée, re-scan des données de la plateforme lancé...",
  "The value is too long": "La valeur est trop longue",
  "The value is too short": "La valeur est trop courte",
  "The value must be a date (yyyy-MM-dd)": "La valeur doit être une date (dd/mm/aaaaa)",
  "The value must be a datetime (yyyy-MM-dd hh:mm (a|p)m)": "La valeur doit être une date et un temps (dd/mm/aaaaa HH:mm)",
  "The value must be a datetime with seconds (yyyy-MM-dd hh:mm:ss (a|p)m)": "La valeur doit être une date et un temps avec des secondes (dd/mm/aaaaa HH:mm:ss)",
  "The value must be a number": "La valeur doit être un nombre",
  "The value must be an URL": "La valeur doit être une URL",
  "The value must be an email address": "La valeur doit être une adresse email",
  "The value must be between min and max value": "La valeur doit être comprise entre la valeur min et max",
  "The value must be between minimum and maximum value": "UNDEFINED",
  "The value must be greater than or equal to 0": "La valeur doit être supérieure ou égale à 0",
  "The value must be less than or equal to 100": "La valeur doit être inférieure ou égale à 100",
  "The values do not match": "Les valeurs ne correspondent pas",
  "Theme": "Thème",
  "This action will generate STIX patterns indicators from the selected observables.": "Cette action va générer des indicateurs STIX depuis les observables sélectionnés.",
  "This action will generate observables from the selected indicators.": "Cette action va générer des observables depuis les indicateurs sélectionnés.",
  "This configuration enables an entity to automatically construct an external reference from the uploaded file.": "Cette configuration permet à une entité de construire automatiquement une référence externe à partir du fichier téléchargé.",
  "This configuration enables the requirement of a reference message on an entity update.": "Cette configuration permet l'exigence d'un message de référence sur une mise à jour d'entité.",
  "This configuration hide a specific entity type across the entire platform.": "Cette configuration masque un type d'entité spécifique sur l'ensemble de la plateforme.",
  "This configuration is not available for this entity type": "Cette configuration n'est pas disponible pour ce type d'entité",
  "This connector is active": "Ce connecteur est actif",
  "This connector is disconnected": "Ce connecteur est déconnecté",
  "This feature is not available yet.": "Cette fonctionnalité n'est pas encore disponible.",
  "This field is required": "Ce champ est requis",
  "This field must be a number": "UNDEFINED",
  "This field must only contain alphanumeric chars, dashes and space": "Ce champ ne peut contenir que des caractères alphanumériques, des tirets et des espaces",
  "This individual is now a user": "Cette individualne est maintenant un utilisateur",
  "This individual is part of": "Cette individualne fait partie de",
  "This malware has been used": "Ce code a été utilisé",
  "This page is not found on this OpenCTI application.": "Cette page est introuvable sur cette application OpenCTI.",
  "This panel shows by default the latest created entities, use the search to find more.": "Ce panneau montre par défaut les dernières entités créées, utilisez la recherche pour en trouver plus.",
  "This relation is inferred": "Cette relation est inférée",
  "This report contains too many objects to be displayed as a graph. We are working on a new visualization which will allow large graph to be displayed in the future.": "Ce rapport contient trop d'objets pour être affiché comme un graphe. Nous travaillons sur une nouvelle visualisation qui permettra d'afficher de grands graphes à l'avenir.",
  "This rule has been applied on the existing data": "Cette règle a été appliquée sur les données de la plateforme",
  "This sector does not have any description.": "Ce secteur n'a aucune description.",
  "Threat actor": "Acteur",
  "Threat actor types": "Type d'acteur",
  "Threat actors": "Acteurs",
  "Threat hunting techniques": "Techniques de recherche de compromission",
  "Threats": "Menaces",
  "Threats targeting": "Ciblages de menaces",
  "Threats using this malware": "Menaces utilisant ce code",
  "Thursday": "UNDEFINED",
  "Ticks": "Marqueurs",
  "Time": "UNDEFINED",
  "Timeline": "Chronologie",
  "Title": "Titre",
  "To name": "Nom cible",
  "To type": "Type cible",
  "To use this feature, your platform administrator must enable the according manager in the config.": "Pour utiliser cette fonctionnalité, l'administrateur de votre plateforme doit activer la configuration correspondante.",
  "To use this feature, your platform administrator must enable the subscription manager in the config.": "Pour utiliser cette fonctionnalité, l'administrateur de votre plateforme doit activer le manager de souscriptions.",
  "Token": "UNDEFINED",
  "Too many objects": "Nombre trop important d'objets",
  "Tool": "Outil",
  "Tool types": "Types d'outil",
  "Tool usage": "Utilisation de cet outil",
  "Tool version": "Version de l'outil",
  "Tools": "Outils",
  "Tools versions": "Versions des outils",
  "Top 10 active entities (3 last months)": "Top 10 des entités actives (3 derniers mois)",
  "Top 10 threats targeting this entity": "Top 10 des menaces ciblant cette entité",
  "Top 10:": "Top 10 :",
  "Top Labels (3 last months)": "Top Labels (3 derniers mois)",
  "Total direct relations": "Nombre de relations directes",
  "Total entities": "Nombre d'entités",
  "Total indicators": "Nombre d'indicateurs",
  "Total notes": "Nombre de notes",
  "Total number of documents": "Nombre total de documents",
  "Total number of operations": "Nombre total d'opérations",
  "Total observables": "Nombre d'observables",
  "Total pending inserts": "Nombre d'insertions en attente",
  "Total processed messages": "Total de messages traités",
  "Total relations": "Nombre de relations",
  "Total relationships": "Nombre de relations",
  "Total reports": "Nombre de rapports",
  "Total workspaces": "Nombre d'espaces de travail",
  "Triggering on": "Se déclenche sur",
  "Triggers": "UNDEFINED",
  "Triggers and digests": "Déclencheurs et résumés",
  "Tuesday": "UNDEFINED",
  "Turn to user": "Transformer en utilisateur",
  "Two-factor authentication": "Authentification double facteur",
  "Type": "Type",
  "Type the code generated in your application": "Taper le code généré dans votre application",
  "Types": "UNDEFINED",
  "Types of the targeting": "Types de ciblage",
  "Types of the targets": "Types de cibles",
  "URL": "URL",
  "Unauthorized action, please refresh your browser": "Action non autorisée, merci de rafraichir votre navigateur",
  "Unfix the nodes and re-apply forces": "Libérer les noeuds et ré-appliquer les forces",
  "Unique identifier": "Identifiant unique",
  "Unknown": "Inconnu",
  "Unsupported": "Non supporté",
  "Update": "Modifier",
  "Update a TAXII collection": "Modifier une collection TAXII",
  "Update a campaign": "Modifier une campagne",
  "Update a case incident": "Mettre à jour un incident",
  "Update a channel": "Modifier un canal",
  "Update a city": "Modifier une ville",
  "Update a country": "Modifier un pays",
  "Update a course of action": "Modifier une conduite à suivre",
  "Update a data component": "Modifier un composant de données",
  "Update a data source": "Modifier une source de données",
  "Update a feed": "Modifier un flux",
  "Update a feedback": "Mettre à jour un commentaire",
  "Update a group": "Modifier un groupe",
  "Update a grouping": "Modifier un groupement",
  "Update a individual": "Modifier un individu",
  "Update a kill chain phase": "Modifier une étape de kill chain",
  "Update a label": "Modifier un label",
  "Update a live stream": "Modifier un stream live",
  "Update a malware": "Modifier un code malveillant",
  "Update a marking definition": "Modifier un marquage",
  "Update a narrative": "Modifier un narratif",
  "Update a note": "Modifier une note",
  "Update a position": "Modifier une position",
  "Update a region": "Modifier une région",
  "Update a relationship": "Modifier une relation",
  "Update a report": "Modifier un rapport",
  "Update a retention policy": "Mettre à jour une règle de rétention",
  "Update a role": "Modifier un rôle",
  "Update a sector": "Modifier un secteur",
  "Update a sighting": "Modifier une détection",
  "Update a status": "Mettre à jour un statut",
  "Update a status template": "Modifier un template de statut",
  "Update a subscription": "Modifier une souscription",
  "Update a synchronizer": "Modifier un synchroniseur",
  "Update a system": "Modifier un système",
  "Update a threat actor": "Modifier un acteur",
  "Update a tool": "Modifier un outil",
  "Update a trigger": "Modifier un déclencheur",
  "Update a user": "Modifier un utilisateur",
  "Update a vulnerability": "Modifier une vulnérabilité",
  "Update a widget": "Modifier un widget",
  "Update a workspace": "Modifier un espace de travail",
  "Update an area": "Modifier une zone",
  "Update an artifact": "Modifier un artefact",
  "Update an attack pattern": "Modifier un motif d'attaque",
  "Update an attribute": "Modifier un attribut",
  "Update an country": "UNDEFINED",
  "Update an entity": "Modifier une entité",
  "Update an event": "Modifier un événement",
  "Update an external reference": "Modifier une référence externe",
  "Update an incident": "Modifier un incident",
  "Update an indicator": "Modifier un indicateur",
  "Update an infrastructure": "Modifier une infrastructure",
  "Update an intrusion set": "Modifier un mode opératoire",
  "Update an observable": "Modifier un observable",
  "Update an observed data": "Modifier une donnée observée",
  "Update an organization": "Modifier une organisation",
  "Update and complete": "Modifier et compléter",
  "Update entities": "Modifier des entités",
  "Update opinion": "Modifier l'opinion",
  "Updated the": "Mis à jour le",
  "Uploaded files": "Fichiers uploadés",
  "Usage": "Utilisation",
  "Use": "Utiliser",
  "Use 2FA authentication": "Utiliser l'authentification à double facteur",
  "Used TTPs": "TTPs utilisées",
  "Used by this actor": "Utilisé par cet acteur",
  "Used by this intrusion set": "Utilisé par ce mode opératoire",
  "Used by this malware": "Utilisé par ce code",
  "Used in this campaign": "Utilisé dans cette campagne",
  "Used in this incident": "Utilisé dans cet incident",
  "Used tools": "Outils utilisés",
  "User interface": "Interface utilisateur",
  "User responsible for data creation (empty = System)": "Utilisateur responsable de la création des données (vide = System)",
  "User will be created with default groups.": "L'utilisateur sera créé avec les groupes par défaut.",
  "Users": "Utilisateurs",
  "Using this TTP": "Utilisant cette TTP",
  "Using this tool": "Utilisant cet outil",
  "Valid from": "Valide depuis",
  "Valid until": "Valide jusqu'à",
  "Validate": "Valider",
  "Validate and send for import": "Valider et envoyer pour import",
  "Validate this workbench": "Valider cet espace de travail",
  "Value": "Valeur",
  "Values": "Valeurs",
  "Variants": "Variantes",
  "Variants of this malware": "Variantes de ce code",
  "Vendor": "Editeur",
  "Verify": "Vérifier",
  "Verify SSL certificate": "Vérifier le certificat SSL",
  "Versions": "Versions",
  "Vertical Bar": "Barre verticale",
  "Victimology": "Victimologie",
  "Victimology (countries)": "Victimologie (pays)",
  "Victimology (regions)": "Victimologie (régions)",
  "Victimology (sectors)": "Victimologie (secteurs)",
  "View": "Aperçu",
  "View the item": "Voir l'object",
  "Visualization": "Visualisation",
  "Vulnerabilities": "Vulnérabilités",
  "Vulnerability": "Vulnérabilité",
  "Vulnerability usage": "Usage de cette vulnérabilité",
  "Webhook": "UNDEFINED",
  "Wednesday": "UNDEFINED",
  "Week day": "UNDEFINED",
  "When you specified the platform organization, data without any organization restriction will be accessible only for users that are part of the platform one": "Lorsque vous avez spécifié l'organisation de la plateforme, les données sans aucune restriction d'organisation ne seront accessibles qu'aux utilisateurs faisant partie de celle ci",
  "Widget": "Widget",
  "Windows scheduled tasks": "Tâches planifiées Windows",
  "Windows services": "Services Windows",
  "Work end time": "Fin de l'éxécution",
  "Work start time": "Début de l'exécution",
  "Workers statistics": "Statistiques des workers",
  "Workflow": "Flux de travail",
  "Workflow of": "Flux de travail de",
  "Workflows": "Flux de travail",
  "Works": "Exécutions",
  "Workspace": "Espace de travail",
  "Workspaces": "Espaces de travail",
  "Write": "Ecrire",
  "Write a note": "Ecrire une note",
  "Write operations": "Opérations d'écriture",
  "Write something awesome...": "Ecrivez quelque chose de génial...",
  "X509 Certificates": "Certificats X509",
  "Year": "Année",
  "Yes": "Oui",
  "You are not allowed to do this.": "Vous n'ête pas autorisés à faire cette action.",
  "You do not have any access to the knowledge of this OpenCTI instance.": "Vous n'avez aucun accès à la connaissance de cette instance OpenCTI.",
  "You have no subscription for the moment.": "Vous n'avez aucune souscription pour le moment.",
  "You have successfully logged out.": "Vous avez bien été déconnecté.",
  "You must be logged in to do this.": "Vous devez être authentifié pour faire cette action.",
  "You must provide at least one external reference for this type of entity": "Vous devez fournir au moins une référence externe pour ce type d'entité",
  "You need to activate a two-factor authentication. Please type the code generated in your application.": "Vous devez activer une authentification à deux facteurs. Veuillez saisir le code généré dans votre application.",
  "You need to validate your two-factor authentication. Please type the code generated in your application.": "Vous devez valider votre authentification à deux facteurs. Veuillez saisir le code généré dans votre application.",
  "You're targeting more than 1000 entities with this background task, be sure of what you're doing!": "Vous ciblez plus de 1000 entités avec cette tâche de fond, soyez sûrs de ce que vous faites !",
  "_": "UNDEFINED",
  "added a note": "a ajouté une note",
  "day": "UNDEFINED",
  "entities": "entités",
  "entity_Administrative-Area": "Zone",
  "entity_All": "Toutes les entités",
  "entity_Analysis": "Analyses",
  "entity_Arsenal": "Arsenal",
  "entity_Artifact": "Artefact",
  "entity_Attack-Pattern": "Motif d'attaque",
  "entity_Autonomous-System": "Système autonome",
  "entity_Bank-Account": "Compte bancaire",
  "entity_Campaign": "Campagne",
  "entity_Case": "Case",
  "entity_Case-Incident": "Réponse aux incidents",
  "entity_Case-Rfi": "Demande d'information",
  "entity_Case-Rft": "Demande de retrait",
  "entity_Channel": "Canal",
  "entity_City": "Ville",
  "entity_Country": "Pays",
  "entity_Course-Of-Action": "Conduite à suivre",
  "entity_Cryptocurrency-Wallet": "Wallet de cryptomonnaie",
  "entity_Cryptographic-Key": "Clé cryptographique",
  "entity_Data-Component": "Composant de données",
  "entity_Data-Source": "Source de données",
  "entity_Directory": "Dossier",
  "entity_Domain-Name": "Nom de domaine",
  "entity_Email-Addr": "Adresse email",
  "entity_Email-Message": "Mail",
  "entity_Email-Mime-Part-Type": "Mail - Partie MIME",
  "entity_Entities": "Entité",
  "entity_Event": "Evénement",
  "entity_Events": "Evènements",
  "entity_External-Reference": "Référence externe",
  "entity_Feedback": "Commentaire",
  "entity_Grouping": "Groupement",
  "entity_Hostname": "Nom d'hôte",
  "entity_IPv4-Addr": "Adresse IPv4",
  "entity_IPv6-Addr": "Adresse IPv6",
  "entity_Identity": "Identité",
  "entity_Incident": "Incident",
  "entity_Indicator": "Indicateur",
  "entity_Individual": "Individu",
  "entity_Infrastructure": "Infrastructure",
  "entity_Intrusion-Set": "Mode opératoire",
  "entity_Ipv4-Addr": "Adresse IPv4",
  "entity_Ipv6-Addr": "Adresse IPv6",
  "entity_Label": "Label",
  "entity_Language": "Langue",
  "entity_Location": "Emplacement",
  "entity_Locations": "Localisations",
  "entity_Mac-Addr": "Adresse MAC",
  "entity_Malware": "Code malveillant",
  "entity_Marking-Definition": "Marquage",
  "entity_Media-Content": "Contenu média",
  "entity_Mutex": "Mutex",
  "entity_Narrative": "Narratif",
  "entity_Network-Traffic": "Trafic réseau",
  "entity_Note": "Note",
  "entity_Observable": "Observable",
  "entity_Observations": "Observations",
  "entity_Observed-Data": "Donnée observée",
  "entity_Opinion": "Opinion",
  "entity_Organization": "Organisation",
  "entity_Payment-Card": "Carte de paiement",
  "entity_Phone-Number": "Numéro de téléphone",
  "entity_Position": "Position",
  "entity_Process": "Processus",
  "entity_Region": "Région",
  "entity_Relationship": "Relation",
  "entity_Report": "Rapport",
  "entity_Sector": "Secteur",
  "entity_Sighting": "Détection",
  "entity_Software": "Logiciel",
  "entity_Stix-Core-Objects": "Entités et observables",
  "entity_Stix-Core-Relationship": "Relations",
  "entity_Stix-Cyber-Observable": "Observable",
  "entity_Stix-Cyber-Observables": "Observables",
  "entity_Stix-Domain-Object": "Entité",
  "entity_Stix-Domain-Objects": "Entités",
  "entity_StixFile": "Fichier",
  "entity_Stixfile": "Fichier",
  "entity_System": "Système",
  "entity_Techniques": "Techniques",
  "entity_Text": "Texte",
  "entity_Threat-Actor": "Acteur",
  "entity_Threats": "Menaces",
  "entity_Tool": "Outil",
  "entity_Url": "URL",
  "entity_User-Account": "Compte utilisateur",
  "entity_User-Agent": "User agent",
  "entity_Vulnerability": "Vulnérabilité",
  "entity_Windows-Registry-Key": "Clé de reg. Windows",
  "entity_Windows-Registry-Value-Type": "Clé de reg. Windows - Valeur",
  "entity_X509-Certificate": "Certificat X509",
  "filter_${filterKey}": "UNDEFINED",
  "filter_assigneeTo": "Référent",
  "filter_basedOn": "Basé sur un observable",
  "filter_containedBy": "Conteneur",
  "filter_createdBy": "Auteur",
  "filter_createdBy_not_eq": "SANS Auteur",
  "filter_elementId": "Entité liée",
  "filter_fromId": "Entité source",
  "filter_fromTypes": "Type source",
  "filter_killChainPhase": "Phase de kill chain",
  "filter_labelledBy": "Label",
  "filter_labelledBy_not_eq": "SANS Label",
  "filter_markedBy": "Marquage",
  "filter_markedBy_not_eq": "SANS Marquage",
  "filter_objectContains": "Contient",
  "filter_sightedBy": "Détecté par/dans",
  "filter_sightedBy_not_eq": "SANS Détecté par/dans",
  "filter_toCreatedAt_end_date": "Ingéré avant",
  "filter_toCreatedAt_start_date": "Ingéré après",
  "filter_toId": "Entité cible",
  "filter_toSightingId": "Détect dans/en",
  "filter_toTypes": "Type destination",
  "hour": "UNDEFINED",
  "name": "Nom",
  "obsContent": "Contenu",
  "of": "UNDEFINED",
  "on": "le",
  "organization": "Organisation structurée",
  "relationship_All": "Tous les types de relation",
  "reliability_A": "A - Completely reliable",
  "reliability_B": "B - Usually reliable",
  "reliability_C": "C - Fairly reliable",
  "reliability_D": "D - Not usually reliable",
  "reliability_E": "E - Unreliable",
  "reliability_F": "F - Reliability cannot be judged",
  "selected": "sélectionné(s)",
  "to exclude items": "pour exclure des items",
  "unknown": "inconnu",
  "week": "UNDEFINED"
}