export default {
  "2FA": "2FA",
  "2FA state": "二要素認証の状態",
  "AND": "UNDEFINED",
  "API access": "APIアクセス",
  "API key": "APIキー",
  "About": "OpenCTIについて",
  "Abstract": "要旨",
  "Accent color ": "アクセントカラー",
  "Access stream directly in your browser": "UNDEFINED",
  "Accesses": "アクセス",
  "Action type": "アクションタイプ",
  "Active": "アクティブ",
  "Activities": "アクティビティ",
  "Activity": "アクティビティ",
  "Add": "追加",
  "Add Tick": "マーカーを追加",
  "Add a widget": "ウィジェットを追加",
  "Add an action": "アクションを追加",
  "Add an entity to this container": "ここにエンティティを追加する",
  "Add and complete": "追加して完成",
  "Add attack patterns": "攻撃パターンを追加",
  "Add context": "コンテキストを追加",
  "Add courses of action": "行動指針を追加",
  "Add data components": "データコンポーネントの追加",
  "Add data source": "データソースの追加",
  "Add entities": "エンティティの追加",
  "Add external references": "外部参照を追加",
  "Add locations": "ロケーションの追加",
  "Add new labels": "新しいラベルを作成",
  "Add notes": "ノートを追加",
  "Add observable": "観測結果の追加",
  "Add observables": "観測結果の追加",
  "Add sub attack patterns": "下位攻撃パターンを追加",
  "Add subsectors": "下位セクターを追加",
  "Additional mandatory attributes": "追加の必須属性",
  "Admin": "管理者",
  "Advanced search": "詳細検索",
  "Affected software": "影響を受けるソフトウェア",
  "Affecting this sector": "このセクターに影響があるもの",
  "Alias": "別名",
  "Aliases": "UNDEFINED",
  "Aliases separated by commas": "カンマ区切りの別名",
  "All": "すべて",
  "All confidence levels": "すべての信頼水準",
  "All entities": "すべてのエンティティ",
  "All observables": "観測結果",
  "All reports": "レポート",
  "All threats": "すべての脅威",
  "All types of entity": "すべての種類のエンティティ",
  "All types of relationship": "全てのリレーションシップの種別",
  "All years": "すべての年",
  "Allowed markings": "許可されるマーキング",
  "Already in plat.": "すでにプラットフォームに存在します",
  "Also delete these elements": "これらの要素も削除します",
  "An unknown error has occurred!  Please try again later.": "不明なエラーが発生しました。後でもう一度お試しください。",
  "Analysis": "分析",
  "Analyst workbenches": "アナリストのワークスペース",
  "Apply on": "適用",
  "Applying this rule on the existing data": "既存のデータにルールを適用しています",
  "Architecture execution env.": "CPUアーキテクチャ",
  "Area": "領域",
  "Areas": "领域",
  "Arsenal": "武器庫",
  "Artifacts": "アーティファクト",
  "As it happens": "5分毎",
  "Assignee(s)": "参照",
  "Assignees": "譲受人",
  "Associated file": "関連ファイル",
  "Attack pattern": "攻撃パターン",
  "Attack pattern usage": "アタックパターンの利用",
  "Attack patterns": "攻撃パターン",
  "Attributed to this actor": "この脅威アクターに帰属するもの",
  "Attributed to this campaign": "このキャンペーンに帰属するもの",
  "Attributed to this country": "この国に帰属するもの",
  "Attributed to this individual": "この個人に帰属するもの",
  "Attributed to this intrusion set": "この侵入セットに帰属するもの",
  "Attributed to this organization": "この組織に帰属するもの",
  "Attributed to this region": "この地域に帰属するもの",
  "Attribution": "アトリビューション",
  "Authentication": "認証",
  "Authentication strategies": "認証方法",
  "Author": "著者",
  "Auto new markings": "新しいマーキングの自動化",
  "Automatic": "自動",
  "Automatic references at file upload": "ファイルアップロード時の自動参照",
  "Automatic trigger": "自動起動",
  "Automatically authorize this group to new marking definition": "このグループに新しいデータマーキングを自動的に適用する",
  "Autonomous system": "自律システム (AS)",
  "Autonomous systems": "自律システム(AS)",
  "Averages of context relations": "コンテキストリレーションの平均",
  "Avoid dependencies resolution": "依存関係の解消を避ける",
  "Back": "戻る",
  "Background color": "背景色",
  "Background tasks": "バックグラウンドタスク",
  "Bad login or password": "ユーザー名またはパスワードが間違っています。",
  "Base URL": "ベースURL",
  "Based on": "根拠",
  "Basic information": "基本情報",
  "Belonging to this organization": "この組織に属するもの",
  "Browse the link": "リンクを閲覧する",
  "Bulk search": "一括検索",
  "Bundle content": "バンドルの内容",
  "Bundle details": "バンドルの詳細",
  "Bundles processed": "処理されたバンドル",
  "CRITICAL": "UNDEFINED",
  "CSIRT": "CSIRT",
  "CSV file": "CSVファイル",
  "Campaign": "キャンペーン",
  "Campaigns": "キャンペーン",
  "Cancel": "キャンセル",
  "Capabilities": "能力",
  "Cards view": "カード表示",
  "Cascade delete": "カスケード削除",
  "Case priority": "优先事项",
  "Case severity": "严重程度",
  "Category": "カテゴリー",
  "Channel": "チャネル",
  "Channel type": "チャネルタイプ",
  "Channel types": "チャネルタイプ",
  "Channels": "チャネル",
  "Cities": "都市",
  "City": "都市",
  "Cleaning up this rule on the existing data": "既存データからルールを削除しています",
  "Clear": "クリア",
  "Clear all works": "全ての作業を削除",
  "Clear filters": "フィルタのクリア",
  "Clear this connector": "コネクタを削除する",
  "Close": "閉じる",
  "Cloud Control Plane": "クラウドコントロールプレーン",
  "Collapse": "崩壊",
  "Color": "色",
  "Column": "カラム",
  "Columns": "カラム",
  "Commit message": "コミットメッセージ",
  "Commit message when updating data from the UI.": "UIからデータを更新したときのコミットメッセージ。",
  "Commit messages": "コミットメッセージ",
  "Compare": "比較",
  "Completed tasks": "完了したタスク",
  "Completed works": "完了した作業",
  "Confidence": "信頼度",
  "Confidence level": "信頼水準",
  "Configuration": "配置",
  "Confirmation": "確認",
  "Confirmation required": "確認が必要です",
  "Connected": "接続中",
  "Connected workers": "接続中のワーカー",
  "Connection successfully verified": "接続が正常に検証されました",
  "Connector": "コネクタ",
  "Connectors": "コネクタ",
  "Connectors & workers": "コネクタとワーカー",
  "Constituent": "構成要素",
  "Contact information": "お問い合わせ先",
  "Containers": "コンテナ",
  "Containers (reports, notes & opinions)": "コンテナ（レポート、ノート、オピニオン）",
  "Content": "内容",
  "Context relations": "コンテキストとのリレーション",
  "Continue": "続行",
  "Copied to clipboard": "クリップボードにコピーしました",
  "Copy": "写し",
  "Copy disabled: too many selected elements (maximum number of elements for a copy: ": "コピー無効:選択した要素が多すぎます(コピーの要素の最大数:",
  "Copy/paste text content": "コンテンツのコピー/ペースト",
  "Correlate": "相関",
  "Correlation view": "相関の表示",
  "Count": "合計",
  "Countries": "国",
  "Country": "国",
  "Course of action": "行動指針",
  "Courses of action": "行動指針",
  "Courses of action view": "行動指針の表示",
  "Create": "作成",
  "Create a TAXII collection": "TAXIIコレクションを作成",
  "Create a campaign": "キャンペーンを作成",
  "Create a case incident": "ケース インシデントの作成",
  "Create a channel": "チャネルを作成",
  "Create a city": "都市を作成",
  "Create a country": "国を作成",
  "Create a course of action": "行動指針を作成",
  "Create a data component": "データコンポーネントの作成",
  "Create a data source": "データ ソースを作成する",
  "Create a feed": "フィードを作成",
  "Create a feedback": "フィードバックを作成する",
  "Create a file": "ファイルを作成",
  "Create a group": "グループを作成",
  "Create a grouping": "グルーピングを作成",
  "Create a individual": "個人を作成",
  "Create a kill chain phase": "キルチェーンフェーズを作成",
  "Create a label": "ラベルを作成",
  "Create a live stream": "ライブストリームを作成",
  "Create a live trigger": "UNDEFINED",
  "Create a malware": "マルウェアを作成",
  "Create a marking definition": "データマーキングを作成",
  "Create a narrative": "ナラティブを作成",
  "Create a nested relationship": "階層化されたリレーションシップを作成する",
  "Create a note": "ノートを作成",
  "Create a opinions": "UNDEFINED",
  "Create a position": "職位の作成",
  "Create a region": "地域を作成",
  "Create a regular digest": "UNDEFINED",
  "Create a relationship": "リレーションシップを作成",
  "Create a report": "レポートを作成",
  "Create a retention policy": "保持ポリシーの作成",
  "Create a role": "ロールを作成",
  "Create a sector": "セクターを作成",
  "Create a sighting": "目撃情報を作成",
  "Create a status": "ステータスの作成",
  "Create a status template": "状態テンプレートを作成する",
  "Create a subscription": "サブスクリプションを作成",
  "Create a synchronizer": "同期処理を作成",
  "Create a system": "システムを作成",
  "Create a threat actor": "脅威アクターを作成",
  "Create a tool": "ツールを作成",
  "Create a user": "ユーザーを作成",
  "Create a vocabulary": "UNDEFINED",
  "Create a vulnerability": "脆弱性を作成",
  "Create a workbench": "ワークスペースを作成する",
  "Create a workspace": "ワークスペースを作成",
  "Create an area": "領域を作成する",
  "Create an artifact": "アーティファクトを作成",
  "Create an attack pattern": "攻撃パターンを作成",
  "Create an attribute": "属性を作成",
  "Create an entity": "エンティティを作成",
  "Create an event": "イベントを作成",
  "Create an external reference": "外部参照を作成",
  "Create an incident": "インシデントを作成",
  "Create an indicator": "インジケータを作成",
  "Create an indicator from this observable": "観測結果からインジケータを作成",
  "Create an infrastructure": "インフラストラクチャを作成",
  "Create an intrusion set": "侵入セットを作成",
  "Create an observable": "観測結果を作成",
  "Create an observed data": "観測データを作成",
  "Create an opinion": "意見を作成する",
  "Create an organization": "組織を作成",
  "Create external reference at upload": "UNDEFINED",
  "Created entities": "作成されたエンティティ",
  "Created the": "作成日時",
  "Creation": "UNDEFINED",
  "Creation date": "作成日",
  "Creation date (in this platform)": "プラットフォーム上での作成日",
  "Creator": "作成者",
  "Creators": "クリエーター",
  "Current password": "現在のパスワード",
  "Current state": "現在の状態",
  "Custom dashboard": "カスタムダッシュボード",
  "Custom dashboards": "カスタムダッシュボード",
  "Dark": "ダークテーマ",
  "Dark (with background)": "ダークテーマ (背景有り)",
  "Dark (without background)": "ダークテーマ (背景無し)",
  "Dark theme": "ダークテーマ",
  "Dashboard": "ダッシュボード",
  "Dashboard settings": "ダッシュボードの設定",
  "Data": "データ",
  "Data component": "データコンポーネント",
  "Data components": "データコンポーネント",
  "Data curation": "データ管理",
  "Data import": "データインポート",
  "Data import and analyst workbenches": "UNDEFINED",
  "Data sharing": "データ共有",
  "Data source": "データソース",
  "Data sources": "データソース",
  "Data type": "データ型",
  "Date": "日付",
  "Date reference": "参照日時",
  "Default": "デフォルト",
  "Default hidden entity types": "UNDEFINED",
  "Default mandatory attributes": "デフォルトの必須属性",
  "Default membership": "既定のメンバーシップ",
  "Default value": "デフォルト値",
  "Definition": "定義",
  "Delete": "削除",
  "Delete the element if no other containers contain it": "他のコンテナに要素が含まれていない場合は、要素を削除します",
  "Delete this file": "ファイルの削除",
  "Delete this workbench": "このワークスペースを削除",
  "Deletion": "UNDEFINED",
  "Demo credentials": "デモ用の認証情報",
  "Dependencies": "依存関係",
  "Description": "説明",
  "Details": "詳細",
  "Digest with multiple notifications": "UNDEFINED",
  "Direct Update": "UNDEFINED",
  "Direct relations creations": "直接的なリレーションの作成",
  "Direct targeting of this country": "この国家を直接的に標的にしている",
  "Direct targeting of this region": "この地域を直接的に標的にしている",
  "Direct targeting of this sector": "このセクターを直接的に標的にしている",
  "Directories": "ディレクトリ",
  "Directory": "ディレクトリ",
  "Disable": "無効化",
  "Disable 3D mode": "3D表示をやめる",
  "Disable forces": "強制モードをやめる",
  "Disable tree horizontal mode": "水平ツリー表示をやめる",
  "Disable tree vertical mode": "垂直ツリー表示をやめる",
  "Disable two-factor authentication": "二要素認証を無効にする",
  "Disabled": "無効",
  "Disconnected": "切断中",
  "Display as": "表示: ",
  "Display global knowledge with filters and criteria.": "フィルターと条件を使用してグローバルな知識を表示します。",
  "Display notes": "ノートを表示",
  "Display specific knowledge using relationships and filters.": "関係とフィルターを使用して特定の知識を表示します。",
  "Display time range selector": "時間範囲選択ツールを表示",
  "Distribution": "分布",
  "Distribution of entities": "エンティティの分布",
  "Distribution of opinions": "オピニオンの分布",
  "Distribution of relations": "リレーションの分布",
  "Distribution of relations (including inferred)": "リレーション(推論を含む)の分布",
  "Distribution of sources": "ソースの分布",
  "Distribution:": "分布:",
  "Do you want to browse this external link?": "この外部リンクを閲覧しますか？",
  "Do you want to clear the works of this connector?": "このコネクタの情報を削除しますか？",
  "Do you want to create a STIX Indicator from this observable?": "この観測結果からインジケータを作成しますか？",
  "Do you want to delete these entities?": "このエンティティを削除しますか？",
  "Do you want to delete this area?": "この領域を削除しますか？",
  "Do you want to delete this attack pattern?": "この攻撃パターンを削除しますか？",
  "Do you want to delete this attribute?": "この属性を削除しますか？",
  "Do you want to delete this campaign?": "このキャンペーンを削除しますか？",
  "Do you want to delete this case incident ?": "このケース インシデントを削除しますか?",
  "Do you want to delete this city?": "この都市を削除しますか？",
  "Do you want to delete this country?": "この国を削除しますか？",
  "Do you want to delete this course of action?": "この行動指針を削除しますか？",
  "Do you want to delete this data component?": "このデータコンポーネントを削除しますか?",
  "Do you want to delete this data source?": "このデータ ソースを削除しますか?",
  "Do you want to delete this entity?": "このエンティティを削除しますか？",
  "Do you want to delete this external reference?": "この外部参照を削除しますか？",
  "Do you want to delete this feed?": "このフィードを削除しますか？",
  "Do you want to delete this feedback ?": "このフィードバックを削除しますか?",
  "Do you want to delete this file?": "このファイルを削除しますか？",
  "Do you want to delete this group?": "このグループを削除しますか？",
  "Do you want to delete this incident?": "このインシデントを削除しますか？",
  "Do you want to delete this indicator?": "このインジケータを削除しますか？",
  "Do you want to delete this individual?": "この個人を削除しますか？",
  "Do you want to delete this intrusion set?": "この侵入セットを削除しますか？",
  "Do you want to delete this kill chain phase?": "このキルチェーンフェーズを削除しますか？",
  "Do you want to delete this label?": "このラベルを削除しますか？",
  "Do you want to delete this live stream?": "このライブストリームを削除しますか？",
  "Do you want to delete this malware?": "このマルウェアを削除しますか？",
  "Do you want to delete this marking definition?": "このデータマーキングを削除しますか？",
  "Do you want to delete this note?": "このノートを削除しますか？",
  "Do you want to delete this observable?": "この観測結果を削除しますか？",
  "Do you want to delete this observed data?": "この観測データを削除しますか？",
  "Do you want to delete this organization?": "この組織を削除しますか？",
  "Do you want to delete this region?": "この地域を削除しますか？",
  "Do you want to delete this relation?": "この関連を削除しますか？",
  "Do you want to delete this report?": "このレポートを削除しますか？",
  "Do you want to delete this role?": "このロールを削除しますか？",
  "Do you want to delete this sector?": "このセクターを削除しますか？",
  "Do you want to delete this sighting?": "この目撃情報を削除しますか？",
  "Do you want to delete this status template?": "このステータステンプレートを削除しますか?",
  "Do you want to delete this synchronizer?": "この同期処理を削除しますか？",
  "Do you want to delete this system?": "このシステムを削除しますか？",
  "Do you want to delete this threat actor?": "この脅威アクターを削除しますか？",
  "Do you want to delete this tool?": "このツールを削除しますか？",
  "Do you want to delete this user?": "このユーザーを削除しますか？",
  "Do you want to delete this vulnerability?": "この脆弱性を削除しますか？",
  "Do you want to delete this widget?": "このウィジェットを削除しますか？",
  "Do you want to delete this workbench?": "このワークスペースを削除しますか?",
  "Do you want to delete this workspace?": "このワークスペースを削除しますか？",
  "Do you want to disable this rule?": "このルールを無効にしますか？",
  "Do you want to enable this rule?": "このルールを有効にしますか？",
  "Do you want to kill all the sessions of this user?": "このユーザーのセッションをすべて削除しますか？",
  "Do you want to kill this session?": "このセッションを削除しますか？",
  "Do you want to remove the entity from this container?": "このコンテナからエンティティを削除しますか？",
  "Do you want to remove the entity from this report?": "レポートからこのエンティティを削除しますか？",
  "Do you want to remove the indicator from this observable?": "この観測結果からインジケータを削除しますか？",
  "Do you want to remove the observable from this indicator?": "このインジケータから観測結果を削除しますか？",
  "Do you want to remove these elements from this investigation?": "調査内容からこれらの要素を削除しますか？",
  "Do you want to remove these elements from this report?": "レポートからこれらの要素を削除しますか？",
  "Do you want to remove this external reference?": "この外部参照を削除しますか？",
  "Do you want to remove this job?": "このジョブを削除しますか？",
  "Do you want to remove this note?": "このノートを削除しますか？",
  "Do you want to remove this object?": "このオブジェクトを削除しますか?",
  "Do you want to remove this opinion?": "このオピニオンを削除しますか？",
  "Do you want to remove this report?": "このレポートを削除しますか？",
  "Do you want to remove this status?": "このステータスを削除しますか?",
  "Do you want to reset the state of this connector?": "このコネクタの状態をリセットしますか？",
  "Do you want to start this synchronizer?": "この同期処理を開始しますか？",
  "Do you want to stop this synchronizer?": "この同期処理を停止しますか？",
  "Domain": "ドメイン",
  "Domain names": "ドメイン名",
  "Donut": "ドーナツ",
  "Donut chart": "ドーナツチャート",
  "Download": "ダウンロード",
  "Download this file": "ファイルのダウンロード",
  "EXPIRATION_SCHEDULER": "有効期限スケジューラ",
  "EXTERNAL_IMPORT": "データインポート",
  "Each tick value must be between min and max value": "各マーカー値は最小値と最大値の間にある必要があります",
  "Edit the selected item": "選択したアイテムを編集する",
  "Elasticsearch": "Elasticsearch",
  "Element will be rescan with all compatible activated rules": "要素はすべての互換性のある有効なルールで再スキャンされます",
  "Elements successfully copied": "要素が正常にコピーされました",
  "Email": "Eメール",
  "Email address": "Eメールアドレス",
  "Email addresses": "Eメールアドレス",
  "Email subject": "Eメールの件名",
  "Emails": "Eメール",
  "Enable": "有効化",
  "Enable 3D mode": "3D表示にする",
  "Enable commit messages": "コミットメッセージの有効化",
  "Enable forces": "強制モードにする",
  "Enable this feature": "UNDEFINED",
  "Enable tree mode": "ツリー表示にする",
  "Enable two-factor authentication": "二要素認証を有効にする",
  "Enabled": "有効",
  "Enabled import connectors": "有効なインポート用コネクタ",
  "Enabled the ": "有効化: ",
  "End date": "終了日",
  "Enforce reference": "参照を強制する",
  "Enforce reference on entity type": "エンティティ タイプの参照を強制する",
  "Enforce references": "UNDEFINED",
  "Enforce two-factor authentication": "二要素認証を強制する",
  "Enrich": "エンリッチ",
  "Enrichment": "エンリッチメント",
  "Enrichment connectors": "エンリッチ用コネクタ",
  "Entities": "エンティティ",
  "Entities distribution": "エンティティの分布",
  "Entities view": "エンティティの表示",
  "Entity": "エンティティ",
  "Entity aliases": "エンティティの別名",
  "Entity details": "エンティティの詳細",
  "Entity enrichment": "エンティティのエンリッチメント",
  "Entity settings": "エンティティ設定",
  "Entity type": "エンティティタイプ",
  "Entity types": "エンティティ種別",
  "Entity usage": "エンティティの利用",
  "Error": "エラー",
  "Event types": "イベント種別",
  "Events": "イベント",
  "Every 1 hour": "1時間毎",
  "Every 24 hours": "24時間毎",
  "Every month": "毎月",
  "Every week": "毎週",
  "Everything": "全ての項目",
  "Evidences": "エビデンス",
  "Evolution": "発展",
  "Example": "例",
  "Expand": "拡張",
  "Expand elements": "要素を拡張する",
  "Explanation": "説明",
  "Explore": "探索",
  "Explore the attack campaigns of the dataset through time and involved entities.": "攻撃キャンペーンを時間とエンティティから探す。",
  "Explore the kill chains of entities through time and other contextual information like campaigns or incidents.": "キルチェーンをキャンペーンやインシデント等と時間から探す。",
  "Explore the observables of the dataset though time to visualize clusters and correlations.": "観測結果を時間と視覚化されたクラスター/相関から探す。",
  "Explore the techniques, tactics and procedures of the dataset through time and entities who used its.": "TTPsを時間と使用した脅威アクターのエンティティから探す。",
  "Explore the victims and the targets of the dataset through space and time.": "被害者とターゲットを場所と時間から探す。",
  "Explore the vulnerabilities used by entities through time and kill chain phases.": "脆弱性を時間と使用されたキルチェーンのフェーズから探す。",
  "Export": "出力",
  "Export as PDF": "PDF出力",
  "Export as image": "画像出力",
  "Export data in CSV": "CSVでデータを出力する",
  "Export format": "出力形式",
  "Export is disabled because too many entities are targeted (maximum number of entities is: ": "ターゲットとするエンティティが多すぎるため、エクスポートは無効になっています (エンティティの最大数は次のとおりです)。",
  "Export successfully started": "出力を開始しました",
  "Export the entity": "エンティティの出力",
  "Export to CSV": "CSVを出力",
  "Export to PDF": "PDFを出力",
  "Export to document (pdf)": "PDF出力",
  "Export to image": "画像を出力",
  "Export to image (png)": "画像出力 (png)",
  "Export type": "出力タイプ",
  "Exported files": "出力済みファイル",
  "Exports list": "出力結果一覧",
  "Exports panel": "出力画面",
  "External ID": "外部ID",
  "External authentication": "外部認証",
  "External references": "外部参照",
  "External references files": "外部参照資料",
  "False positive": "偽陽性",
  "Feedback": "UNDEFINED",
  "Feeds (CSV)": "フィード (CSV)",
  "Field": "フィールド",
  "Field type": "フィールドタイプ",
  "File MD5 hash": "MD5ハッシュ",
  "File SHA1 hash": "SHA1ハッシュ",
  "File SHA256 hash": "SHA256ハッシュ",
  "File and associated external reference successfully removed": "ファイルおよび関連する外部参照が正常に削除されました",
  "File hash": "ファイルハッシュ",
  "File hashes": "ファイルハッシュ",
  "File information": "ファイル情報",
  "File name": "ファイル名",
  "File path": "ファイルパス",
  "File successfully removed": "ファイルの削除に成功",
  "File successfully uploaded": "ファイルのアップロードに成功",
  "File successfully uploaded and associated external reference successfully created": "ファイルが正常にアップロードされ、関連付けられた外部参照が正常に作成されました",
  "File to import": "インポートするファイル",
  "Files": "ファイル",
  "Files & history": "ファイルと履歴",
  "Filter authors (created by)": "作成者で絞り込む",
  "Filter by": "フィルタ",
  "Filter entity types": "エンティティ種別で絞り込む",
  "Filter marking definitions": "データマーキングで絞り込む",
  "Filters": "フィルタ",
  "First obs.": "初観測日時",
  "First observed": "初観測日時",
  "First seen": "初観測日時",
  "Firstname": "名前",
  "Fit graph to canvas": "グラフを画面内に収める",
  "Force now": "即時適用",
  "Free text import": "フリーテキストのインポート",
  "Friday": "UNDEFINED",
  "From name": "ソース名",
  "From type": "ソースタイプ",
  "Full export (entity and first neighbours)": "エンティティとその関連オブジェクトを出力",
  "Functional date": "機能的な日時",
  "GRAPHQL_API": "GraphQL API",
  "General": "全般",
  "Generate": "生成",
  "Generate an export": "出力ファイルを生成",
  "Generated the": "生成ファイル: ",
  "Generation in progress...": "生成中...",
  "Global": "全体",
  "Global keyword": "グローバルキーワード",
  "Global kill chain": "グローバルキルチェーン",
  "Global parameters": "グローバルパラメータ",
  "Global streams are available for granted users. Live at /stream/live and raw at /stream": "グローバルストリームが許可されたユーザーで利用可能です。ライブストリームは/stream/live、生データは/streamから利用してください。",
  "Goals": "目標",
  "Goals (1 / line)": "目標 (1行あたり1つ)",
  "Good": "高",
  "Granted by default": "デフォルトで付与",
  "Granted by default at user creation": "ユーザー作成時にデフォルトで付与",
  "Graph": "グラフ",
  "Graph type": "グラフタイプ",
  "Graph view": "グラフ表示",
  "Grouping": "グルーピング",
  "Groupings": "グルーピング",
  "Groups": "グループ",
  "Groups permissions on data marking is not fully implemented yet.": "データマーキングのグループ権限は、まだ完全には実装されていません。",
  "Groups with this role": "この役割を持つグループ",
  "HISTORY_MANAGER": "ヒストリーマネージャ",
  "HTML files": "HTMLファイル",
  "Heatmap": "ヒートマップ",
  "Hidden entity types": "非表示のエンティティ種別",
  "Hidden in interface": "インターフェイスに隠されている",
  "Hidden in roles": "ロールに隠されている",
  "Hide in the platform": "UNDEFINED",
  "High": "高い",
  "History": "履歴",
  "Horizontal Bar": "水平バー",
  "Host": "ホスト",
  "INTERNAL_ENRICHMENT": "データエンリッチメント",
  "INTERNAL_EXPORT_FILE": "ファイルエクスポート",
  "INTERNAL_IMPORT_FILE": "ファイルインポート",
  "IPv4 address": "IPv4アドレス",
  "IPv4 addresses": "IPv4アドレス",
  "IPv6 address": "IPv6アドレス",
  "IPv6 addresses": "IPv6アドレス",
  "Identities": "アイデンティティ",
  "Identity": "アイデンティティ",
  "Impacted": "影響",
  "Implant": "インプラント",
  "Implementation languages": "実装言語",
  "Import": "インポート",
  "Import data": "インポート対象データ",
  "Import successfully asked": "インポート要求を正常に受け付けました",
  "Import type": "インポート種別",
  "In OpenCTI, a predictable STIX ID is generated based on one or multiple attributes of the entity.": "OpenCTIでは、1つまたは複数の属性からSTIX IDが生成されます。",
  "In all the database": "すべてのデータベースで",
  "In progress messages": "処理中のメッセージ",
  "In progress tasks": "進行中のタスク",
  "In progress works": "進行中の作業",
  "In this report, ": "このレポートでは、",
  "Incident": "インシデント",
  "Incident Date": "インシデントの日付",
  "Incident type": "インシデントタイプ",
  "Incidents": "インシデント",
  "Include headers in the feed": "フィードにヘッダを含める",
  "Indicator": "インジケータ",
  "Indicator pattern": "インジケータパターン",
  "Indicator type": "インジケータの種別",
  "Indicator types": "インジケータの種別",
  "Indicators": "インジケータ",
  "Indicators composed with this observable": "この観測結果から得られたインジケータ",
  "Indicators/observables generation": "インジケータ/観測結果の生成",
  "Individual": "個人",
  "Individuals": "個人",
  "Inference explanation": "推論に関する説明",
  "Inference rules": "推論ルール",
  "Inferences": "参考",
  "Inferred knowledge based on the rule ": "ルールに基づく推論",
  "Information": "情報",
  "Infrastructure types": "インフラストラクチャ種別",
  "Infrastructures": "インフラストラクチャ",
  "Ingested entities": "取り込まれたエンティティ",
  "Initiator": "イニシエータ",
  "Intrusion set": "侵入セット",
  "Intrusion sets": "侵入セット",
  "Investigate": "調査",
  "Investigations": "調査",
  "Is family": "ファミリ",
  "Is family?": "ファミリかどうか",
  "JSON content": "JSONコンテンツ",
  "Just in the report": "レポートで",
  "Key": "キー",
  "Kill chain": "キルチェーン",
  "Kill chain name": "キルチェーン名",
  "Kill chain phase": "キルチェーンフェーズ",
  "Kill chain phases": "キルチェーンフェーズ",
  "Kill chain view": "キルチェーンの表示",
  "Kill chains": "キルチェーン",
  "Knowledge": "ナレッジ",
  "Knowledge entity": "ナレッジエンティティ",
  "Knowledge graph": "ナレッジグラフ",
  "Knowledge update (except indicators & observables)": "ナレッジを更新（インジケータと観測結果を除く）",
  "Label": "ラベル",
  "Labels": "ラベル",
  "Labels & Attributes": "ラベルと属性",
  "Language": "言語",
  "Last": "UNDEFINED",
  "Last 24 hours": "過去24時間",
  "Last 6 months": "過去6ヶ月",
  "Last 7 days": "過去7日間",
  "Last execution": "最終実行日時",
  "Last ingested reports (creation date in the platform)": "最新のレポート",
  "Last modified": "最終更新日時",
  "Last modified entities": "最後に変更されたエンティティ",
  "Last month": "過去1ヶ月",
  "Last notes": "最新ノート",
  "Last obs.": "最終観測日時",
  "Last observables": "最新の観測結果",
  "Last observed": "最終観測日時",
  "Last processed message": "最後に処理したメッセージ",
  "Last reports": "最新レポート",
  "Last reports about the entity": "このエンティティに関連する最新のレポート",
  "Last run": "最終実行日時",
  "Last run:": "最終実行日時: ",
  "Last seen": "最終観測日時",
  "Last targeted organizations in this sector": "このセクターで最後に標的となった組織",
  "Last update": "最終更新",
  "Last year": "過去1年間",
  "Lastname": "苗字",
  "Latest created relationships": "最後に作成されたリレーションシップ",
  "Latest reports about this entity": "このエンティティに関連する最新のレポート",
  "Latest reports written by this entity": "このエンティティによって作成された最新のレポート",
  "Latitude": "UNDEFINED",
  "Launch": "起動",
  "Launch a background task": "バックグラウンドタスクの起動",
  "Launch an import": "インポート開始",
  "Launch an import of this file": "このファイルのインポートを開始する",
  "Launch rescan": "再スキャンを開始する",
  "Layers": "層",
  "Let the field empty to grant all users": "すべてのユーザーに権限を与えるには、フィールドを空にします",
  "Level": "レベル",
  "Light": "ライトテーマ",
  "Light (with background)": "ライトテーマ (背景有り)",
  "Light (without background)": "ライトテーマ (背景無し)",
  "Light theme": "ライトテーマ",
  "Likelihood": "可能性",
  "Limit": "リミット",
  "Limits": "UNDEFINED",
  "Line chart": "ラインチャート",
  "Lines view": "ライン表示",
  "Linked entities": "リンクされたエンティティ",
  "Linked entity": "リンクされたエンティティ",
  "Linked knowledge": "リンクされたナレッジ",
  "Linked threat": "リンクされた脅威",
  "Linked threat(s)": "リンクされた脅威",
  "Links with threats": "脅威とのリンク",
  "List": "リスト",
  "List of entities": "エンティティ一覧",
  "Live streams": "ライブストリーム",
  "Live trigger": "UNDEFINED",
  "Localized in this country": "この国にローカライズされたもの",
  "Localized in this region": "この地域にローカライズされたもの",
  "Location": "ロケーション",
  "Locations": "ロケーション",
  "Locations of this individual": "この個人の所在地",
  "Locations of this organization": "この組織の所在地",
  "Log sources": "ログソース",
  "Log sources (1 / line)": "ログソース(1行あたり1つ)",
  "Login": "ログイン",
  "Logo URL": "ロゴURL",
  "Logo URL for login page": "ログインページのロゴURL",
  "Logout": "ログアウト",
  "Longitude": "UNDEFINED",
  "Low": "低",
  "MAC address": "MACアドレス",
  "MAC addresses": "MACアドレス",
  "MEDIUM": "UNDEFINED",
  "Main observable type": "観測結果のタイプ",
  "Make this stream public and available to anyone": "このストリームを公開して誰でも利用できるようにする",
  "Malicious": "悪性",
  "Malware": "マルウェア",
  "Malware types": "マルウェア種別",
  "Malwares": "マルウェア",
  "Manage a container": "コンテナを管理する",
  "Manage an entity": "エンティティを管理する",
  "Manage an observable": "オブザーバブルを管理する",
  "Mandatory attributes": "必須属性",
  "Manual": "手動",
  "Map": "地図",
  "Markdown files": "マークダウンファイル",
  "Markdown source": "マークダウンソース",
  "Marking": "マーキング",
  "Marking definitions": "データマーキング",
  "Markings": "マーキング",
  "Matrix view": "マトリックス表示",
  "Max marking definition level": "データマーキングレベルの最大値",
  "Max retention": "最大保持数",
  "Maximum": "UNDEFINED",
  "Maximum retention days": "最大保持日数",
  "Med": "中くらい",
  "Members": "メンバ",
  "Merge": "マージ",
  "Merge entities": "エンティティをマージする",
  "Merged entity": "マージされたエンティティ",
  "Message": "UNDEFINED",
  "Metrics": "メトリクス",
  "MinIO": "MinIO",
  "Mini map": "ミニマップ",
  "Minimum": "UNDEFINED",
  "Minimum one outcome": "UNDEFINED",
  "Minimum one trigger": "UNDEFINED",
  "Mitigated attack patterns": "緩和された攻撃パターン",
  "Moderate": "中",
  "Modification": "UNDEFINED",
  "Modification date": "変更日",
  "Modified": "更新日時",
  "Monday": "UNDEFINED",
  "Month": "月",
  "Month day": "UNDEFINED",
  "More": "もっと見る",
  "Most recent history": "直近の履歴",
  "Multiple": "UNDEFINED",
  "Multiple entities selected": "複数のエンティティが選択されました",
  "Mutex": "ミューテックス",
  "NOTIFICATION_MANAGER": "通知生成マネージャ",
  "Name": "名前",
  "Narrative": "ナラティブ",
  "Narratives": "ナラティブ",
  "Navigation color": "ナビゲーションカラー",
  "Nested objects": "階層化されたオブジェクト",
  "Network": "ネットワーク",
  "Never enabled": "有効化されていない",
  "Never generated": "生成されていません",
  "New alias": "新しい別名",
  "New password": "新しいパスワード",
  "No": "いいえ",
  "No available options": "利用可能なオプションはありません",
  "No available public stream on this platform": "UNDEFINED",
  "No connector available for the selected entities.": "選択したエンティティに有効なコネクタはありません。",
  "No connectors are enabled on this platform.": "有効なコネクタがありません。",
  "No connectors for this type of entity": "このタイプのエンティティ用のコネクタがありません",
  "No description": "UNDEFINED",
  "No description of this targeting": "この標的についての説明はありません",
  "No description of this usage": "この使用方法についての説明はありません",
  "No enrichment connectors on this platform": "有効なエンリッチ用コネクタがありません",
  "No entities of this type has been found.": "このタイプのエンティティは見つかりませんでした。",
  "No entities were found for this search.": "エンティティは見つかりませんでした。",
  "No export connector available to generate an export": "対応する出力用コネクタがありません",
  "No file for the moment": "ファイルが存在しません",
  "No file selected.": "ファイルが選択されていません。",
  "No files in this category.": "このカテゴリーに該当するファイルはありません。",
  "No history about this entity.": "このエンティティには履歴がありません。",
  "No history about this relationship.": "このリレーションシップについての履歴はありません。",
  "No import connectors on this platform": "有効なインポート用コネクタがありません",
  "No label": "ラベルなし",
  "No notes about this entity yet.": "このエンティティにはまだノートがありません。",
  "No potential duplicate entities has been found.": "重複する可能性のあるエンティティは見つかりませんでした。",
  "No relations history about this entity.": "このエンティティにはリレーションの履歴がありません。",
  "No reports about this entity.": "このエンティティに関するレポートはありません。",
  "No task": "タスクなし",
  "No value": "値なし",
  "No widget in this workspace": "このワークスペースにウィジェットはありません",
  "No work": "作業なし",
  "None": "N/A",
  "Nonee": "N/A",
  "Not Specified": "指定されていない",
  "Not aplicable": "適用不可",
  "Not applicable": "該当なし",
  "Note types": "ノートの種類",
  "Notes": "ノート",
  "Notes about this entity": "このエンティティに関するノート",
  "Notes about this relationship": "このリレーションシップに関するノート",
  "Notification": "UNDEFINED",
  "Notifications and triggers": "UNDEFINED",
  "Number": "番号",
  "Number observed": "観測された数",
  "Number of": "番号",
  "Number of elements": "要素数",
  "Number of entities": "エンティティ数",
  "Number of errors": "エラー数",
  "Number of relationships": "リレーションシップの数",
  "Number of target relations": "対象のリレーションの数",
  "Number of targeting": "標的の数",
  "OR": "UNDEFINED",
  "Object": "UNDEFINED",
  "Objective": "目的",
  "Observable type": "観測結果の種別",
  "Observable types": "観測結果の種別",
  "Observable value": "観測結果の値",
  "Observables": "観測結果",
  "Observables and indicators conversion": "観測結果とインジケータの変換",
  "Observables distribution": "観測結果の分布",
  "Observables roles": "観測結果のロール",
  "Observations": "観測記録",
  "Observed data": "観測データ",
  "Observed datas": "観測データ",
  "One keyword by line or separated by commas": "1 つのキーワードを 1 行またはカンマで区切る",
  "Only contextual": "条件に応じて起動",
  "Open export panel": "出力画面を開く",
  "Open the suggestions": "提案を開く",
  "OpenCTI - Cyber threat intelligence platform": "OpenCTI - サイバー脅威インテリジェンスプラットフォーム",
  "OpenCTI version": "OpenCTIバージョン",
  "Operations completed": "完了したオペレーションの数",
  "Opinion": "UNDEFINED",
  "Opinions": "オピニオン",
  "Optional, you may want to subscribe to specific entities.": "特定のエンティティを登録できます。",
  "Options": "オプション",
  "Order": "順序",
  "Organization": "組織",
  "Organization type": "組織種別",
  "Organizations": "組織",
  "Organizations restriction": "組織の制限",
  "Organizations sharing": "UNDEFINED",
  "Originates from": "発生元",
  "Origins of the malware": "このマルウェアの発生元",
  "Origins of the targeting": "標的の発生元",
  "Origins of this campaign": "このキャンペーンの発生元",
  "Origins of this incident": "このインシデントの発生元",
  "Origins of this intrusion set": "この侵入セットの発生元",
  "Other": "その他",
  "Other STIX IDs": "その他のSTIX ID",
  "Others": "UNDEFINED",
  "Out of Range": "範囲外",
  "Overview": "概要",
  "Owner": "所有者",
  "PDB Path": "PDBパス",
  "PDF files": "PDFファイル",
  "PDF viewer": "PDFビューアー",
  "PUBLISHER_MANAGER": "M通知発行マネージャ",
  "Paper color": "ウィジェットカラー",
  "Parameters": "パラメータ",
  "Parent attack patterns": "上位攻撃パターン",
  "Parent regions": "親地域",
  "Parent sectors": "上位セクター",
  "Part of this sector": "このセクターの一部",
  "Partner": "パートナー",
  "Password": "パスワード",
  "Pattern": "パターン",
  "Pattern type": "パターンタイプ",
  "Period": "UNDEFINED",
  "Periodicity": "周期",
  "Permissions": "パーミッション",
  "Personal motivations": "個人的動機",
  "Phase name": "フェーズ名",
  "Pie chart": "円グラフ",
  "Platform": "プラットフォーム",
  "Platform favicon URL": "faviconのURL",
  "Platform login message": "ログインメッセージ",
  "Platform organization": "プラットフォーム構成",
  "Platform title": "プラットフォーム名",
  "Platforms": "プラットフォーム",
  "Played role": "実行されたロール",
  "Playground": "プレイグラウンド",
  "Positions": "位置",
  "Postal code": "郵便番号",
  "Potential duplicate entities": "重複する可能性のあるエンティティ",
  "Preview": "プレビュー",
  "Primary color": "プライマリーカラー",
  "Primary motivation": "一次的動機",
  "Priority": "優先順位",
  "Processed time": "処理時間",
  "Processing status": "処理状況",
  "Profile": "プロフィール",
  "Progress": "進捗",
  "Proxy": "プロキシ",
  "Public stream": "公開ストリーム",
  "Public stream collections": "UNDEFINED",
  "Publication": "公開",
  "Publication date": "公開日",
  "Queued bundles": "キューイング済みバンドル",
  "RETENTION_MANAGER": "リテンションマネージャ",
  "RFIs": "UNDEFINED",
  "RULE_ENGINE": "ルールエンジン",
  "RabbitMQ": "RabbitMQ",
  "Radar chart": "レーダーチャート",
  "Rating": "評価",
  "Read operations": "読み込みオペレーション",
  "Received time": "受付時刻",
  "Redirecting to the Content section": "コンテンツセクションへのリダイレクト",
  "Redirecting to the Knowledge section": "ナレッジセクションへのリダイレクト",
  "Redirecting to the Overview section": "概要セクションへのリダイレクト",
  "Redis": "Redis",
  "Reference knowledge update": "リファレンスナレッジの更新",
  "Reference modification": "参考文献の変更",
  "References": "参考文献",
  "Refresh the knowledge using this connector": "このコネクタを使用してエンティティを更新する",
  "Region": "地域",
  "Regions": "地域",
  "Regions, countries and cities": "地域、国と都市",
  "Registered connectors": "登録済みのコネクタ",
  "Registration": "登録",
  "Registry": "レジストリ",
  "Registry key": "レジストリキー",
  "Registry key value": "レジストリ値",
  "Regular digest": "UNDEFINED",
  "Related cases": "関連事例",
  "Related entities": "関連エンティティ",
  "Related entities (generic relation \"related-to\")": "関連するエンティティ(一般的なリレーションは \"関連あり\")",
  "Related reports": "関連レポート",
  "Related to this country": "この国に関連付けられたもの",
  "Related to this organization": "この組織に関連付けられたもの",
  "Related to this region": "この地域に関連付けられたもの",
  "Relation": "リレーション",
  "Relation type": "リレーションタイプ",
  "Relations": "リレーション",
  "Relations of the entity": "エンティティのリレーション",
  "Relations to other entities": "他のエンティティとのリレーション",
  "Relations to threats": "脅威とのリレーション",
  "Relationship": "リレーションシップ",
  "Relationship type": "リレーションシップタイプ",
  "Relationship types": "関係の種類",
  "Relationships": "リレーションシップ",
  "Relative time": "相対時間",
  "Reliability": "信頼性",
  "Remote OpenCTI URL": "リモートOpenCTI URL",
  "Remote OpenCTI configuration": "リモート OpenCTI 構成",
  "Remote OpenCTI stream ID": "リモートOpenCTI ストリームID",
  "Remote OpenCTI token": "リモートOpenCTI トークン",
  "Remove": "解除",
  "Remove from the container": "コンテナから削除する",
  "Remove from this entity": "このエンティティから削除する",
  "Remove from this object": "このオブジェクトから削除する",
  "Remove selected items": "選択したアイテムを削除する",
  "Renew": "更新",
  "Replace": "置換",
  "Report": "レポート",
  "Report type": "レポートタイプ",
  "Report types": "レポートタイプ",
  "Reports": "レポート",
  "Reports distribution": "レポートの分布",
  "Required permissions": "要求されるパーミッション",
  "Rescan": "再スキャン",
  "Reset": "リセット",
  "Reset filters": "フィルタをリセット",
  "Reset the connector state": "コネクタの状態を初期化する",
  "Resource level": "リソースレベル",
  "Response type": "応答タイプ",
  "Retention policies": "保持ポリシー",
  "Revoked": "失効",
  "Rich editor": "リッチエディタ",
  "Role": "ロール",
  "Roles": "ロール",
  "Rolling time": "問い合わせ間隔",
  "Rolling time (in minutes)": "問い合わせ間隔(分)",
  "Rule entity rescan": "ルールエンティティの再スキャン",
  "Rule has been cleaned up on the existing data": "既存データからルールを削除しました",
  "Rule rescan": "ルールの再スキャン",
  "Rule rescan (engine is disabled)": "ルールの再スキャン（停止中）",
  "Rules engine": "ルールエンジン",
  "Running": "開始",
  "STIX Version": "STIXバージョン",
  "STIX2 bundle": "STIX2バンドル",
  "STREAM": "ストリーミング",
  "SUBSCRIPTION_MANAGER": "サブスクリプションマネージャ",
  "SYNC_MANAGER": "シンクマネージャ",
  "Saturday": "UNDEFINED",
  "Save": "UNDEFINED",
  "Scope": "スコープ",
  "Score": "スコア",
  "Search": "検索",
  "Search for a threat...": "脅威の検索...",
  "Search for an entity": "エンティティを検索",
  "Search for multiple entities": "複数のエンティティを検索",
  "Secondary color": "セカンダリーカラー",
  "Secondary motivations": "二次的動機",
  "Sector": "セクター",
  "Sectors": "セクター",
  "Sectors and organizations": "セクターと組織",
  "Select a relationship": "リレーションシップを選択",
  "Select all nodes": "すべてのノードを選択",
  "Select by entity type": "エンティティ種別を指定して選択",
  "Select your file": "ファイルを選択してください",
  "Selected connectors": "選択したコネクタ",
  "Selected entities": "選択したエンティティ",
  "Selected rules": "選択されたルール",
  "Sender": "送信者",
  "Sender email address": "メールアドレス",
  "Separator": "セパレータ",
  "Settings": "設定",
  "Settings have been updated": "設定を変更しました",
  "Severity": "重大度",
  "Share": "共有する",
  "Share with an organization": "組織と共有する",
  "Sightings": "目撃情報",
  "Sightings distribution": "目撃情報の分布",
  "Sign in": "サインイン",
  "Signatures": "シグネチャ",
  "Simple export (just the entity)": "エンティティのみ出力",
  "Size": "サイズ",
  "Sophistication": "洗練度",
  "Sort by": "ソート",
  "Source": "UNDEFINED",
  "Source name": "ソース名",
  "Standard STIX ID": "標準STIX ID",
  "Start": "開始",
  "Start date": "開始日",
  "Start time": "開始時刻",
  "Starting synchronization (empty = from start)": "同期処理を開始します (値が未設定の場合、開始時刻が適用されます)",
  "State": "状態",
  "Statistics": "統計",
  "Status": "ステータス",
  "Status templates": "ステータス テンプレート",
  "Step": "ステップ",
  "Stop": "停止",
  "Stop time": "停止時刻",
  "Stream ID": "ストリーム ID",
  "Street address": "住所",
  "Strong": "最高",
  "Sub attack patterns": "下位攻撃パターン",
  "Submit a feedback": "フィードバックを送信する",
  "Subregions": "子地域",
  "Subscriptions & digests": "サブスクリプション & ダイジェスト版",
  "Subsectors": "下位セクター",
  "Sunday": "UNDEFINED",
  "Synchronization": "同期",
  "Synthesis of knowledge": "ナレッジの統合",
  "System": "システム",
  "Systems": "システム",
  "TASK_MANAGER": "タスクマネージャ",
  "TAXII collections": "TAXIIコレクション",
  "TTPs": "TTPs",
  "TTPs knowledge": "TTPsに関するナレッジ",
  "TTPs of threats": "脅威の用いるTTPs",
  "TTPs through time": "時間軸でみたTTPs",
  "Table": "表",
  "Table (top 10)": "表(トップ10)",
  "Tactics": "戦術",
  "Tactics matrix view": "戦術マトリックスの表示",
  "Take deletions into account": "削除されたものを考慮する",
  "Target": "UNDEFINED",
  "Targeted by this TTP": "このTTPの標的",
  "Targeted by this actor": "この脅威アクターの標的",
  "Targeted by this intrusion set": "この侵入セットの標的",
  "Targeted by this malware": "このマルウェアの標的",
  "Targeted countries (3 last months)": "攻撃対象国（過去3ヶ月）",
  "Targeted entities": "対象エンティティ",
  "Targeted entity through time": "時間で見た標的となったエンティティ",
  "Targeted entity types": "標的となったエンティティ種別",
  "Targeted in this campaign": "このキャンペーンの標的",
  "Targeted in this incident": "このインシデントの標的",
  "Targeting knowledge": "ターゲットに関するナレッジ",
  "Targeting this country": "この国を標的にするもの",
  "Targeting this individual": "この個人を標的にするもの",
  "Targeting this organization": "この組織を標的にするもの",
  "Targeting this region": "この地域を標的にするもの",
  "Targeting this sector": "このセクターを標的にしているもの",
  "Targeting this vulnerability": "この脆弱性を標的にするもの",
  "Targeting through time": "時間軸でみたターゲティング",
  "Targeting types": "標的種別",
  "Task end time": "タスク終了時刻",
  "Task start time": "タスク開始時刻",
  "Tasks": "UNDEFINED",
  "Technical date": "技術的な日時",
  "Technical elements (indicators & observables)": "技術的要素（インジケータと観測結果）",
  "Techniques": "技術",
  "Techniques matrix": "技術マトリックス",
  "Text files": "テキストファイル",
  "The CSV file has been generated with the parameters of the view and is ready for download.": "指定されたパラメータでCSVが生成され、ダウンロードできるようになりました。",
  "The alias has been added": "別名を追加しました",
  "The code is not correct": "コードが正しくありません",
  "The color must be written in hexadecimal. Example: #ff9800": "色は 16 進数で記述する必要があります。例: #ff9800",
  "The connector has been cleared": "コネクタを削除しました",
  "The connector state has been reset": "コネクタの状態を初期化しました",
  "The importation of the file has been started": "ファイルのインポートが開始されました",
  "The min value cannot be greater than max value": "最小値を最大値より大きくすることはできません",
  "The minimum value cannot be greater than maximum value": "UNDEFINED",
  "The password has been updated": "パスワードを変更しました",
  "The relations attached to selected entities will be copied to the merged entity.": "選択されたエンティティに付属するリレーションは、マージされたエンティティにコピーされます。",
  "The rule has been disabled, clean-up launched...": "ルールは無効化され、クリーンアップが開始されました...",
  "The rule has been enabled, rescan of platform data launched...": "ルールが有効化され、プラットフォームデータの再スキャンが開始されました...",
  "The value is too long": "文字数が上限を超えています",
  "The value is too short": "文字数が不足しています",
  "The value must be a date (yyyy-MM-dd)": "日付(yyyy-MM-dd)を入力してください",
  "The value must be a datetime (yyyy-MM-dd hh:mm (a|p)m)": "日時(yyyy-MM-dd hh:mm (a|p)m)を入力してください",
  "The value must be a datetime with seconds (yyyy-MM-dd hh:mm:ss (a|p)m)": "日時(yyyy-MM-dd hh:mm:ss (a|p)m)を入力してください",
  "The value must be a number": "数値を入力してください",
  "The value must be an URL": "URLを入力してください",
  "The value must be an email address": "メールアドレスを入力してください",
  "The value must be between min and max value": "値は最小値と最大値の間でなければなりません",
  "The value must be between minimum and maximum value": "UNDEFINED",
  "The value must be greater than or equal to 0": "値は 0 以上である必要があります",
  "The value must be less than or equal to 100": "値は 100 以下である必要があります",
  "The values do not match": "値が一致しません",
  "Theme": "テーマ",
  "This action will generate STIX patterns indicators from the selected observables.": "この操作によって選択された観測結果からSTIXパターンインジケータを生成します。",
  "This action will generate observables from the selected indicators.": "この操作によって選択されたインジケータから観測結果が生成されます。",
  "This configuration enables an entity to automatically construct an external reference from the uploaded file.": "この構成により、エンティティはアップロードされたファイルから外部参照を自動的に構築できます。",
  "This configuration enables the requirement of a reference message on an entity update.": "この構成により、エンティティ更新時の参照メッセージの要件が有効になります。",
  "This configuration hide a specific entity type across the entire platform.": "この構成により、プラットフォーム全体で特定のエンティティ タイプが非表示になりました。",
  "This configuration is not available for this entity type": "この構成は、このエンティティ タイプでは使用できません",
  "This connector is active": "このコネクタはアクティブです",
  "This connector is disconnected": "このコネクタとの接続が切れています",
  "This feature is not available yet.": "この機能はまだ利用できません。",
  "This field is required": "このフィールドは必須です",
  "This field must be a number": "UNDEFINED",
  "This field must only contain alphanumeric chars, dashes and space": "このフィールドに入力可能な文字はアルファベット、数字、\"-\", 半角スペースのみです",
  "This individual is now a user": "この個人が現在のユーザーです",
  "This individual is part of": "この個人が属するもの",
  "This malware has been used": "このマルウェアが使用された",
  "This page is not found on this OpenCTI application.": "このページは、OpenCTIアプリケーション上で見つかりませんでした。",
  "This panel shows by default the latest created entities, use the search to find more.": "デフォルトではこのパネルには最近作成されたエンティティが表示されますが、検索を使うことでより多くのエンティティを表示できます。",
  "This relation is inferred": "このリレーションが推測されました",
  "This report contains too many objects to be displayed as a graph. We are working on a new visualization which will allow large graph to be displayed in the future.": "このレポートには、非常に多いオブジェクトが含まれているため、グラフを表示できません。将来的には大きなグラフを表示できるように取り組んでいます。",
  "This rule has been applied on the existing data": "既存のデータにルールを適用しました",
  "This sector does not have any description.": "このセクターには説明がありません。",
  "Threat actor": "脅威アクター",
  "Threat actor types": "脅威アクターの種別",
  "Threat actors": "脅威アクター",
  "Threat hunting techniques": "スレットハンティング手法",
  "Threats": "脅威",
  "Threats targeting": "脅威のターゲット",
  "Threats using this malware": "このマルウェアを使用する脅威",
  "Thursday": "UNDEFINED",
  "Ticks": "マーカー",
  "Time": "UNDEFINED",
  "Timeline": "タイムライン",
  "Title": "タイトル",
  "To name": "ターゲット名",
  "To type": "ターゲットタイプ",
  "To use this feature, your platform administrator must enable the according manager in the config.": "この機能を使用するには、プラットフォーム管理者が構成で適切なマネージャーを有効にする必要があります。",
  "To use this feature, your platform administrator must enable the subscription manager in the config.": "この機能を使用するためには、プラットフォーム管理者が設定でサブスクリプションマネージャーを有効にする必要があります。",
  "Token": "UNDEFINED",
  "Too many objects": "オブジェクトが多すぎます",
  "Tool": "ツール",
  "Tool types": "ツール種別",
  "Tool usage": "ツールの使い方",
  "Tool version": "ツールバージョン",
  "Tools": "ツール",
  "Tools versions": "ツールバージョン",
  "Top 10 active entities (3 last months)": "活動中の上位10エンティティ (過去3ヶ月)",
  "Top 10 threats targeting this entity": "このエンティティを標的とした脅威のトップ10",
  "Top 10:": "トップ10:",
  "Top Labels (3 last months)": "上位のラベル(過去3ヶ月)",
  "Total direct relations": "直接的なリレーションの総数",
  "Total entities": "エンティティの総数",
  "Total indicators": "インジケータの総数",
  "Total notes": "ノートの総数",
  "Total number of documents": "ドキュメントの総数",
  "Total number of operations": "オペレーションの総数",
  "Total observables": "観測結果の総数",
  "Total pending inserts": "保留中の挿入事項の総数",
  "Total processed messages": "処理したメッセージの総数",
  "Total relations": "リレーションの総数",
  "Total relationships": "リレーションシップの総数",
  "Total reports": "レポートの総数",
  "Total workspaces": "ワークスペースの総数",
  "Triggering on": "UNDEFINED",
  "Triggers": "UNDEFINED",
  "Tuesday": "UNDEFINED",
  "Turn to user": "ユーザーに向ける",
  "Two-factor authentication": "二要素認証",
  "Type": "タイプ",
  "Type the code generated in your application": "アプリケーションが生成したコードを入力してください",
  "Types": "UNDEFINED",
  "Types of the targeting": "標的の種別",
  "Types of the targets": "標的の種別",
  "URL": "URL",
  "Unauthorized action, please refresh your browser": "不正な操作です。ブラウザを更新してください",
  "Unfix the nodes and re-apply forces": "ノードの固定を解除し、強制モードを再適用する",
  "Unique identifier": "一意な識別子",
  "Unknown": "不明",
  "Unsupported": "サポートされていません",
  "Update": "更新",
  "Update a TAXII collection": "TAXIIコレクションを更新",
  "Update a campaign": "キャンペーンを更新",
  "Update a case incident": "ケース インシデントの更新",
  "Update a channel": "チャネルを更新",
  "Update a city": "都市を更新",
  "Update a country": "国を更新",
  "Update a course of action": "行動指針を更新",
  "Update a data component": "データコンポーネントの更新",
  "Update a data source": "データ ソースを更新する",
  "Update a feed": "フィードを更新",
  "Update a feedback": "フィードバックを更新する",
  "Update a group": "グループを更新",
  "Update a grouping": "グルーピングを作成",
  "Update a individual": "個人を更新",
  "Update a kill chain phase": "キルチェーンフェーズを更新",
  "Update a label": "ラベルを更新",
  "Update a live stream": "ライブストリームを更新",
  "Update a malware": "マルウェアを更新",
  "Update a marking definition": "データマーキングを更新",
  "Update a narrative": "ナラティブを更新",
  "Update a note": "ノートを更新",
  "Update a position": "職位の更新",
  "Update a region": "地域を更新",
  "Update a relationship": "リレーションシップを更新",
  "Update a report": "レポートを更新",
  "Update a retention policy": "保持ポリシーの更新",
  "Update a role": "ロールを更新",
  "Update a sector": "セクターを更新",
  "Update a sighting": "目撃情報を更新",
  "Update a status": "ステータスを更新する",
  "Update a status template": "状態テンプレートを更新する",
  "Update a subscription": "サブスクリプションを更新",
  "Update a synchronizer": "同期処理を更新",
  "Update a system": "システムを更新",
  "Update a threat actor": "脅威アクターを更新",
  "Update a tool": "ツールを更新",
  "Update a trigger": "UNDEFINED",
  "Update a user": "ユーザーを更新",
  "Update a vulnerability": "脆弱性を更新",
  "Update a widget": "ウィジェットを更新",
  "Update a workspace": "ワークスペースを更新",
  "Update an area": "領域を更新します",
  "Update an artifact": "アーティファクトを更新",
  "Update an attack pattern": "攻撃パターンを更新",
  "Update an attribute": "属性を更新",
  "Update an country": "UNDEFINED",
  "Update an entity": "エンティティを更新",
  "Update an event": "イベントを更新",
  "Update an external reference": "外部参照を更新",
  "Update an incident": "インシデントを更新",
  "Update an indicator": "インジケータを更新",
  "Update an infrastructure": "インフラストラクチャを更新",
  "Update an intrusion set": "侵入セットを更新",
  "Update an observable": "観測結果を更新",
  "Update an observed data": "観測データを更新",
  "Update an organization": "組織を更新",
  "Update and complete": "更新して完了",
  "Update entities": "エンティティの更新",
  "Update opinion": "オピニオンの更新",
  "Updated the": "更新日: ",
  "Uploaded files": "アップロードされたファイル",
  "Usage": "使用方法",
  "Use": "UNDEFINED",
  "Use 2FA authentication": "二要素認証を使用する",
  "Use Alt + click to exclude items": "Alt + クリックを使用して項目を除外する",
  "Used TTPs": "使用されたTTPs",
  "Used by this actor": "この脅威アクターに使用されたもの",
  "Used by this intrusion set": "この侵入セットに使用されたもの",
  "Used by this malware": "このマルウェアが使用するもの",
  "Used in this campaign": "このキャンペーンに使用されたもの",
  "Used in this incident": "このインシデントで使用されたもの",
  "Used tools": "使用されたツール",
  "User interface": "UNDEFINED",
  "User responsible for data creation (empty = System)": "データ作成を担当するユーザー (空 = System)",
  "User will be created with default groups.": "ユーザーは既定のグループで作成されます。",
  "Users": "ユーザー",
  "Using this TTP": "このTTPを使用しているもの",
  "Using this tool": "このツールを使用しているもの",
  "Valid from": "有効期間(開始)",
  "Valid until": "有効期間(終了)",
  "Validate": "有効期限",
  "Validate and send for import": "インポート用に検証して送信する",
  "Validate this workbench": "このワークスペースを検証する",
  "Value": "値",
  "Values": "値",
  "Variants": "バリエーション",
  "Variants of this malware": "このマルウェアの亜種",
  "Vendor": "ベンダー",
  "Verify": "検証",
  "Verify SSL certificate": "SSL証明書を検証する",
  "Versions": "バージョン",
  "Vertical Bar": "縦棒",
  "Victimology": "被害者学",
  "Victimology (countries)": "被害者学（国）",
  "Victimology (regions)": "被害者学（地域）",
  "Victimology (sectors)": "被害者学（セクター）",
  "View": "表示",
  "View the item": "アイテムの表示",
  "Visualization": "可視化",
  "Vulnerabilities": "脆弱性",
  "Vulnerability": "脆弱性",
  "Vulnerability usage": "脆弱性の利用",
  "Webhook": "UNDEFINED",
  "Wednesday": "UNDEFINED",
  "Week day": "UNDEFINED",
  "When you specified the platform organization, data without any organization restriction will be accessible only for users that are part of the platform one": "プラットフォーム組織を指定すると、組織の制限のないデータには、プラットフォーム 1 の一部であるユーザーのみがアクセスできます",
  "Widget": "ウィジェット",
  "Windows scheduled tasks": "Windowsのスケジュールされたタスク",
  "Windows services": "Windowsサービス",
  "Work end time": "作業終了時刻",
  "Work start time": "作業開始時刻",
  "Workers statistics": "ワーカーの統計",
  "Workflow": "ワークフロー",
  "Workflow of": "ワークフロー",
  "Workflows": "ワークフロー",
  "Works": "作業",
  "Workspace": "ワークスペース",
  "Workspaces": "ワークスペース",
  "Write": "編集",
  "Write a note": "ノートを書く",
  "Write operations": "書き込みオペレーション",
  "Write something awesome...": "値を入力してください。",
  "X509 Certificates": "X.509証明書",
  "Year": "年",
  "Yes": "はい",
  "You are not allowed to do this.": "この操作を行う権限がありません。",
  "You do not have any access to the knowledge of this OpenCTI instance.": "このOpenCTIインスタンスのナレッジデータにアクセスする権限がありません。",
  "You have no subscription for the moment.": "現在、サブスクリプションはありません。",
  "You have successfully logged out.": "ログアウトが完了しました。",
  "You must be logged in to do this.": "この操作を行うにはログインする必要があります。",
  "You must provide at least one external reference for this type of entity": "このタイプのエンティティは最低1個の外部参照を含む必要があります",
  "You need to activate a two-factor authentication. Please type the code generated in your application.": "二要素認証を有効にする必要があります。アプリケーションで生成されたコードを入力してください。",
  "You need to validate your two-factor authentication. Please type the code generated in your application.": "二要素認証を検証する必要があります。アプリケーションで生成されたコードを入力してください。",
  "You're targeting more than 1000 entities with this background task, be sure of what you're doing!": "このバックグラウンドタスクで1000以上のエンティティをターゲットにしています。実行内容を確認してください。",
  "_": "UNDEFINED",
  "added a note": "メモを追加しました",
  "day": "UNDEFINED",
  "entities": "エンティティ",
  "entity_Administrative-Area": "管理領域",
  "entity_All": "全てのエンティティ",
  "entity_Analysis": "解析",
  "entity_Arsenal": "武器庫",
  "entity_Artifact": "アーティファクト",
  "entity_Attack-Pattern": "攻撃パターン",
  "entity_Autonomous-System": "自律システム (AS)",
  "entity_Bank-Account": "銀行口座",
  "entity_Campaign": "キャンペーン",
  "entity_Case": "場合",
  "entity_Case-Incident": "インシデント対応",
  "entity_Case-Rfi": "情報を要求する",
  "entity_Case-Rft": "削除のリクエスト",
  "entity_Channel": "チャネル",
  "entity_City": "都市",
  "entity_Country": "国",
  "entity_Course-Of-Action": "行動指針",
  "entity_Cryptocurrency-Wallet": "暗号通貨ウォレット",
  "entity_Cryptographic-Key": "暗号鍵",
  "entity_Data-Component": "データコンポーネント",
  "entity_Data-Source": "データソース",
  "entity_Directory": "ディレクトリ",
  "entity_Domain-Name": "ドメイン名",
  "entity_Email-Addr": "Eメールアドレス",
  "entity_Email-Message": "Eメールメッセージ",
  "entity_Email-Mime-Part-Type": "Eメールメッセージ - MIMEマルチパート",
  "entity_Entities": "エンティティ",
  "entity_Event": "イベント",
  "entity_Events": "イベント",
  "entity_External-Reference": "外部参照資料",
  "entity_Feedback": "フィードバック",
  "entity_Grouping": "グループ化",
  "entity_Hostname": "ホスト名",
  "entity_IPv4-Addr": "IPv4アドレス",
  "entity_IPv6-Addr": "IPv6アドレス",
  "entity_Identity": "アイデンティティ",
  "entity_Incident": "インシデント",
  "entity_Indicator": "インジケータ",
  "entity_Individual": "個人",
  "entity_Infrastructure": "インフラストラクチャ",
  "entity_Intrusion-Set": "侵入セット",
  "entity_Ipv4-Addr": "IPv4アドレス",
  "entity_Ipv6-Addr": "IPv6アドレス",
  "entity_Label": "ラベル",
  "entity_Language": "言語",
  "entity_Location": "ロケーション",
  "entity_Locations": "場所",
  "entity_Mac-Addr": "MACアドレス",
  "entity_Malware": "マルウェア",
  "entity_Marking-Definition": "データマーキング",
  "entity_Media-Content": "メディアコンテンツ",
  "entity_Mutex": "ミューテックス",
  "entity_Narrative": "ナラティブ",
  "entity_Network-Traffic": "ネットワークトラフィック",
  "entity_Note": "ノート",
  "entity_Observable": "オブザーバブル",
  "entity_Observations": "観測",
  "entity_Observed-Data": "観測データ",
  "entity_Opinion": "オピニオン",
  "entity_Organization": "組織",
  "entity_Payment-Card": "クレジットカード番号",
  "entity_Phone-Number": "電話番号",
  "entity_Position": "位置",
  "entity_Process": "プロセス",
  "entity_Region": "地域",
  "entity_Relationship": "リレーションシップ",
  "entity_Report": "レポート",
  "entity_Sector": "セクター",
  "entity_Sighting": "一斑",
  "entity_Software": "ソフトウェア",
  "entity_Stix-Core-Objects": "エンティティと観測結果",
  "entity_Stix-Core-Relationship": "リレーションシップ",
  "entity_Stix-Cyber-Observable": "観測結果",
  "entity_Stix-Cyber-Observables": "観測結果",
  "entity_Stix-Domain-Object": "エンティティ",
  "entity_Stix-Domain-Objects": "エンティティ(複数)",
  "entity_StixFile": "ファイル",
  "entity_Stixfile": "ファイル",
  "entity_System": "システム",
  "entity_Techniques": "技術",
  "entity_Text": "テキスト",
  "entity_Threat-Actor": "脅威アクター",
  "entity_Threats": "脅威",
  "entity_Tool": "ツール",
  "entity_Url": "URL",
  "entity_User-Account": "ユーザアカウント",
  "entity_User-Agent": "ユーザーエージェント",
  "entity_Vulnerability": "脆弱性",
  "entity_Windows-Registry-Key": "Windowsレジストリキー",
  "entity_Windows-Registry-Value-Type": "Windowsレジストリ値",
  "entity_X509-Certificate": "X.509証明書",
  "filter_assigneeTo": "譲受人",
  "filter_basedOn": "観測結果をベースにする",
  "filter_containedBy": "コンテナ",
  "filter_createdBy": "作成者",
  "filter_createdBy_not_eq": "作成者なし",
  "filter_elementId": "関連エンティティ",
  "filter_fromId": "ソースのエンティティ",
  "filter_fromTypes": "ソースのタイプ",
  "filter_killChainPhase": "キルチェーンフェーズ",
  "filter_labelledBy": "ラベル",
  "filter_labelledBy_not_eq": "ラベルなし",
  "filter_markedBy": "データマーキング",
  "filter_markedBy_not_eq": "データマーキングなし",
  "filter_objectContains": "含む",
  "filter_sightedBy": "目撃情報",
  "filter_sightedBy_not_eq": "目撃情報なし",
  "filter_toCreatedAt_end_date": "作成日時(終了)",
  "filter_toCreatedAt_start_date": "作成日時(開始)",
  "filter_toId": "ターゲットのエンティティ",
  "filter_toSightingId": "目撃情報",
  "filter_toTypes": "ターゲットのタイプ",
  "hour": "UNDEFINED",
  "name": "名前",
  "obsContent": "コンテンツ",
  "of": "UNDEFINED",
  "on": "UNDEFINED",
  "organization": "構造化された組織",
  "relationship_All": "全てのタイプのリレーション",
  "reliability_A": "A - 非常に信頼できる",
  "reliability_B": "B - 信頼できる",
  "reliability_C": "C - ほぼ信頼できる",
  "reliability_D": "D - 一部信頼できない",
  "reliability_E": "E - 信頼できない",
  "reliability_F": "F - 判断不能",
  "selected": "選択中: ",
  "to exclude items": "UNDEFINED",
  "unknown": "不明",
  "week": "UNDEFINED"
}