export default {
  "2FA state": "2FA状态",
  "AND": "UNDEFINED",
  "API access": "API访问",
  "API key": "API密钥",
  "About": "关于",
  "Abstract": "抽象",
  "Access stream directly in your browser": "UNDEFINED",
  "Accesses": "接入",
  "Action type": "行动类型",
  "Active": "活跃",
  "Activities": "活动",
  "Activity": "活动",
  "Add": "添加",
  "Add Tick": "添加标记",
  "Add a widget": "添加控件",
  "Add an action": "增加一个动作",
  "Add an entity to this container": "将实体添加到此容器",
  "Add and complete": "添加并完成",
  "Add attack patterns": "添加攻击模式",
  "Add context": "添加上下文",
  "Add courses of action": "添加应对措施",
  "Add data components": "添加数据组件",
  "Add data source": "添加数据源",
  "Add entities": "添加实体",
  "Add external references": "添加外部引用",
  "Add locations": "添加位置",
  "Add new labels": "添加新的标签",
  "Add notes": "添加注释",
  "Add observable": "添加可观测数据",
  "Add observables": "添加可观测数据",
  "Add sub attack patterns": "添加子攻击模式",
  "Add subsectors": "添加子部门",
  "Additional mandatory attributes": "额外的强制属性",
  "Admin": "管理员",
  "Advanced search": "高级搜索",
  "Affected software": "受影响的软件",
  "Affecting this sector": "影响此部门",
  "Alias": "别名",
  "Aliases": "UNDEFINED",
  "Aliases separated by commas": "用逗号分隔的别名",
  "All": "所有",
  "All confidence levels": "所有置信水平",
  "All entities": "所有实体",
  "All observables": "所有可观测数据",
  "All reports": "所有报告",
  "All threats": "所有威胁",
  "All types of entity": "所有类型的实体",
  "All types of relationship": "关系的所有类型",
  "All years": "所有年份",
  "Allowed markings": "允許的標記",
  "Already in plat.": "经在平台",
  "Also delete these elements": "同时删除这些元素",
  "An unknown error has occurred!  Please try again later.": "发生未知错误，请稍后再试。",
  "Analysis": "分析",
  "Analyst workbenches": "分析师工作区",
  "Apply on": "应用于",
  "Applying this rule on the existing data": "对现有数据应用此规则",
  "Architecture execution env.": "架构执行环境",
  "Area": "管理領域",
  "Areas": "地域",
  "Arsenal": "武器库",
  "Artifacts": "工件",
  "As it happens": "当其发生时",
  "Assignee(s)": "协调人",
  "Assignees": "受让人",
  "Associated file": "关联的文件",
  "Attack pattern": "攻击模式",
  "Attack pattern usage": "攻击模式使用",
  "Attack patterns": "攻击模式",
  "Attributed to this actor": "归因到此威胁主体",
  "Attributed to this campaign": "归因到该攻击活动",
  "Attributed to this country": "归因到此国家/地区",
  "Attributed to this individual": "归因到此个体",
  "Attributed to this intrusion set": "归因到该入侵集合",
  "Attributed to this organization": "归因到该组织",
  "Attributed to this region": "归因到该区域",
  "Attribution": "属性",
  "Authentication": "验证",
  "Authentication strategies": "认证策略",
  "Author": "作者",
  "Auto new markings": "新標記的自動化",
  "Automatic": "自动",
  "Automatic references at file upload": "文件上传时自动引用",
  "Automatic trigger": "自动触发",
  "Automatically authorize this group to new marking definition": "自动将此组权限授权给新的标记定义",
  "Autonomous system": "自治系统",
  "Autonomous systems": "自治系统",
  "Averages of context relations": "上下文关系的平均值",
  "Avoid dependencies resolution": "避免依賴解析",
  "Back": "返回",
  "Background tasks": "后台任务",
  "Bad login or password": "用户名或密码错误",
  "Base URL": "基本URL",
  "Based on": "基于",
  "Basic information": "基础信息",
  "Belonging to this organization": "归属于该组织",
  "Browse the link": "浏览链接",
  "Bulk search": "批量搜索",
  "Bundle content": "捆绑包内容",
  "Bundle details": "捆绑包详情",
  "Bundles processed": "已处理的捆绑包",
  "CRITICAL": "UNDEFINED",
  "CSIRT": "CSIRT",
  "CSV file": "CSV文件",
  "Campaign": "攻击活动",
  "Campaigns": "攻击活动",
  "Cancel": "取消",
  "Capabilities": "能力",
  "Cards view": "卡片视图",
  "Cascade delete": "級聯刪除",
  "Case priority": "優先順位",
  "Case severity": "重大度",
  "Category": "类别",
  "Channel": "渠道",
  "Channel type": "渠道类型",
  "Channel types": "渠道类型",
  "Channels": "频道",
  "Cities": "城市",
  "City": "城市",
  "Cleaning up this rule on the existing data": "正在清除现有数据上的此规则",
  "Clear": "清除",
  "Clear all works": "清除所有作品",
  "Clear filters": "清除过滤器",
  "Clear this connector": "清除此连接器",
  "Close": "关闭",
  "Cloud Control Plane": "云控制平面",
  "Collapse": "坍塌",
  "Color": "颜色",
  "Column": "欄",
  "Columns": "列",
  "Commit message": "提交消息",
  "Commit message when updating data from the UI.": "从UI更新数据时提交消息",
  "Commit messages": "提交消息",
  "Compare": "对比",
  "Completed tasks": "已完成的任务",
  "Completed works": "已完成的工作",
  "Confidence": "置信度",
  "Confidence level": "置信级别",
  "Configuration": "配置",
  "Confirmation": "确认",
  "Confirmation required": "需要确认",
  "Connected": "连接的",
  "Connected workers": "已连接的工作器",
  "Connection successfully verified": "已成功验证连接",
  "Connector": "连接器",
  "Connectors": "连接器",
  "Connectors & workers": "连接器和工作器",
  "Constituent": "组成",
  "Contact information": "联系信息",
  "Containers": "容器",
  "Containers (reports, notes & opinions)": "容器(报告、注释和建议)",
  "Content": "内容",
  "Context relations": "上下文关系",
  "Continue": "继续",
  "Copied to clipboard": "已復製到剪貼板",
  "Copy": "複製",
  "Copy disabled: too many selected elements (maximum number of elements for a copy: ": "複製已關閉：選取元素過多（複製的最大元素數：",
  "Copy/paste text content": "复制/粘贴文本内容",
  "Correlate": "关联",
  "Correlation view": "关联视图",
  "Count": "总数",
  "Countries": "国家/地区",
  "Country": "国家/地区",
  "Course of action": "应对措施",
  "Courses of action": "应对措施",
  "Courses of action view": "应对措施视图",
  "Create": "创建",
  "Create a TAXII collection": "创建TAXII集合",
  "Create a campaign": "创建攻击活动",
  "Create a case incident": "创建个案事件",
  "Create a channel": "创建频道",
  "Create a city": "创建城市",
  "Create a country": "创建国家/地区",
  "Create a course of action": "创建应对措施",
  "Create a data component": "創建資料元件",
  "Create a data source": "创建数据源",
  "Create a feed": "创建提要",
  "Create a feedback": "创建反馈",
  "Create a file": "创建文件",
  "Create a group": "创建组",
  "Create a individual": "创建个体",
  "Create a kill chain phase": "创建杀伤链阶段",
  "Create a label": "创建标签",
  "Create a live stream": "创建实时流",
  "Create a live trigger": "UNDEFINED",
  "Create a malware": "创建恶意软件",
  "Create a marking definition": "创建标记定义",
  "Create a narrative": "创建叙述",
  "Create a nested relationship": "创建嵌套关系",
  "Create a note": "创建注释",
  "Create a opinions": "UNDEFINED",
  "Create a position": "創建職位",
  "Create a region": "创建区域",
  "Create a regular digest": "UNDEFINED",
  "Create a relationship": "创建关系",
  "Create a report": "创建报告",
  "Create a retention policy": "创建保留策略",
  "Create a role": "创建角色",
  "Create a sector": "创建部门",
  "Create a sighting": "创建目击",
  "Create a status": "创建状态",
  "Create a status template": "創建狀態範本",
  "Create a subscription": "创建一个订阅",
  "Create a synchronizer": "创建一个同步器",
  "Create a system": "创建系统",
  "Create a threat actor": "创建威胁主体",
  "Create a tool": "创建攻击工具",
  "Create a user": "创建用户",
  "Create a vocabulary": "UNDEFINED",
  "Create a vulnerability": "创建脆弱性",
  "Create a workbench": "创建工作区",
  "Create a workspace": "创建工作区",
  "Create an area": "创建区域",
  "Create an artifact": "创建工件",
  "Create an attack pattern": "创建攻击模式",
  "Create an attribute": "创建属性",
  "Create an entity": "创建实体",
  "Create an event": "创建活动",
  "Create an external reference": "创建外部引用",
  "Create an incident": "创建安全事件",
  "Create an indicator": "创建攻击指标",
  "Create an indicator from this observable": "从该可观测数据创建攻击指标",
  "Create an infrastructure": "创建基础设施",
  "Create an intrusion set": "创建入侵集合",
  "Create an observable": "创建可观测数据",
  "Create an observed data": "创建可观测数据",
  "Create an opinion": "创建意见",
  "Create an organization": "创建组织",
  "Create external reference at upload": "UNDEFINED",
  "Created entities": "创建的实体",
  "Created the": "已创建",
  "Creation": "UNDEFINED",
  "Creation date": "创建日期",
  "Creation date (in this platform)": "创建日期(在此平台中)",
  "Creator": "创建者",
  "Creators": "創作者",
  "Current password": "前密码",
  "Current state": "当前状态",
  "Custom dashboard": "自定义仪表盘",
  "Custom dashboards": "自定义仪表盘",
  "Dark": "暗色",
  "Dark (with background)": "暗色(带背景)",
  "Dark (without background)": "暗色(无背景)",
  "Dashboard": "仪表盘",
  "Dashboard settings": "仪表盘设置",
  "Data": "数据",
  "Data component": "數據元件",
  "Data components": "數據元件",
  "Data curation": "数据管理",
  "Data import": "数据导入",
  "Data import and analyst workbenches": "UNDEFINED",
  "Data sharing": "数据共享",
  "Data source": "数据源",
  "Data sources": "数据源",
  "Data type": "数据类型",
  "Date": "日期",
  "Date reference": "日期引用",
  "Default": "默认",
  "Default hidden entity types": "UNDEFINED",
  "Default mandatory attributes": "默认强制属性",
  "Default membership": "默認成員資格",
  "Default value": "默认值",
  "Definition": "定义",
  "Delete": "删除",
  "Delete the element if no other containers contain it": "如果沒有其他容器包含該元素，則刪除該元素",
  "Delete this file": "删除此文件",
  "Delete this workbench": "删除此工作区",
  "Deletion": "UNDEFINED",
  "Demo credentials": "Demo凭证",
  "Dependencies": "依赖",
  "Description": "描述",
  "Details": "详情",
  "Digest with multiple notifications": "UNDEFINED",
  "Direct Update": "UNDEFINED",
  "Direct relations creations": "直接关系创建",
  "Direct targeting of this country": "直接针对该国家/地区",
  "Direct targeting of this region": "直接针对该区域",
  "Direct targeting of this sector": "直接针对该部门",
  "Directories": "目录",
  "Directory": "目录",
  "Disable": "禁用",
  "Disable 3D mode": "禁用3D模式",
  "Disable forces": "禁用强制",
  "Disable tree horizontal mode": "禁用水平树形模式",
  "Disable tree vertical mode": "禁用垂直树形模式",
  "Disable two-factor authentication": "禁用双重身份验证",
  "Disabled": "禁用",
  "Disconnected": "断开连接的",
  "Display as": "显示为",
  "Display global knowledge with filters and criteria.": "使用过滤器和标准显示全球知识。",
  "Display notes": "显示注释",
  "Display specific knowledge using relationships and filters.": "使用关系和过滤器显示特定知识。",
  "Display time range selector": "显示时间范围选择器",
  "Distribution": "分布:",
  "Distribution of entities": "实体分布",
  "Distribution of opinions": "意见分布",
  "Distribution of relations": "关系分布",
  "Distribution of relations (including inferred)": "关系分布(包含推理)",
  "Distribution of sources": "源分布",
  "Distribution:": "分布:",
  "Do you want to browse this external link?": "是否要浏览此外部链接？",
  "Do you want to clear the works of this connector?": "你想清除这个连接器的工作吗？",
  "Do you want to create a STIX Indicator from this observable?": "是否要从此可观测数据创建一个STIX攻击指标？",
  "Do you want to delete these entities?": "是否要删除这些实体？",
  "Do you want to delete this area?": "是否要删除此区域?",
  "Do you want to delete this attack pattern?": "是否要删除此攻击模式？",
  "Do you want to delete this attribute?": "是否要删除此属性？",
  "Do you want to delete this campaign?": "是否要删除此攻击活动？",
  "Do you want to delete this case incident ?": "是否要删除此案例事件？",
  "Do you want to delete this city?": "是否要删除此城市？",
  "Do you want to delete this country?": "是否要删除此国家/地区？",
  "Do you want to delete this course of action?": "是否要删除此应对措施？",
  "Do you want to delete this data component?": "是否要刪除此資料元件？",
  "Do you want to delete this data source?": "你想删除这个数据源吗?",
  "Do you want to delete this entity?": "是否要删除此实体？",
  "Do you want to delete this external reference?": "是否要删除此外部引用？",
  "Do you want to delete this feed?": "您要删除此提要吗？",
  "Do you want to delete this feedback ?": "要删除此反馈吗？",
  "Do you want to delete this file?": "你想删除这个文件吗？",
  "Do you want to delete this group?": "是否要删除此组？",
  "Do you want to delete this incident?": "是否要删除此安全事件？",
  "Do you want to delete this indicator?": "是否要删除此攻击指标？",
  "Do you want to delete this individual?": "是否要删除此个体？",
  "Do you want to delete this intrusion set?": "是否要删除此入侵集合？",
  "Do you want to delete this kill chain phase?": "是否要删除此杀伤链阶段？",
  "Do you want to delete this label?": "是否要删除此标签？",
  "Do you want to delete this live stream?": "是否要删除此实时流？",
  "Do you want to delete this malware?": "是否要删除此恶意软件？",
  "Do you want to delete this marking definition?": "是否要删除此标记定义？",
  "Do you want to delete this note?": "是否要删除此注释？",
  "Do you want to delete this observable?": "是否要删除此可观测数据？",
  "Do you want to delete this observed data?": "是否要删除此观测数据？",
  "Do you want to delete this organization?": "是否要删除此组织？",
  "Do you want to delete this region?": "是否要删除此区域？",
  "Do you want to delete this relation?": "是否要删除此关系？",
  "Do you want to delete this report?": "是否要删除此报告？",
  "Do you want to delete this role?": "是否要删除此角色？",
  "Do you want to delete this sector?": "是否要删除此部门？",
  "Do you want to delete this sighting?": "是否要删除此目击？",
  "Do you want to delete this status template?": "想要刪除此狀態範本？",
  "Do you want to delete this synchronizer?": "是否要删除此同步器？",
  "Do you want to delete this system?": "是否要删除此系统？",
  "Do you want to delete this threat actor?": "是否要删除此威胁主体？",
  "Do you want to delete this tool?": "是否要删除此工具？",
  "Do you want to delete this user?": "是否要删除此用户？",
  "Do you want to delete this vulnerability?": "是否要删除此脆弱性？",
  "Do you want to delete this widget?": "你想删除这个小部件吗？",
  "Do you want to delete this workbench?": "是否要丢弃此捆绑包?",
  "Do you want to delete this workspace?": "是否要删除此工作区？",
  "Do you want to disable this rule?": "是否要禁用该规则？",
  "Do you want to enable this rule?": "是否要启用该规则？",
  "Do you want to kill all the sessions of this user?": "是否要终止此用户的所有会话？",
  "Do you want to kill this session?": "是否要终止此会话？",
  "Do you want to remove the entity from this container?": "是否要从此容器中移除该实体？",
  "Do you want to remove the entity from this report?": "是否要从此报告中移除该实体？",
  "Do you want to remove the indicator from this observable?": "你想从这个技术元素中删除指标吗？",
  "Do you want to remove the observable from this indicator?": "是否要移除此攻击指标中移除该可观测数据？",
  "Do you want to remove these elements from this investigation?": "是否要从此调查中移除这些元素？",
  "Do you want to remove these elements from this report?": "是否要从此报告中移除这些元素？",
  "Do you want to remove this external reference?": "是否要移除此外部引用？",
  "Do you want to remove this job?": "您要删除此作业吗？",
  "Do you want to remove this note?": "是否要移除此注释？",
  "Do you want to remove this object?": "是否要删除此对象？",
  "Do you want to remove this opinion?": "是否要移除此意见？",
  "Do you want to remove this report?": "是否要移除此报告？",
  "Do you want to remove this status?": "您要删除此状态吗？",
  "Do you want to reset the state of this connector?": "是否要重置此连接器的状态？",
  "Do you want to start this synchronizer?": "是否要启动此同步器？",
  "Do you want to stop this synchronizer?": "是否要删除此同步器？",
  "Domain": "域",
  "Domain names": "域名",
  "Donut": "甜甜圈",
  "Donut chart": "圆环图",
  "Download": "下载",
  "Download this file": "下载此文件",
  "EXPIRATION_SCHEDULER": "过期计划程序",
  "EXTERNAL_IMPORT": "外部导入",
  "Each tick value must be between min and max value": "每个刻度值必须介于最小值和最大值之间",
  "Edit the selected item": "编辑选中项",
  "Elasticsearch": "Elasticsearch",
  "Element will be rescan with all compatible activated rules": "将使用所有兼容的激活规则重新扫描元素",
  "Elements successfully copied": "已成功複製元素",
  "Email": "电子邮箱",
  "Email address": "邮件地址",
  "Email addresses": "邮箱地址",
  "Email subject": "电子邮件主题",
  "Emails": "电子邮件",
  "Enable": "启用",
  "Enable 3D mode": "启用3D模式",
  "Enable commit messages": "启用提交消息",
  "Enable forces": "启用强制",
  "Enable this feature": "UNDEFINED",
  "Enable tree mode": "启用树形模式",
  "Enable two-factor authentication": "启用双重身份验证",
  "Enabled": "启用",
  "Enabled import connectors": "已启用的导入连接器",
  "Enabled the ": "启用该",
  "End date": "结束日期",
  "Enforce reference": "强制引用",
  "Enforce reference on entity type": "对实体类型强制引用",
  "Enforce references": "UNDEFINED",
  "Enforce two-factor authentication": "强制执行两因素身份验证",
  "Enrich": "丰富",
  "Enrichment": "富化",
  "Enrichment connectors": "富化连接器",
  "Entities": "实体",
  "Entities distribution": "实体分布",
  "Entities view": "实体视图",
  "Entity": "实体",
  "Entity aliases": "实体别名",
  "Entity details": "实体详情",
  "Entity enrichment": "实体充实",
  "Entity settings": "实体设置",
  "Entity type": "实体类型",
  "Entity types": "实体类型",
  "Entity usage": "实体使用",
  "Error": "错误",
  "Event types": "事件类型",
  "Events": "事件",
  "Every 1 hour": "每1小时",
  "Every 24 hours": "每24小时",
  "Every month": "每个月",
  "Every week": "每周",
  "Everything": "所有事情",
  "Evidences": "证据",
  "Evolution": "演变",
  "Example": "示例",
  "Explanation": "解释",
  "Explore": "探索",
  "Explore the attack campaigns of the dataset through time and involved entities.": "通过时间和相关实体探索数据集的攻击活动。",
  "Explore the kill chains of entities through time and other contextual information like campaigns or incidents.": "通过时间和其它上下文信息（如攻击活动或安全事件）探索实体的杀伤链",
  "Explore the observables of the dataset though time to visualize clusters and correlations.": "通过时间探索数据集的可观测数据，以进行可视化聚类和关联。",
  "Explore the techniques, tactics and procedures of the dataset through time and entities who used its.": "通过时间和使用数据集的实体探索数据集的TTPs（技术、战术和程序）。",
  "Explore the victims and the targets of the dataset through space and time.": "通过空间和时间探索数据集的受害者和目标。",
  "Explore the vulnerabilities used by entities through time and kill chain phases.": "通过时间和杀伤链探索实体使用的脆弱性.",
  "Export": "导出",
  "Export as PDF": "导出成PDF",
  "Export as image": "导出成图像",
  "Export data in CSV": "以CSV格式导出数据",
  "Export format": "导出格式",
  "Export is disabled because too many entities are targeted (maximum number of entities is: ": "匯出被禁用，因為目標實體太多（最大實體數為：",
  "Export successfully started": "导出已成功启动",
  "Export the entity": "导出实体",
  "Export to CSV": "导出成CSV",
  "Export to PDF": "导出成PDF",
  "Export to document (pdf)": "导出到文档(pdf)",
  "Export to image": "导出成图像",
  "Export to image (png)": "导出到图像(png)",
  "Export type": "导出类型",
  "Exported files": "导出的文件",
  "Exports list": "导出列表",
  "Exports panel": "导出面板",
  "External ID": "外部ID",
  "External authentication": "外部认证",
  "External references": "外部引用",
  "External references files": "外部引用文件",
  "False positive": "误报",
  "Feedback": "UNDEFINED",
  "Feeds (CSV)": "供稿 (CSV)",
  "Field": "字段",
  "Field type": "字段类型",
  "File MD5 hash": "文件MD5哈希",
  "File SHA1 hash": "文件SHA1哈希",
  "File SHA256 hash": "文件SHA256哈希",
  "File and associated external reference successfully removed": "已成功刪除檔和關聯的外部引用",
  "File hash": "文件哈希",
  "File hashes": "文件哈希",
  "File information": "文件信息",
  "File name": "文件名称",
  "File path": "文件路径",
  "File successfully removed": "已成功移除文件",
  "File successfully uploaded": "已成功上传文件",
  "File successfully uploaded and associated external reference successfully created": "已成功上載檔並成功創建關聯的外部引用",
  "File to import": "要导入的文件",
  "Files": "文件",
  "Files & history": "文件 & 历史",
  "Filter authors (created by)": "过滤作者(创建者)",
  "Filter by": "过滤条件",
  "Filter entity types": "过滤实体类型",
  "Filter marking definitions": "过滤标记定义",
  "Filters": "过滤器",
  "First obs.": "首次观测.",
  "First observed": "首次观测",
  "First seen": "首次看到",
  "Firstname": "名字",
  "Fit graph to canvas": "将图表适配到画布",
  "Force now": "立即生效",
  "Free text import": "自由文本导入",
  "Friday": "UNDEFINED",
  "From name": "源名称",
  "From type": "源类型",
  "Full export (entity and first neighbours)": "完全导出(实体和第一个邻居)",
  "Functional date": "功能日期",
  "GRAPHQL_API": "API GraphQL",
  "General": "通用",
  "Generate an export": "生成导出",
  "Generated the": "已生成",
  "Generation in progress...": "正在生成...",
  "Global": "全局",
  "Global keyword": "全局关键词",
  "Global kill chain": "全局杀伤链",
  "Global parameters": "全局参数",
  "Goals": "目标",
  "Goals (1 / line)": "目标(1/行)",
  "Good": "好",
  "Granted by default": "默认授予",
  "Granted by default at user creation": "在用户创建时默认授予",
  "Graph": "图标",
  "Graph type": "图表类型",
  "Graph view": "图形视图",
  "Groupings": "UNDEFINED",
  "Groups": "组",
  "Groups permissions on data marking is not fully implemented yet.": "对数据标记的组权限尚未完全实现。",
  "Groups with this role": "具有此角色的組",
  "HISTORY_MANAGER": "历史经理",
  "HTML files": "HTML 文件",
  "Heatmap": "热图",
  "Hidden entity types": "隐藏的实体类型",
  "Hidden in interface": "隐藏在界面中",
  "Hidden in roles": "隱藏在角色中",
  "Hide in the platform": "UNDEFINED",
  "High": "高的",
  "History": "历史",
  "Horizontal Bar": "单杠",
  "Host": "主机",
  "INTERNAL_ENRICHMENT": "富化",
  "INTERNAL_EXPORT_FILE": "导出文件",
  "INTERNAL_IMPORT_FILE": "导入文件",
  "IPv4 address": "IPv4地址",
  "IPv4 addresses": "IPv4地址",
  "IPv6 address": "IPv6地址",
  "IPv6 addresses": "IPv6地址",
  "Identities": "身份",
  "Identity": "身份",
  "Impacted": "影响",
  "Implant": "植入",
  "Implementation languages": "实现语言",
  "Import": "导入",
  "Import data": "导入数据",
  "Import successfully asked": "请求导入成功",
  "Import type": "导入类型",
  "In OpenCTI, a predictable STIX ID is generated based on one or multiple attributes of the entity.": "在 OpenCTI 中，基于实体的一个或多个属性生成可预测的 STIX ID。",
  "In all the database": "在所有数据库中",
  "In progress messages": "进行中的消息",
  "In progress tasks": "进行中的任务",
  "In progress works": "进行中的工作",
  "In this report, ": "在这份报告中，",
  "Incident": "安全事件",
  "Incident Date": "事件日期",
  "Incident type": "事件类型",
  "Incidents": "安全事件",
  "Include headers in the feed": "在提要中包含标题",
  "Indicator": "攻击指标",
  "Indicator pattern": "攻击指标模式",
  "Indicator type": "攻击指标类型",
  "Indicator types": "攻击指标类型",
  "Indicators": "攻击指标",
  "Indicators composed with this observable": "由该可观测数据组成的攻击指标",
  "Indicators/observables generation": "指标/可观察的生成",
  "Individual": "个体",
  "Individuals": "个体",
  "Inference explanation": "推理解释",
  "Inference rules": "推理规则",
  "Inferences": "引用",
  "Inferred knowledge based on the rule ": "基于规则推理的知识",
  "Information": "信息",
  "Infrastructure types": "基础设施类型",
  "Infrastructures": "基础设施",
  "Ingested entities": "引入的实体",
  "Initiator": "发起者",
  "Intrusion set": "入侵集合",
  "Intrusion sets": "入侵集合",
  "Investigate": "调查",
  "Investigations": "UNDEFINED",
  "Is family": "是同一家族",
  "Is family?": "是否是同一家族?",
  "JSON content": "JSON内容",
  "Just in the report": "就在报告中",
  "Key": "键",
  "Kill chain": "杀伤链",
  "Kill chain name": "杀伤链名称",
  "Kill chain phase": "杀伤链阶段",
  "Kill chain phases": "杀伤链阶段",
  "Kill chain view": "杀伤链视图",
  "Kill chains": "杀伤链",
  "Knowledge": "知识",
  "Knowledge entity": "知识实体",
  "Knowledge graph": "知识图谱",
  "Knowledge update (except indicators & observables)": "知识更新(攻击指标和可观测数据除外)",
  "Label": "标签",
  "Labels": "标签",
  "Labels & Attributes": "标签和属性",
  "Language": "语言",
  "Last": "UNDEFINED",
  "Last 24 hours": "最近24小时",
  "Last 6 months": "最近6个月",
  "Last 7 days": "最近7天",
  "Last execution": "上次执行时间",
  "Last ingested reports (creation date in the platform)": "上次摄取的报告（平台中的创建日期）",
  "Last modified": "上次修改",
  "Last modified entities": "最后修改的实体",
  "Last month": "最近1个月",
  "Last notes": "最后注释",
  "Last obs.": "上次观测.",
  "Last observables": "最后的可观测数据",
  "Last observed": "上次观测",
  "Last processed message": "上次处理的消息",
  "Last reports": "最后报告",
  "Last reports about the entity": "关于该实体的最后报告",
  "Last run": "上次运行",
  "Last run:": "上次运行:",
  "Last seen": "上次看到",
  "Last targeted organizations in this sector": "在此部门中最近被针对的组织",
  "Last update": "上次更新",
  "Last year": "最近1年",
  "Lastname": "姓氏",
  "Latest created relationships": "最新创建的关系",
  "Latest reports about this entity": "关于该实体的最新报告",
  "Latest reports written by this entity": "该实体编写的最新报告",
  "Latitude": "UNDEFINED",
  "Launch": "启动",
  "Launch a background task": "启动后台任务",
  "Launch an import": "启动导入",
  "Launch an import of this file": "启动此文件的导入",
  "Launch rescan": "启动重新扫描",
  "Layers": "层",
  "Let the field empty to grant all users": "将该字段设置为空，以授权给所有用户",
  "Level": "级别",
  "Light": "浅色",
  "Light (with background)": "浅色(带背景)",
  "Light (without background)": "浅色(无背景)",
  "Likelihood": "可能性",
  "Limit": "限制",
  "Limits": "UNDEFINED",
  "Line chart": "折线图",
  "Lines view": "线条视图",
  "Linked entities": "链接实体",
  "Linked entity": "链接实体",
  "Linked knowledge": "链接知识",
  "Linked threat": "链接威胁",
  "Linked threat(s)": "链接威胁",
  "Links with threats": "链接威胁",
  "List": "リスト",
  "List of entities": "实体列表",
  "Live streams": "实时流",
  "Live trigger": "UNDEFINED",
  "Localized in this country": "在此国家/地区本地化",
  "Localized in this region": "在此区域本地化",
  "Location": "位置",
  "Locations": "位置",
  "Locations of this individual": "此个体的位置",
  "Locations of this organization": "该组织的位置",
  "Log sources": "日志源",
  "Log sources (1 / line)": "日志源(1/行)",
  "Login": "登录",
  "Logout": "注销",
  "Longitude": "UNDEFINED",
  "Low": "低",
  "MAC address": "MAC地址",
  "MAC addresses": "MAC地址",
  "MEDIUM": "UNDEFINED",
  "Main observable type": "主要可观测类型",
  "Make this stream public and available to anyone": "将此流公开并提供给任何人",
  "Malicious": "恶意",
  "Malware": "恶意软件",
  "Malware types": "恶意软件类型",
  "Malwares": "恶意软件",
  "Manage a container": "理容器",
  "Manage an entity": "管理实体",
  "Manage an observable": "管理一个可观察的",
  "Mandatory attributes": "必須属性",
  "Manual": "手动",
  "Map": "地图",
  "Markdown files": "降价文件",
  "Markdown source": "Markdown源",
  "Marking": "标记",
  "Marking definitions": "标记定义",
  "Markings": "标记",
  "Matrix view": "矩阵视图",
  "Max marking definition level": "最大标记定义级别",
  "Max retention": "最长保留期",
  "Maximum": "UNDEFINED",
  "Maximum retention days": "最长保留天数",
  "Med": "中等的",
  "Members": "成员",
  "Merge": "归并",
  "Merge entities": "归并实体",
  "Merged entity": "归并的实体",
  "Message": "UNDEFINED",
  "Metrics": "指标",
  "MinIO": "MinIO",
  "Mini map": "小地圖",
  "Minimum": "UNDEFINED",
  "Minimum one outcome": "UNDEFINED",
  "Minimum one trigger": "UNDEFINED",
  "Mitigated attack patterns": "缓解的攻击模式",
  "Moderate": "中",
  "Modification": "UNDEFINED",
  "Modification date": "修改日期",
  "Modified": "修改的",
  "Monday": "UNDEFINED",
  "Month": "月",
  "Month day": "UNDEFINED",
  "More": "更多",
  "Most recent history": "最近历史操作",
  "Multiple": "UNDEFINED",
  "Multiple entities selected": "已选择多个实体",
  "Mutex": "互斥体",
  "NOTIFICATION_MANAGER": "通知生成管理器",
  "Name": "姓名",
  "Narrative": "叙述",
  "Narratives": "叙事",
  "Nested objects": "嵌套对象",
  "Network": "网络",
  "Never enabled": "从未启用",
  "Never generated": "从未生成",
  "New alias": "新别名",
  "New password": "新密码",
  "No": "否",
  "No available options": "没有可用的选项",
  "No available public stream on this platform": "UNDEFINED",
  "No connector available for the selected entities.": "没有可用于选定实体的连接器。",
  "No connectors are enabled on this platform.": "此平台未启用任何连接器。",
  "No connectors for this type of entity": "此类型的实体没有连接器",
  "No description": "UNDEFINED",
  "No description of this targeting": "没有关于此针对的描述",
  "No description of this usage": "没有关于此用法的描述",
  "No enrichment connectors on this platform": "此平台上没有富化连接器",
  "No entities of this type has been found.": "未找到此类型的实体。",
  "No entities were found for this search.": "未找到此搜索的实体。",
  "No export connector available to generate an export": "没有可以用于生成导出的导出连接器",
  "No file for the moment": "暂无文件",
  "No file selected.": "未选择文件。",
  "No files in this category.": "此类别中没有文件。",
  "No history about this entity.": "关于此实体的历史。",
  "No history about this relationship.": "没有关于此关系的历史",
  "No import connectors on this platform": "此平台没有导入连接器",
  "No label": "无标签",
  "No notes about this entity yet.": "尚无关于此实体的注释",
  "No potential duplicate entities has been found.": "未找到潜在的重复实体",
  "No relations history about this entity.": "尚无关于此实体的关系历史",
  "No reports about this entity.": "没有关于此实体的报告。",
  "No task": "没有任务",
  "No value": "没有价值",
  "No widget in this workspace": "此工作区没有控件",
  "No work": "没有工作",
  "None": "无",
  "Nonee": "无",
  "Not Specified": "未指定",
  "Not aplicable": "不适用",
  "Not applicable": "不适合",
  "Note types": "筆記類型",
  "Notes": "UNDEFINED",
  "Notes about this entity": "关于此实体的注释",
  "Notes about this relationship": "关于此关系的注释",
  "Notification": "UNDEFINED",
  "Notifications and triggers": "UNDEFINED",
  "Number": "数目",
  "Number observed": "观测到的数量",
  "Number of": "数目",
  "Number of elements": "元素数量",
  "Number of entities": "实体数量",
  "Number of errors": "错误数量",
  "Number of relationships": "关系数量",
  "Number of target relations": "目标关系数目",
  "Number of targeting": "针对的数量",
  "OR": "UNDEFINED",
  "Object": "UNDEFINED",
  "Objective": "目标",
  "Observable type": "可观测类型",
  "Observable types": "可观测类型",
  "Observable value": "可观测值",
  "Observables": "可观测数据",
  "Observables and indicators conversion": "可观测数据和指标转换",
  "Observables distribution": "可观测数据分布",
  "Observables roles": "可观测角色",
  "Observations": "可观测数据",
  "Observed data": "可观测数据",
  "Observed datas": "可观测数据",
  "One keyword by line or separated by commas": "一个关键字逐行或以逗号分隔",
  "Only contextual": "仅上下文",
  "Open export panel": "打开导出面板",
  "Open the suggestions": "打开建议",
  "OpenCTI - Cyber threat intelligence platform": "OpenCTI - 网络威胁情报平台",
  "OpenCTI version": "OpenCTI版本",
  "Operations completed": "已完成的操作",
  "Opinion": "UNDEFINED",
  "Opinions": "UNDEFINED",
  "Optional, you may want to subscribe to specific entities.": "可选，你可能希望订阅特定实体。",
  "Options": "选项",
  "Order": "次序",
  "Organization": "组织",
  "Organization type": "组织类型",
  "Organizations": "组织",
  "Organizations restriction": "组织限制",
  "Organizations sharing": "UNDEFINED",
  "Originates from": "来源于",
  "Origins of the malware": "该恶意软件的起源",
  "Origins of the targeting": "针对的起源",
  "Origins of this campaign": "该攻击活动的起源",
  "Origins of this incident": "该安全事件的起源",
  "Origins of this intrusion set": "该入侵集合的起源",
  "Other": "其它",
  "Other STIX IDs": "其它STIX IDs",
  "Others": "UNDEFINED",
  "Out of Range": "超出范围",
  "Overview": "概况",
  "Owner": "所有者",
  "PDB Path": "PDB路径",
  "PDF files": "PDF 文件",
  "PDF viewer": "PDF查看器",
  "PUBLISHER_MANAGER": "通知發布經理",
  "Parameters": "参数",
  "Parent attack patterns": "父攻击模式",
  "Parent regions": "父区域",
  "Parent sectors": "父部门",
  "Part of this sector": "此部门的一部分",
  "Partner": "伙伴",
  "Password": "密码",
  "Pattern": "模式",
  "Pattern type": "模式类型",
  "Period": "UNDEFINED",
  "Periodicity": "周期性",
  "Permissions": "权限",
  "Personal motivations": "个人动机",
  "Perspective": "看法",
  "Phase name": "阶段名称",
  "Pie chart": "饼图",
  "Platform": "平台",
  "Platform favicon URL": "平台图标 URL",
  "Platform organization": "平台組織",
  "Platform title": "平台标题",
  "Platforms": "平台",
  "Played role": "扮演的角色",
  "Playground": "Playground",
  "Positions": "UNDEFINED",
  "Postal code": "郵遞區號",
  "Potential duplicate entities": "潜在重复实体",
  "Preview": "预览",
  "Primary motivation": "主要动机",
  "Priority": "优先事项",
  "Processed time": "处理时间",
  "Processing status": "处理状态",
  "Profile": "配置",
  "Progress": "进展",
  "Proxy": "代理",
  "Public stream": "公共流",
  "Public stream collections": "UNDEFINED",
  "Publication": "发布",
  "Publication date": "发布日期",
  "Queued bundles": "排队的捆绑包",
  "RETENTION_MANAGER": "保留管理器",
  "RFIs": "UNDEFINED",
  "RULE_ENGINE": "规则引擎",
  "RabbitMQ": "RabbitMQ",
  "Radar chart": "雷达图",
  "Rating": "评分",
  "Read operations": "读取操作",
  "Received time": "接收时间",
  "Redirecting to the Content section": "重定向到“內容”部分",
  "Redirecting to the Knowledge section": "重定向至“知識”部分",
  "Redirecting to the Overview section": "重定向至「概述」部分",
  "Redis": "Redis",
  "Reference knowledge update": "引用知识更新",
  "Reference modification": "引用修改",
  "References": "引用",
  "Refresh the knowledge using this connector": "使用此连接器刷新知识",
  "Region": "区域",
  "Regions": "区域",
  "Regions, countries and cities": "区域、国家/地区和城市",
  "Registered connectors": "已注册连接器",
  "Registration": "注册",
  "Registry": "注册表",
  "Registry key": "注册表键",
  "Registry key value": "注册表键值",
  "Regular digest": "UNDEFINED",
  "Related cases": "相关案例",
  "Related entities": "相关实体",
  "Related entities (generic relation \"related-to\")": "相关实体(通用关系\"related-to\")",
  "Related reports": "相关报道",
  "Related to this country": "关联到此国家/地区",
  "Related to this organization": "关联到该组织",
  "Related to this region": "关联到该区域",
  "Relation": "关系",
  "Relation type": "关系类型",
  "Relations": "关系",
  "Relations of the entity": "实体关系",
  "Relations to other entities": "与其它实体的关系",
  "Relations to threats": "与威胁的关系",
  "Relationship": "关系",
  "Relationship type": "关系类型",
  "Relationship types": "关系类型",
  "Relationships": "关系",
  "Relative time": "相对时间",
  "Reliability": "可靠性",
  "Remote OpenCTI URL": "远程OpenCTI URL",
  "Remote OpenCTI configuration": "远程 OpenCTI 配置",
  "Remote OpenCTI stream ID": "远程OpenCTI流ID",
  "Remote OpenCTI token": "远程OpenCTI token",
  "Remove": "移除",
  "Remove from the container": "从容器中取出",
  "Remove from this entity": "从该实体中移除",
  "Remove from this object": "从该对象中移除",
  "Remove selected items": "移除选中项",
  "Renew": "更新",
  "Replace": "替换",
  "Report": "报告",
  "Report type": "报告类型",
  "Report types": "报告类型",
  "Reports": "报告",
  "Reports distribution": "报告分布",
  "Required permissions": "所需权限",
  "Rescan": "重新扫描",
  "Reset": "重启",
  "Reset filters": "重置过滤器",
  "Reset the connector state": "重置连接器状态",
  "Resource level": "资源级别",
  "Response type": "響應類型",
  "Retention policies": "保留策略",
  "Revoked": "撤销",
  "Rich editor": "富编辑器",
  "Role": "角色",
  "Roles": "角色",
  "Rolling time": "查询间隔",
  "Rolling time (in minutes)": "查询间隔（分钟）",
  "Rule entity rescan": "规则实体重新扫描",
  "Rule has been cleaned up on the existing data": "已清除现有数据上的规则",
  "Rule rescan": "规则重新扫描",
  "Rule rescan (engine is disabled)": "规则重新扫描（引擎已禁用）",
  "Rules engine": "规则引擎",
  "Running": "开始",
  "STIX Version": "STIX版本",
  "STIX2 bundle": "STIX2捆绑包",
  "STREAM": "流",
  "SUBSCRIPTION_MANAGER": "订阅管理器",
  "SYNC_MANAGER": "同步管理器",
  "Saturday": "UNDEFINED",
  "Save": "UNDEFINED",
  "Scope": "范围",
  "Score": "分数",
  "Search": "搜索",
  "Search for a threat...": "搜索威胁...",
  "Search for an entity": "搜索实体",
  "Search for multiple entities": "搜索多个实体",
  "Secondary motivations": "次要动机",
  "Sector": "部门",
  "Sectors": "部门",
  "Sectors and organizations": "部门和组织",
  "Select a relationship": "更新关系",
  "Select all nodes": "选择所有节点",
  "Select by entity type": "按实体类型选择",
  "Select your file": "选择你的文件",
  "Selected connectors": "选定的连接器",
  "Selected entities": "选定的实体",
  "Selected rules": "选定的规则",
  "Sender": "发件人",
  "Sender email address": "发件人电子邮件地址",
  "Separator": "分隔器",
  "Settings": "设置",
  "Settings have been updated": "设置已更新",
  "Severity": "严重程度",
  "Share": "分享",
  "Share with an organization": "与组织共享",
  "Sightings": "目击",
  "Sightings distribution": "目击分布",
  "Sign in": "登录",
  "Signatures": "签名",
  "Simple export (just the entity)": "简单导出(仅实体)",
  "Size": "大小",
  "Sophistication": "复杂度",
  "Sort by": "排序方式",
  "Source": "UNDEFINED",
  "Source name": "源名称",
  "Standard STIX ID": "标准STIX ID",
  "Start": "开始",
  "Start date": "开始日期",
  "Start time": "开始时间",
  "Starting synchronization (empty = from start)": "開始同步(空的 = 從一開始)",
  "State": "状态",
  "Statistics": "统计",
  "Status": "状态",
  "Status templates": "状态模板",
  "Step": "步骤",
  "Stop": "结束",
  "Stop time": "停止时间",
  "Stream ID": "流 ID",
  "Street address": "街道位址",
  "Strong": "强",
  "Sub attack patterns": "子攻击模式",
  "Submit a feedback": "提交反馈",
  "Subregions": "子区域",
  "Subscriptions & digests": "订阅和摘要",
  "Subsectors": "子部门",
  "Sunday": "UNDEFINED",
  "Synchronization": "同步",
  "Synthesis of knowledge": "知识综合",
  "System": "系统",
  "Systems": "系统",
  "TASK_MANAGER": "任务管理器",
  "TAXII collections": "TAXII集合",
  "TTPs": "TTPs",
  "TTPs knowledge": "TTPs知识",
  "TTPs of threats": "威胁的TTPs",
  "TTPs through time": "按照时间TTPs",
  "Table": "表",
  "Table (top 10)": "表(前10个)",
  "Tactics": "战术",
  "Tactics matrix view": "战术矩阵视图",
  "Take deletions into account": "考虑删除",
  "Target": "UNDEFINED",
  "Targeted by this TTP": "被该TTP针对",
  "Targeted by this actor": "被此威胁主体针对",
  "Targeted by this intrusion set": "被此入侵集合针对",
  "Targeted by this malware": "被该恶意软件针对",
  "Targeted countries (3 last months)": "针对的国家/地区(最近3个月)",
  "Targeted entities": "针对的实体",
  "Targeted entity through time": "随时间推移的目标实体",
  "Targeted entity types": "针对的实体类型",
  "Targeted in this campaign": "被该攻击活动针对",
  "Targeted in this incident": "被该安全事件针对",
  "Targeting knowledge": "针对知识",
  "Targeting this country": "针对此国家/地区",
  "Targeting this individual": "针对此个体",
  "Targeting this organization": "针对该组织",
  "Targeting this region": "针对该区域",
  "Targeting this sector": "针对此部门",
  "Targeting this vulnerability": "针对该漏洞",
  "Targeting through time": "按时间针对",
  "Targeting types": "针对类型",
  "Task end time": "任务结束时间",
  "Task start time": "任务开始时间",
  "Tasks": "UNDEFINED",
  "Technical date": "技术日期",
  "Technical elements (indicators & observables)": "技术元素(攻击指标和可观测数据)",
  "Techniques": "技术",
  "Techniques matrix": "技术矩阵",
  "Text files": "文本文件",
  "The CSV file has been generated with the parameters of the view and is ready for download.": "CSV文件已使用视图的参数生成，并已准备好下载。",
  "The alias has been added": "别名已添加",
  "The code is not correct": "UNDEFINED",
  "The color must be written in hexadecimal. Example: #ff9800": "颜色必须以十六进制书写。示例：#ff9800",
  "The connector has been cleared": "连接器已清理",
  "The connector state has been reset": "连接器状态已重置",
  "The importation of the file has been started": "已开始导入文件",
  "The min value cannot be greater than max value": "最小值不能大于最大值",
  "The minimum value cannot be greater than maximum value": "UNDEFINED",
  "The password has been updated": "密码已更新",
  "The relations attached to selected entities will be copied to the merged entity.": "附加到选定实体的关系将复制到归并的实体中。",
  "The rule has been disabled, clean-up launched...": "该规则已禁用，清理已启动",
  "The rule has been enabled, rescan of platform data launched...": "该规则已启用，平台数据的重新扫描已启动",
  "The value is too long": "该值太长",
  "The value is too short": "该值太短",
  "The value must be a date (yyyy-MM-dd)": "该值必须是一个日期(yyyy-MM-dd)",
  "The value must be a datetime (yyyy-MM-dd hh:mm (a|p)m)": "该值必须是一个日期(yyyy-MM-dd hh:mm a)",
  "The value must be a datetime with seconds (yyyy-MM-dd hh:mm:ss (a|p)m)": "该值必须是一个日期(yyyy-MM-dd hh:mm:ss a)",
  "The value must be a number": "该值必须是一个数字",
  "The value must be an URL": "该值必须是一个URL",
  "The value must be an email address": "该值必须是一个邮件地址",
  "The value must be between min and max value": "该值必须介于最小值和最大值之间",
  "The value must be between minimum and maximum value": "UNDEFINED",
  "The value must be greater than or equal to 0": "该值必须大于或等于 0",
  "The value must be less than or equal to 100": "该值必须小于或等于 100",
  "The values do not match": "该值不匹配",
  "Theme": "主题",
  "This action will generate STIX patterns indicators from the selected observables.": "此操作将从选定的 observables 生成 STIX 模式指标。",
  "This action will generate observables from the selected indicators.": "此操作将从选定的指标生成 observables。",
  "This configuration enables an entity to automatically construct an external reference from the uploaded file.": "此配置使实体能够从上传的文件自动构建外部引用。",
  "This configuration enables the requirement of a reference message on an entity update.": "此配置启用了对实体更新的参考消息的要求。",
  "This configuration hide a specific entity type across the entire platform.": "此配置隐藏了整个平台的特定实体类型。",
  "This configuration is not available for this entity type": "此配置不适用于此实体类型",
  "This connector is active": "此连接器处于活动状态",
  "This connector is disconnected": "此连接器已断开连接",
  "This feature is not available yet.": "此功能尚不可用。",
  "This field is required": "此字段为必填项",
  "This field must be a number": "UNDEFINED",
  "This field must only contain alphanumeric chars, dashes and space": "此字段只能包含字母、数字、字符、下划线和空格",
  "This individual is now a user": "此个体现在是用户",
  "This individual is part of": "此个体是其一部分",
  "This malware has been used": "该恶意软件已经被使用",
  "This page is not found on this OpenCTI application.": "在此OpenCTI应用程序上找不到此页面。",
  "This panel shows by default the latest created entities, use the search to find more.": "此面板默认显示最新创建的实体，请使用搜索查找更多信息。",
  "This relation is inferred": "该关系是推理出来的",
  "This report contains too many objects to be displayed as a graph. We are working on a new visualization which will allow large graph to be displayed in the future.": "此报告包含的对象过多，无法显示为图形。我们正在研究一种新的可视化，这将允许展示更大的图形。",
  "This rule has been applied on the existing data": "该规则已应用于现有数据",
  "This sector does not have any description.": "此部门没有任何描述。",
  "Threat actor": "威胁主体",
  "Threat actor types": "威胁主体类型",
  "Threat actors": "威胁主体",
  "Threat hunting techniques": "威胁狩猎技术",
  "Threats": "威胁",
  "Threats targeting": "威胁针对",
  "Threats using this malware": "威胁使用该恶意软件",
  "Thursday": "UNDEFINED",
  "Ticks": "标记",
  "Time": "UNDEFINED",
  "Timeline": "列表",
  "Title": "标题",
  "To name": "目标名称",
  "To type": "目标类型",
  "To use this feature, your platform administrator must enable the according manager in the config.": "要使用此功能，您的平台管理員必須在配置中啟用相應的管理器。",
  "To use this feature, your platform administrator must enable the subscription manager in the config.": "要使用此功能，平台管理员必须在配置中启用订阅管理器。",
  "Token": "UNDEFINED",
  "Too many objects": "对象过多",
  "Tool": "攻击工具",
  "Tool types": "工具类型",
  "Tool usage": "工具用法",
  "Tool version": "工具版本",
  "Tools": "攻击工具",
  "Tools versions": "工具版本",
  "Top 10 active entities (3 last months)": "10大活跃实体(最近3个月)",
  "Top 10 threats targeting this entity": "针对此实体的10大威胁",
  "Top 10:": "Top 10:",
  "Top Labels (3 last months)": "最多标签(最近3个月)",
  "Total direct relations": "直接关系总数",
  "Total entities": "实体总数",
  "Total indicators": "攻击指标总数",
  "Total notes": "注释总数",
  "Total number of documents": "文档总数",
  "Total number of operations": "操作总数",
  "Total observables": "可观测数据总数",
  "Total pending inserts": "待处理插入总数",
  "Total processed messages": "已处理消息总数",
  "Total relations": "关系总数",
  "Total relationships": "关系总数",
  "Total reports": "报告总数",
  "Total workspaces": "工作区总数",
  "Triggering on": "UNDEFINED",
  "Triggers": "UNDEFINED",
  "Tuesday": "UNDEFINED",
  "Turn to user": "转向用户",
  "Two-factor authentication": "两因素身份验证",
  "Type": "类型",
  "Types": "UNDEFINED",
  "Types of the targeting": "针对的类型",
  "Types of the targets": "目标的类型",
  "URL": "URL",
  "Unauthorized action, please refresh your browser": "未授权的操作，请刷新浏览器",
  "Unfix the nodes and re-apply forces": "取消固定节点并重新应用强制",
  "Unique identifier": "唯一标识",
  "Unknown": "未知",
  "Unsupported": "不支持",
  "Update": "更新",
  "Update a TAXII collection": "更新TAXII集合",
  "Update a campaign": "更新攻击活动",
  "Update a case incident": "更新案例事件",
  "Update a channel": "更新频道",
  "Update a city": "更新城市",
  "Update a country": "更新国家/地区",
  "Update a course of action": "更新应对措施",
  "Update a data component": "更新數據元件",
  "Update a data source": "更新数据源",
  "Update a feed": "更新提要",
  "Update a feedback": "更新一个反馈",
  "Update a group": "更新组",
  "Update a individual": "更新个体",
  "Update a kill chain phase": "更新杀伤链阶段",
  "Update a label": "更新标签",
  "Update a live stream": "更新实时流",
  "Update a malware": "更新恶意软件",
  "Update a marking definition": "更新标记定义",
  "Update a narrative": "更新叙述",
  "Update a note": "更新注释",
  "Update a position": "更新職位",
  "Update a region": "更新区域",
  "Update a relationship": "更新关系",
  "Update a report": "更新报告",
  "Update a retention policy": "更新保留策略",
  "Update a role": "更新角色",
  "Update a sector": "更新部门",
  "Update a sighting": "更新目标",
  "Update a status": "更新状态",
  "Update a status template": "更新狀態範本",
  "Update a subscription": "更新一个订阅",
  "Update a synchronizer": "更新一个同步器",
  "Update a system": "更新系统",
  "Update a threat actor": "更新威胁主体",
  "Update a tool": "更新攻击工具",
  "Update a trigger": "UNDEFINED",
  "Update a user": "更新用户",
  "Update a vulnerability": "更新脆弱性",
  "Update a widget": "更新控件",
  "Update a workspace": "更新工作区",
  "Update an area": "更新区域",
  "Update an artifact": "更新工件",
  "Update an attack pattern": "更新攻击模式",
  "Update an attribute": "更新属性",
  "Update an country": "UNDEFINED",
  "Update an entity": "更新实体",
  "Update an event": "更新事件",
  "Update an external reference": "更新外部引用",
  "Update an incident": "更新安全事件",
  "Update an indicator": "更新攻击指标",
  "Update an infrastructure": "更新基础设施",
  "Update an intrusion set": "更新入侵集合",
  "Update an observable": "更新可观测数据",
  "Update an observed data": "更新可观测数据",
  "Update an organization": "更新组织",
  "Update and complete": "更新并完成",
  "Update entities": "更新实体",
  "Update opinion": "更新意见",
  "Updated the": "已更新",
  "Uploaded files": "已上传的文件",
  "Usage": "用法",
  "Use": "UNDEFINED",
  "Use 2FA authentication": "使用 2FA 身份驗證",
  "Use Alt + click to exclude items": "使用 Alt + 按兩下排除專案",
  "Used TTPs": "使用的TTPs",
  "Used by this actor": "被此威胁主体使用",
  "Used by this intrusion set": "被该入侵集合使用",
  "Used by this malware": "被该恶意软件使用",
  "Used in this campaign": "被该攻击活动使用",
  "Used in this incident": "被该安全事件使用",
  "Used tools": "用过的工具",
  "User interface": "UNDEFINED",
  "User responsible for data creation (empty = System)": "负责数据创建的用户（空 = System）",
  "User will be created with default groups.": "將使用預設組創建使用者。",
  "Users": "用户",
  "Using this TTP": "使用该TTP",
  "Using this tool": "使用该工具",
  "Valid from": "有效期从",
  "Valid until": "有效期至",
  "Validate": "验证",
  "Validate and send for import": "验证并发送以进行导入",
  "Validate this workbench": "验证此工作区",
  "Value": "值",
  "Values": "值",
  "Variants": "变种",
  "Variants of this malware": "该恶意软件的变种",
  "Vendor": "供应商",
  "Verify": "验证",
  "Verify SSL certificate": "验证SSL证书",
  "Versions": "版本",
  "Vertical Bar": "竖条",
  "Victimology": "受害者研究",
  "Victimology (countries)": "受害者学（国家）",
  "Victimology (regions)": "受害者学（地区）)",
  "Victimology (sectors)": "受害者学（部门）",
  "View": "视图",
  "View the item": "查看项目",
  "Visualization": "可视化",
  "Vulnerabilities": "脆弱性",
  "Vulnerability": "脆弱性",
  "Vulnerability usage": "脆弱性使用",
  "Webhook": "UNDEFINED",
  "Wednesday": "UNDEFINED",
  "Week day": "UNDEFINED",
  "When you specified the platform organization, data without any organization restriction will be accessible only for users that are part of the platform one": "當您指定平台組織時，沒有任何組織限制的數據將僅適用於屬於平台一的用戶",
  "Widget": "控件",
  "Windows scheduled tasks": "Windows计划任务",
  "Windows services": "Windows服务",
  "Work end time": "工作结束时间",
  "Work start time": "工作开始时间",
  "Workers statistics": "工作器统计",
  "Workflow": "工作流程",
  "Workflow of": "的工作流程",
  "Workflows": "工作流程",
  "Works": "工作",
  "Workspace": "工作区",
  "Workspaces": "工作区",
  "Write": "写入",
  "Write a note": "写注释",
  "Write operations": "写入操作",
  "Write something awesome...": "写一些很棒的东西...",
  "X509 Certificates": "X509证书",
  "Year": "年",
  "Yes": "是",
  "You are not allowed to do this.": "您这样操作不被允许。",
  "You do not have any access to the knowledge of this OpenCTI instance.": "您无权访问此OpenCTI实例的知识数据。",
  "You have no subscription for the moment.": "您暂时没有订阅。",
  "You have successfully logged out.": "您已成功注销。",
  "You must be logged in to do this.": "您必须登录才能执行此操作。",
  "You need to activate a two-factor authentication. Please type the code generated in your application.": "您需要激活双因素身份验证。请输入在您的应用程序中生成的代码。",
  "You need to validate your two-factor authentication. Please type the code generated in your application.": "您需要验证您的双因素身份验证。请输入在您的应用程序中生成的代码。",
  "You're targeting more than 1000 entities with this background task, be sure of what you're doing!": "您正在使用此后台任务针对超过1000个实体，请确保您正在执行的操作!",
  "_": "UNDEFINED",
  "added a note": "添加了注释",
  "day": "UNDEFINED",
  "entities": "实体",
  "entity_Administrative-Area": "领域",
  "entity_All": "所有实体",
  "entity_Analysis": "分析",
  "entity_Arsenal": "武器库",
  "entity_Artifact": "工件",
  "entity_Attack-Pattern": "攻击模式",
  "entity_Autonomous-System": "自治系统",
  "entity_Bank-Account": "银行账户",
  "entity_Campaign": "攻击活动",
  "entity_Case": "案件",
  "entity_Case-Incident": "事件响应",
  "entity_Case-Rfi": "信息请求",
  "entity_Case-Rft": "要求删除",
  "entity_Channel": "渠道",
  "entity_City": "城市",
  "entity_Country": "国家/地区",
  "entity_Course-Of-Action": "应对措施",
  "entity_Cryptocurrency-Wallet": "加密货币钱包",
  "entity_Cryptographic-Key": "加密密钥",
  "entity_Data-Component": "數據元件",
  "entity_Data-Source": "數據源",
  "entity_Directory": "目录",
  "entity_Domain-Name": "域名",
  "entity_Email-Addr": "电子邮件地址",
  "entity_Email-Message": "电子邮件消息",
  "entity_Email-Mime-Part-Type": "电子邮件扩充部分类型",
  "entity_Entities": "实体",
  "entity_Event": "事件",
  "entity_Events": "事件",
  "entity_External-Reference": "外部引用",
  "entity_Feedback": "反饋",
  "entity_Grouping": "分组",
  "entity_Hostname": "主机名",
  "entity_IPv4-Addr": "IPv4地址",
  "entity_IPv6-Addr": "IPv6地址",
  "entity_Identity": "身份",
  "entity_Incident": "安全事件",
  "entity_Indicator": "攻击指标",
  "entity_Individual": "个体",
  "entity_Infrastructure": "基础设施",
  "entity_Intrusion-Set": "入侵集合",
  "entity_Ipv4-Addr": "IPv4地址",
  "entity_Ipv6-Addr": "IPv6地址",
  "entity_Label": "标签",
  "entity_Language": "语",
  "entity_Location": "地点",
  "entity_Locations": "地點",
  "entity_Mac-Addr": "MAC地址",
  "entity_Malware": "恶意软件",
  "entity_Marking-Definition": "标记定义",
  "entity_Media-Content": "媒体内容",
  "entity_Mutex": "互斥体",
  "entity_Narrative": "叙述",
  "entity_Network-Traffic": "网络流量",
  "entity_Note": "注释",
  "entity_Observable": "觀察",
  "entity_Observations": "觀察",
  "entity_Observed-Data": "可观测数据",
  "entity_Opinion": "意见",
  "entity_Organization": "组织",
  "entity_Payment-Card": "支付卡",
  "entity_Phone-Number": "电话号码",
  "entity_Position": "位置",
  "entity_Process": "进程",
  "entity_Region": "区域",
  "entity_Relationship": "关系",
  "entity_Report": "分組",
  "entity_Sector": "部门",
  "entity_Sighting": "目擊",
  "entity_Software": "软件",
  "entity_Stix-Core-Objects": "STIX核心对象",
  "entity_Stix-Core-Relationship": "STIX核心关系",
  "entity_Stix-Cyber-Observable": "STIX网络可观测数据",
  "entity_Stix-Cyber-Observables": "STIX网络可观测数据",
  "entity_Stix-Domain-Object": "STIX域对象",
  "entity_Stix-Domain-Objects": "STIX域对象",
  "entity_StixFile": "STIX文件",
  "entity_Stixfile": "STIX文件",
  "entity_System": "系统",
  "entity_Techniques": "技術",
  "entity_Text": "文本",
  "entity_Threat-Actor": "威胁源",
  "entity_Threats": "威胁",
  "entity_Tool": "攻击工具",
  "entity_Url": "URL",
  "entity_User-Account": "用户账户",
  "entity_User-Agent": "用户代理",
  "entity_Vulnerability": "脆弱性",
  "entity_Windows-Registry-Key": "Windows注册表键",
  "entity_Windows-Registry-Value-Type": "Windows注册表值类型",
  "entity_X509-Certificate": "X509证书",
  "filter_${filterKey}": "UNDEFINED",
  "filter_assigneeTo": "受让人",
  "filter_basedOn": "基于",
  "filter_containedBy": "包含",
  "filter_createdBy": "作者",
  "filter_createdBy_not_eq": "非作者",
  "filter_elementId": "相关实体",
  "filter_fromId": "源实体",
  "filter_fromTypes": "源类型",
  "filter_killChainPhase": "杀伤链阶段",
  "filter_labelledBy": "标签",
  "filter_labelledBy_not_eq": "非标签",
  "filter_markedBy": "标记",
  "filter_markedBy_not_eq": "非标记",
  "filter_objectContains": "包含",
  "filter_sightedBy": "目击",
  "filter_sightedBy_not_eq": "非目击",
  "filter_toCreatedAt_end_date": "创建结束日期",
  "filter_toCreatedAt_start_date": "创建开始日期",
  "filter_toId": "目标实体",
  "filter_toSightingId": "目击ID",
  "filter_toTypes": "目标类型",
  "hour": "UNDEFINED",
  "name": "姓名",
  "obsContent": "內容",
  "of": "UNDEFINED",
  "on": "UNDEFINED",
  "organization": "组织",
  "relationship_All": "所有关系",
  "reliability_A": "A - 完全可靠",
  "reliability_B": "B - 通常可靠",
  "reliability_C": "C - 相当可靠",
  "reliability_D": "D - 通常不可靠",
  "reliability_E": "E - 不可靠",
  "reliability_F": "F - 可靠性无法判断",
  "selected": "已选",
  "to exclude items": "UNDEFINED",
  "unknown": "未知",
  "week": "UNDEFINED"
}